### ISSUE TITLE
Make Jenkins run tests with OpenSSL

### ISSUE THREAD

**Issue by bellgrim** [opendnssec/SoftHSMv2#138]
Migrated from:
https://issues.opendnssec.org/browse/SOFTHSM-74

**Comment by bellgrim** [comment]
Francis Dupont added a comment - 2014-02-15 14:42
I'd really like to see jenkins setups (this means I shan't help...).

**Comment by halderen** [comment]
Jenkins now runs tesks against  openssl and botan.
