### ISSUE TITLE
Test suite .o files eats a lot of space

### ISSUE THREAD

**Issue by bellgrim** [opendnssec/SoftHSMv2#139]
I've noticed that the .o files from the tests gets really large and the test program also. They currently take over 300meg extra disk space on the test platform nodes. That would mean that one pull request build will eat 400meg disk space and this will be a problem if many pull requests are built since the test platform nodes have limited amount of disk.

A simple strip of the .o files removed 95%.

Can someone look into why they are so big or maybe just strip them?

Other .o files are not striped and does not take much space, may be something wrong with the LDFLAGS.

Migrated from:
https://issues.opendnssec.org/browse/SOFTHSM-77

**Comment by bellgrim** [comment]
Francis Dupont added a comment - 2014-02-15 14:46
Is it related with the visibility configuration option? BTW it is likely platform dependent (for instance visibility gives no direct smaller .o on OSX). 

So my question is: which platform/system? which options (e.g, -g)?

**Comment by bellgrim** [comment]
Jerry Lundström added a comment - 2014-02-17 11:03
I don't know if its related to the visibility option, we just recently added SoftHSMv2 to the test platforms prior to 2.0.0a1 release. 

It affects most platforms, this is a "du -ks" for the Botan and SoftHSMv2 build directory and the root where both was installed. 

ubuntu10-ods01 
154376	/home/jenkins/workspace/pull-SoftHSMv2-58-build 
39396	/home/jenkins/workspace/pull-SoftHSMv2-58-build-botan 
37668	/home/jenkins/workspace/root/pull-SoftHSMv2-58 

ubuntu12-ods02 
305328	/home/jenkins/workspace/pull-SoftHSMv2-58-build 
38956	/home/jenkins/workspace/pull-SoftHSMv2-58-build-botan 
61512	/home/jenkins/workspace/root/pull-SoftHSMv2-58 

suse11-ods05 
160560	/home/jenkins/workspace/pull-SoftHSMv2-58-build 
40164	/home/jenkins/workspace/pull-SoftHSMv2-58-build-botan 
38628	/home/jenkins/workspace/root/pull-SoftHSMv2-58 

freebsd9-ods06.buildfarm.opendnssec.org 
194952	/home/jenkins/workspace/pull-SoftHSMv2-58-build 
42772	/home/jenkins/workspace/pull-SoftHSMv2-58-build-botan 
45812	/home/jenkins/workspace/root/pull-SoftHSMv2-58 

freebsd10-ods07.buildfarm.opendnssec.org 
210928	/home/jenkins/workspace/pull-SoftHSMv2-58-build 
35536	/home/jenkins/workspace/pull-SoftHSMv2-58-build-botan 
44856	/home/jenkins/workspace/root/pull-SoftHSMv2-58 

You can see how Botan is built here: https://github.com/opendnssec/SoftHSMv2/blob/develop/testing/build-botan.sh 
And how SoftHSMv2 is built here: https://github.com/opendnssec/SoftHSMv2/blob/develop/testing/build-softhsm2.sh

**Comment by bellgrim** [comment]
Jerry Lundström added a comment - 2014-02-17 11:05
As stated before, this is only an issue with the .o files related to the tests. Other .o files are also not stripped but they are not bloated like the test .o files.

**Comment by bellgrim** [comment]
Jerry Lundström added a comment - 2014-08-11 10:10
Closing PR https://github.com/opendnssec/SoftHSMv2/pull/58 which is tied to this issue. Can be revised when the handover is done.

**Comment by halderen** [comment]
Not relevant anymore, the Jenkins platform has a more flexible build system keeping a backlog of x tests rather than all current open and can archive old ones.  And has more disk space...
