### ISSUE TITLE
Support AES CTR mode

### ISSUE THREAD

**Issue by bellgrim** [opendnssec/SoftHSMv2#142]
David Fine:
It would be great to see AES GCM and CTR modes supported in SoftHSMv2. OpenSSL already supports these modes.

Migrated from:
https://issues.opendnssec.org/browse/SOFTHSM-116
https://issues.opendnssec.org/browse/SUPPORT-158

**Comment by jhfeng** [comment]
what's timeline for AES-GCM be added ?

**Comment by bellgrim** [comment]
It is currently assigned to v2.2.0, but it is not scheduled in time.

**Comment by xzhan** [comment]
would you mind paste code to us for AES-GCM and AES-CTR

**Comment by bellgrim** [comment]
Sorry, I have not written any code for this yet.

**Comment by bellgrim** [comment]
Splitting this into two issues. AES GCM is now in #325.

**Comment by bellgrim** [comment]
Fixed in #326
