### ISSUE TITLE
Support for Crypto++

### ISSUE THREAD

**Issue by bellgrim** [opendnssec/SoftHSMv2#148]
Francis Dupont:
Tentative support for Crypto++ library.
Works well but unfortunately Crypto++ doesn't support natively some options which are critical for users.
Note the FIPS version is WIN32 binary.
I can pull a request if wanted.

Migrated from:
https://issues.opendnssec.org/browse/SOFTHSM-53

**Comment by bellgrim** [comment]
Francis Dupont added a comment - 2013-12-18 13:15
Tried libgcrypt too without interesting success (note that nettle should be even less interesting...)

**Comment by rijswijk** [comment]
I'm not sure whether supporting Crypto++ really adds much, it is another single-author (mostly anyway) library like Botan. Perhaps we should make this a will not implement for now.
