### ISSUE TITLE
autogen.sh fails on Ubuntu trusty

### ISSUE THREAD

**Issue by jhfeng** [opendnssec/SoftHSMv2#159]
SoftHSMv2# sh autogen.sh
configure.ac:183: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by bellgrim** [comment]
sudo apt-get install libtool ?

**Comment by bellgrim** [comment]
I think we need to update the README.md with some text from:
https://wiki.opendnssec.org/display/SoftHSMDOCS/SoftHSM+Documentation+v2.0

**Building from the repository**
If the code is downloaded directly from the code repository, you have to prepare the configuration scripts.
1. You need to install automake, autoconf, libtool, etc.
2. Run the command 'sh autogen.sh'
3. Continue with the instructions below.

**Comment by jhfeng** [comment]
hmm. I thought I installed it. but apparently not. After installing libtool. autogen.sh works. THANKS
