### ISSUE TITLE
A marked as CA certificate cannot be written in a softhsmv2 db

### ISSUE THREAD

**Issue by nmav** [opendnssec/SoftHSMv2#162]
Trying to write a certificate in a softhsm db with CKA_CERTIFICATE_CATEGORY fails with: CKR_ATTRIBUTE_READ_ONLY

How reproducible:
1. cat >config
directories.tokendir = db
objectstore.backend = file

2. export SOFTHSM2_CONF=config
3. mkdir db
4. softhsm2-util --init-token --slot 0 --label test --so-pin 1234 --pin 1234
5. p11tool --provider /usr/lib64/pkcs11/libsofthsm2.so --write --mark-ca --load-certificate any-cert.pem  --label test --so-login

Output:
Error writing certificate: PKCS #11 error in attribute

Expected Output:
Success.

Writing the same certificate without the mark-ca flag works fine.

The PKCS#11 Spy output is at:
https://bugzilla.redhat.com/show_bug.cgi?id=1272453

**Comment by bellgrim** [comment]
I tried to replicate this using GnuTLS 3.4.5, but it fails to create the object in the correct way. It tries to C_CreateObject() when logged in as SO. It does not set CKA_PRIVATE (which defaults to true). A SO cannot create private objects.

**Comment by bellgrim** [comment]
#164 have a fix for this.

Also had to add --no-mark-private to the p11tool command to get this to work.

**Comment by nmav** [comment]
The login as SO is because of the --so-login option. You may switch it to simply --login.

**Comment by bellgrim** [comment]
Fixed in #164
