### ISSUE TITLE
Allow to set CKF_REMOVABLE_DEVICE flag on a slot

### ISSUE THREAD

**Issue by sumit-bose** [opendnssec/SoftHSMv2#166]
I would like to use SoftHSM for the automatic testing of the SSSD Smartcard authentication feature. We use the CKF_REMOVABLE_DEVICE flag to filter the available slots to make it easier to identify a suitable slot for authentication.

The flags are currently hardcoded to CKF_TOKEN_PRESENT in Slot::getSlotInfo() and we have a special code in SSSD which detects if the PKCS#11 module is softhsm2 and drops the CKF_REMOVABLE_DEVICE check in this case.

It would be nice if softhsm2-util would offer a --slot-flags (or similar) option which would allow to set CKF_REMOVABLE_DEVICE on a given slot and store it together with the other slot specific data like PIN and SO-PIN.

(originally posted as https://issues.opendnssec.org/browse/SUPPORT-178)

**Comment by bellgrim** [comment]
Perhaps we should set CKF_REMOVABLE_DEVICE? We always have a token in each slot, but the tokens can be assigned to other slots (e.g. if a token is removed or a new one is initialized).

From PKCS#11 v2.20:
> For a given slot, the value of the CKF_REMOVABLE_DEVICE flag never changes. In addition, if this flag is not set for a given slot, then the CKF_TOKEN_PRESENT flag for that slot is always set. That is, if a slot does not support a removable device, then that slot always has a token in it.

Maybe we have interpreted the text wrong. We do always have a token in the slot, but not always the same token.

**Comment by rijswijk** [comment]
Rickard Bellgrim wrote:
> Perhaps we should set CKF_REMOVABLE_DEVICE? We always have a token in
> each slot, but the tokens can be assigned to other slots (e.g. if a
> token is removed or a new one is initialized).
> 
> From PKCS#11 v2.20:
> 
>     For a given slot, the value of the CKF_REMOVABLE_DEVICE flag never
>     changes. In addition, if this flag is not set for a given slot, then
>     the CKF_TOKEN_PRESENT flag for that slot is always set. That is, if
>     a slot does not support a removable device, then that slot always
>     has a token in it.
> 
> Maybe we have interpreted the text wrong. We do always have a token in
> the slot, but not always the same token.

It is a matter of taste whether we qualify our slots as
CKF_REMOVABLE_DEVICE; technically speaking, this is intended for things
like smart cards and USB tokens, but if we cannot guarantee that our
tokens are always in the same slot then perhaps cosmetically setting
this flag could be considered. I have no strong opinion either way, am
slightly in favour of keeping the code as-is since we know how software
that uses PKCS #11 deals with our current implementation, and behaviour
may change because of this flag (where said software incorrectly assumes
that they're dealing with an actual removable device like a smart card).

Cheers,

Roland

-- 
-- Roland M. van Rijswijk - Deij
-- SURFnet bv
-- w: http://www.surf.nl/en/about-surf/subsidiaries/surfnet
-- e: roland.vanrijswijk@surfnet.nl

**Comment by sumit-bose** [comment]
On Thu, Oct 22, 2015 at 06:37:58AM -0700, Roland van Rijswijk wrote:
> Rickard Bellgrim wrote:
> > Perhaps we should set CKF_REMOVABLE_DEVICE? We always have a token in
> > each slot, but the tokens can be assigned to other slots (e.g. if a
> > token is removed or a new one is initialized).
> > 
> > From PKCS#11 v2.20:
> > 
> >     For a given slot, the value of the CKF_REMOVABLE_DEVICE flag never
> >     changes. In addition, if this flag is not set for a given slot, then
> >     the CKF_TOKEN_PRESENT flag for that slot is always set. That is, if
> >     a slot does not support a removable device, then that slot always
> >     has a token in it.
> > 
> > Maybe we have interpreted the text wrong. We do always have a token in
> > the slot, but not always the same token.
> 
> It is a matter of taste whether we qualify our slots as
> CKF_REMOVABLE_DEVICE; technically speaking, this is intended for things
> like smart cards and USB tokens, but if we cannot guarantee that our
> tokens are always in the same slot then perhaps cosmetically setting
> this flag could be considered. I have no strong opinion either way, am
> slightly in favour of keeping the code as-is since we know how software
> that uses PKCS #11 deals with our current implementation, and behaviour
> may change because of this flag (where said software incorrectly assumes
> that they're dealing with an actual removable device like a smart card).

I agree with the concern that changing the default might irritate
applications explicitly looking for slots which do not have
CKF_REMOVABLE_DEVICE set. But do you think it would be possible to make
the flags configurable with softhsm2-util --init-token?

bye,
Sumit

**Comment by rijswijk** [comment]
Hi Sumit,

sumit-bose wrote:
> On Thu, Oct 22, 2015 at 06:37:58AM -0700, Roland van Rijswijk wrote:
>> Rickard Bellgrim wrote:
>> > Perhaps we should set CKF_REMOVABLE_DEVICE? We always have a token in
>> > each slot, but the tokens can be assigned to other slots (e.g. if a
>> > token is removed or a new one is initialized).
>> >
>> > From PKCS#11 v2.20:
>> >
>> > For a given slot, the value of the CKF_REMOVABLE_DEVICE flag never
>> > changes. In addition, if this flag is not set for a given slot, then
>> > the CKF_TOKEN_PRESENT flag for that slot is always set. That is, if
>> > a slot does not support a removable device, then that slot always
>> > has a token in it.
>> >
>> > Maybe we have interpreted the text wrong. We do always have a token in
>> > the slot, but not always the same token.
>>
>> It is a matter of taste whether we qualify our slots as
>> CKF_REMOVABLE_DEVICE; technically speaking, this is intended for things
>> like smart cards and USB tokens, but if we cannot guarantee that our
>> tokens are always in the same slot then perhaps cosmetically setting
>> this flag could be considered. I have no strong opinion either way, am
>> slightly in favour of keeping the code as-is since we know how software
>> that uses PKCS #11 deals with our current implementation, and behaviour
>> may change because of this flag (where said software incorrectly assumes
>> that they're dealing with an actual removable device like a smart card).
> 
> I agree with the concern that changing the default might irritate
> applications explicitly looking for slots which do not have
> CKF_REMOVABLE_DEVICE set. But do you think it would be possible to make
> the flags configurable with softhsm2-util --init-token?

This is certainly feasible although the use case seems somewhat limit.
Would you consider writing the code and submitting a pull request that
we can evaluate and integrate?

Cheers,

Roland

-- 
-- Roland M. van Rijswijk - Deij
-- SURFnet bv
-- w: http://www.surf.nl/en/about-surf/subsidiaries/surfnet
-- e: roland.vanrijswijk@surfnet.nl

**Comment by sumit-bose** [comment]
On Fri, Oct 23, 2015 at 09:14:35AM -0700, Roland van Rijswijk wrote:
> Hi Sumit,
> 
> sumit-bose wrote:
> > On Thu, Oct 22, 2015 at 06:37:58AM -0700, Roland van Rijswijk wrote:
> >> Rickard Bellgrim wrote:
> >> > Perhaps we should set CKF_REMOVABLE_DEVICE? We always have a token in
> >> > each slot, but the tokens can be assigned to other slots (e.g. if a
> >> > token is removed or a new one is initialized).
> >> >
> >> > From PKCS#11 v2.20:
> >> >
> >> > For a given slot, the value of the CKF_REMOVABLE_DEVICE flag never
> >> > changes. In addition, if this flag is not set for a given slot, then
> >> > the CKF_TOKEN_PRESENT flag for that slot is always set. That is, if
> >> > a slot does not support a removable device, then that slot always
> >> > has a token in it.
> >> >
> >> > Maybe we have interpreted the text wrong. We do always have a token in
> >> > the slot, but not always the same token.
> >>
> >> It is a matter of taste whether we qualify our slots as
> >> CKF_REMOVABLE_DEVICE; technically speaking, this is intended for things
> >> like smart cards and USB tokens, but if we cannot guarantee that our
> >> tokens are always in the same slot then perhaps cosmetically setting
> >> this flag could be considered. I have no strong opinion either way, am
> >> slightly in favour of keeping the code as-is since we know how software
> >> that uses PKCS #11 deals with our current implementation, and behaviour
> >> may change because of this flag (where said software incorrectly assumes
> >> that they're dealing with an actual removable device like a smart card).
> > 
> > I agree with the concern that changing the default might irritate
> > applications explicitly looking for slots which do not have
> > CKF_REMOVABLE_DEVICE set. But do you think it would be possible to make
> > the flags configurable with softhsm2-util --init-token?
> 
> This is certainly feasible although the use case seems somewhat limit.
> Would you consider writing the code and submitting a pull request that
> we can evaluate and integrate?
> 

sure, I'll have a look at the code.

Thank you.

bye,
Sumit

**Comment by bellgrim** [comment]
Thank you, the code has been merged. Closing this issue.
