### ISSUE TITLE
Problem while closing library that is initialized but improperly finalized.

### ISSUE THREAD

**Issue by halderen** [opendnssec/SoftHSMv2#171]
There is a segmentation violation when closing the softhsm2 library when it was opened dynamically using dlopen().  It happens when the library is initialized using C_Initialize(), but no C_Finalize is called prior unloading the library.

```c
int
main(int argc, char** argv)
{
    int i;
    void* handle;
    void* symbol;
    CK_FUNCTION_LIST_PTR table;
    CK_SESSION_HANDLE session;
    handle = dlopen("/usr/local/lib/softhsm/libsofthsm2.so", RTLD_NOW | RTLD_LOCAL);
    symbol = dlsym(handle, "C_GetFunctionList");
    ((CK_C_GetFunctionList) symbol)(&table);
    table->C_Initialize(&InitArgs);
    return 0;
}
```
Note the dlclose is implicit here, but an explicit dlclose as the end results in about the same.  It will result in
```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f7cc62ad943 in SoftHSM::C_Finalize (this=0x11d5390, pReserved=0x0)
    at SoftHSM.cpp:513
513		if (handleManager != NULL) delete handleManager;
```
Simply because all the vptr is already gone.  My personal take would be to remove the libcleanup() function alltogether, it is an attempt to close off properly when the calling program has not done so (which is the case above), but that won't always work properly.

**Comment by bellgrim** [comment]
Thank you for the report, this has now been fixed in #171
