### ISSUE TITLE
CKR_TEMPLATE_INCOMPLETE vs. _INCONSISTENT

### ISSUE THREAD

**Issue by vanrein** [opendnssec/SoftHSMv2#173]
Hello,

Going through C_DeriveKey, I was a bit surprised about the use of the CK_RV values in the subject; I would often expect them to be used the other way around in relation to CKA_VALUE / CKA_VALUE_LEN:
 _INCOMPLETE when CKA_VALUE_LEN is missing
 _INCONSISTENT when the values are wrong in combination with other places

Maybe this is worth some attention; it almost appears as though a too-automatic search & replace has confused the two.  Let me know if you want concrete places.

-Rick

**Comment by bellgrim** [comment]
Thanks for spotting this. Do you agree on the new return values in #176 ?

**Comment by vanrein** [comment]
Hi Rickard,

> Thanks for spotting this. Do you agree on the new return values in #176 ?

It included the one I was surprised by... and a lot more :) that I can't comment on.

Thanks!
 -Rick
