### ISSUE TITLE
CKA_NEVER_EXTRACTABLE set to CK_FALSE on objects created with C_CreateObject function

### ISSUE THREAD

**Issue by jariq** [opendnssec/SoftHSMv2#177]
It seems that guys from Cryptosense were performing [PKCS#11 compliance tests with SoftHSM2](https://cryptosense.com/pkcs11-functionality-reports/) and published [report with one critical issue](https://cryptosense.com/resources/Compliance_Report-SoftHSM.html). According to their report it seems that SoftHSM2 does not set `CKA_NEVER_EXTRACTABLE` attribute to `CK_FALSE` on objects created with `C_CreateObject` function. I don't have enough time to verify if this is true but I wanted to let you know of their finding.

**Comment by bellgrim** [comment]
Thanks for reporting this. Have a patch in #179
