### ISSUE TITLE
The OSSLCryptoFactory class destructor should not clean up the CRYPTO library state

### ISSUE THREAD

**Issue by mtrojnar** [opendnssec/SoftHSMv2#181]
This crashes other code that also uses libcrypto.  See https://github.com/OpenSC/libp11/issues/51#issuecomment-169831003 for details.

**Comment by bellgrim** [comment]
Is there a way of checking if OpenSSL has already been initialized by the calling application?

Compare https://github.com/opendnssec/SoftHSMv2/blob/63f5e89393b12062e0db7ef6429a160f98962e23/src/lib/crypto/OSSLCryptoFactory.cpp#L110 with  https://github.com/opendnssec/SoftHSMv2/blob/63f5e89393b12062e0db7ef6429a160f98962e23/src/lib/crypto/BotanCryptoFactory.cpp#L64

**Comment by bellgrim** [comment]
The order should be:
* Application initialize crypto library
* Application initialize PKCS#11 library
* PKCS#11 library initialize crypto library, if not initialized by the calling application
* Application finalize PKCS#11 library
* PKCS#11 library clean up crypto library, if it was initialized by the PKCS#11 library
* Application clean up crypto library

**Comment by mtrojnar** [comment]
It is a bit more complex.  There is no single call to initialize libcrypto:
https://wiki.openssl.org/index.php/Library_Initialization#libcrypto_Initialization
The application may only initialize a few algorithms it intends to use.  This is safe with libcrypto, because libcrypto initialization (unlike libcrypto clean-up or PKCS#11 initialization) does __not__ remove any accumulated internal state of the library.  The initialization of every libcrypto component (for example an algorithm) has an internal check to prevent double initialization.  It is also perfectly okay for the application to initialize the PKCS#11 library, and then initialize the libcrypto for the algorithms it wants to use directly.

As long as the application is still allowed to use libcrypto after PKCS#11 finalization, the __only__ solution is to leave all the libcrypto clean-up to the application.

**Comment by jariq** [comment]
It might be interesting to check how is PKCS#11 module provided by OpenSC (opensc-pkcs11.so) dealing with this. AFAIK it uses OpenSSL for general cryptographic tasks too so its authors were probably facing the same problem.

**Comment by mtrojnar** [comment]
OpenSC simply never invokes `ENGINE_cleanup()`...

**Comment by mtrojnar** [comment]
This is a critical issue with a very simple fix available as https://github.com/opendnssec/SoftHSMv2/pull/184.  Please merge it.

**Comment by bellgrim** [comment]
Thank you for the fix, have merged the code.

**Comment by mtrojnar** [comment]
Thank you for merging it.

**Comment by mtrojnar** [comment]
And it's broken again after https://github.com/opendnssec/SoftHSMv2/commit/f1a84745fa981473a4be9ffcf4413fc67e0d8ff7

Please remember that SoftHSM2 is a **library**, and quite likely **not** the only code that uses OpenSSL in an application.  Some other code my still need OpenSSL **after** SoftHSMv2 executed OSSLCryptoFactory::~OSSLCryptoFactory().
