### ISSUE TITLE
"Funny behaviour" when using C_InitToken() from GnuTLS' p11tool

### ISSUE THREAD

**Issue by vanrein** [opendnssec/SoftHSMv2#186]
I am not getting what I expected when using the GnuTLS generic utility `p11tool` for token initialisation (of an already existing token):

    GNUTLS_PIN=1234 p11tool --provider /path/to/softhsm2.so --initialize 'pkcs11:yada;yada;yada'

This calls `C_InitToken()` on the slot holding the token found in the slot referenced by `pkcs11:yada;yada;yada`:

 * https://gitlab.com/gnutls/gnutls/blob/gnutls_3_4_9/src/p11tool.c#L289
 * https://gitlab.com/gnutls/gnutls/blob/gnutls_3_4_9/src/pkcs11.c#L886
 * https://gitlab.com/gnutls/gnutls/blob/gnutls_3_4_9/lib/pkcs11_write.c#L1168
 * https://gitlab.com/gnutls/gnutls/blob/gnutls_3_4_9/lib/pkcs11_int.c#L244

The `C_InitToken()` function requires the SO-PIN, but after entering it `p11tool` consistently fails.  It seems that the token may be completely destroyed by the call, which is not what I would have expected.  To be honest, I am confused what is really going on.  My expectation was that the token would continue to exist, but with all private keys removed and the user PIN removed.

I am assuming that SoftHSMv2 is the problem, because tokens seem to be removed.  But I cannot be completely certain, of course.

**Comment by bellgrim** [comment]
Running C_IninToken() on an already initialized token will re-initialize it. Thus removing all objects.

SoftHSMv2 does this by removing the directory of the token and initializing a new token in the same slot. Maybe we should just remove the objects and set the new token label?

**Comment by vanrein** [comment]
Re-initialisation is the expected behaviour, but it does not seem to get out just the right way.  May caches are reset, or locks abolished?  I cannot make out if the token directory itself would be removed, or just its contents, but that is probably the difference you are talking about here.  Removing the token directory could easily cause such hick-ups of course.  Or producing a new random name for that directory.

I'm afraid I can't answer whether this would solve the behaviour I detected.  Is there anything I can do to test this further, and help to resolve the detected behaviour?

**Comment by larssilven** [comment]
I checked the p11tool that happened to be on my laptop.
The token urls (your pkcs11:yada;yada;yada) look like this for my softhsm tokens:
pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=829ea16d170b6dfd;token=sender
pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=c485591f9bcebb67;token=receive
Keeping the token directory name will keep the serial number. So if the name of the directory is kept and if you initialize with same label then the token will be references with same url both before and after the initialization.

**Comment by bellgrim** [comment]
Working on a patch where we keep the token, but destroy the objects, change the label and remove the user PIN.

**Comment by bellgrim** [comment]
Does it work better with the fix in #204 ?

**Comment by vanrein** [comment]
It does not appear to make a difference, according to the following test flow:

```
shell# make rebuild-pkcs11
#
# WARNING -- PROCEED WITH CARE
#
# About to wipe your PKCS #11 object store.
# If this is unintended, stop now.
#
GNUTLS_PIN=1234 p11tool --provider /usr/local/lib/softhsm/libsofthsm2.so --login --initialize 'pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;token=TLS_Pool_test_data'
Enter Security Officer's PIN: 
Error in pkcs11_init:895: The requested PKCS #11 object is not available
make: *** [clean-pkcs11] Error 1

shell# less ../etc/tlspool.conf

shell# ls -l /usr/local/lib/softhsm/libsofthsm2.so
-rwxr-xr-x 1 root staff 7157033 Mar 31 09:08 /usr/local/lib/softhsm/libsofthsm2.so

shell# ls -l /var/lib/softhsm/tokens/
total 28
...
drwx------ 2 root    root    4096 Mar 31 09:15 707d7ce8-79e9-2147-9036-3089294137cc
...
```

As the added statements show, I did install the recently built SoftHSMv2; its two latest log entries are

```
commit ba6620c2de19758b593581d44a35ab31ec58c8d5
Author: Rickard Bellgrim <rickard@opendnssec.org>
Date:   Tue Mar 29 01:57:21 2016 +0200

    Issue #186: Update NEWS and add more tests

commit 92d509a44ddcf7cc30764cbff07b58658e92c94f
Author: Rickard Bellgrim <rickard@opendnssec.org>
Date:   Tue Mar 29 00:50:36 2016 +0200

    Issue #186: Keep the token, but destroy the objects, change the label and remove the

```

**Comment by bellgrim** [comment]
I used pkcs11-spy and noticed that p11tool does not set the token label upon C_InitToken(). It can thus not find the token again because it has changed the token label.

```
6: C_InitToken
2016-03-31 21:43:06.230
[in] slotID = 0x2f00588a
[in] pPin[ulPinLen] 00007fffa1f77fd0 / 4
    00000000  31 32 33 34                                      1234            
[in] pLabel[32] 00007fffa1f77f70 / 32
    00000000  20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                  
    00000010  20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                  
Returned:  0 CKR_OK
```

It works better when you provide **--label** to **p11tool.**

**Comment by vanrein** [comment]
Thank you -- this clarifies that the remainder of the cause lies with p11tool.  I should therefore look at GnuTLS for further resolution.

**Comment by vanrein** [comment]
Sorry, I probably should not have closed this issue, since you do have a patch that still needs to enter mainstream.  I'm reopening it to let you do the closing on this matter :)
