### ISSUE TITLE
Visual Studio: Cannot open include file: 'openssl/conf.h': No such file or directory in several modules

### ISSUE THREAD

**Issue by koh-osug** [opendnssec/SoftHSMv2#187]
The include path for OpenSSL is not set correctly by the perl script.

I had to manually add the include path to the following modules:

- objstoretest
- p11test
- datamgrtest
- softhsm2
- slotmgrtest

Adding

     '@INCLUDEPATH@;@CUINCPATH@;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>' 

in all visual studio input files is fixing this in the `Debug` and `Release`configuration is fixing this.

Attached is a fix:

[softhsm2.txt](https://github.com/opendnssec/SoftHSMv2/files/120537/softhsm2.txt)

__Note__: I was not using the path C:\build for building the library.

**Comment by bellgrim** [comment]
This was fixed in #180
