### ISSUE TITLE
p11test test error

### ISSUE THREAD

**Issue by koh-osug** [opendnssec/SoftHSMv2#188]
p11test.exe
..................F.........................................

!!!FAILURES!!!
Test Results:
Run:  59   Failures: 1   Errors: 0

1) test: InfoTests::testGetSlotInfoAlt (F) line: 209 ..\..\src\lib\test\InfoTest
s.cpp
assertion failed
- Expression: rv == CKR_OK

**Comment by bellgrim** [comment]
Initialization of SoftHSM failed in this case. Do you have more details from the logs?

**Comment by koh-osug** [comment]
Unfortunately not, I did the proposed tests after building the sources. The test results are not verbose, I just see one dot for one test.

I'm executing this under Windows, build with VS 2013 in 64 bit.

**Comment by bellgrim** [comment]
This issue has now been fixed in #202.
