### ISSUE TITLE
CKR_KEY_INDIGESTIBLE in C_DigestKey when key CKA_EXTRACTABLE = false

### ISSUE THREAD

**Issue by koh-osug** [opendnssec/SoftHSMv2#189]
I cannot find that this behavior is defined in the PKCS#11 spec.In fact it is necessary to allow this to build key derivation functions (KDF) based on the hash of the key. I have not tried to use a `C_DeriveKey` with e.g. `CKM_SHA1_KEY_DERIVATION` because I do want to create a key on the token and my KDF is also using a salt in the beginning. 

Neither in the function definition of `C_DigestKey` on page 148 nor on Page 92,  V2.30:

> CKR_KEY_INDIGESTIBLE: This error code can only be returned by C_DigestKey.
> It indicates that the value of the specified key cannot be digested for some reason
> (perhaps the key isn’t a secret key, or perhaps the token simply can’t digest this kind
> of key). 

The same is true for the `CKA_SENSITIVE` check which should be removed to be spec compliant.

**Comment by bellgrim** [comment]
Please see #29 for more details on why we added this check. There is nothing in the spec that disallow this behavior. The text "for some reason" makes it valid to make a policy decision. But the check could be  removed if we find it unusable.

**Comment by koh-osug** [comment]
What about white listing the trusted hash schemes like SHA-X? The arguments in #26 do not apply here. When looking into the code I see that in `C_DeriveKey` `CKM_SHA1_KEY_DERIVATION` is not supported. So this does not seem to be an option as alternative.
Is there any other way how you are supporting key derivation schemes based on a given key?

Is there a chance in the future to support key derivation schemes using a nonce, e.g. just nonce+key or more elaborate schemes like HKDF?

**Comment by bellgrim** [comment]
A good option would be to implement CKM_SHA1_KEY_DERIVATION in SoftHSM. Currently we only support CKM_DH_PKCS_DERIVE, CKM_ECDH1_DERIVE, CKM_DES_ECB_ENCRYPT_DATA, CKM_DES_CBC_ENCRYPT_DATA, CKM_DES3_ECB_ENCRYPT_DATA, CKM_DES3_CBC_ENCRYPT_DATA, CKM_AES_ECB_ENCRYPT_DATA, CKM_AES_CBC_ENCRYPT_DATA. 

Or as you say to whitelist algorithms like SHA-X.

What would you prefer? With the derive option there is still a possibility to keep the derived key "on-board".

**Comment by koh-osug** [comment]
I'm fine with both options, the white listing is good enough for me right now, because it opens the complete SHA has family and I do not need the key after the derivation.

**Comment by bellgrim** [comment]
We will do whitelisting of algorithms for C_DigestKey().

**Comment by bellgrim** [comment]
Fixed in #300

**Comment by koh-osug** [comment]
Thanks. I have now finally updated the SoftHSMv2 library and not using my patched version anymore.
