### ISSUE TITLE
Can write CSP based on SoftHSM?

### ISSUE THREAD

**Issue by chenhuang511** [opendnssec/SoftHSMv2#191]
Hi,

As the title, i want to write a CSP library for logon, sign, web authentication...on Windows. Can i do that based on SoftHSM? Has somebody can give me some hints?

**Comment by bellgrim** [comment]
Sorry, do not have the details on how to implement a CSP library. Maybe there is already a CSP library that can talk PKCS#11. The information on this page is outdated, but may give some hints: https://github.com/OpenSC/OpenSC/wiki/Windows-CSP-(CryptoAPI)

**Comment by hablutzel1** [comment]
@bellgrim , link is dead, by change it was referring to the (apparently dead) CSP #11 project (https://web.archive.org/web/20071003014559/http://csp11.labs.libre-entreprise.org/explanations)?.
