### ISSUE TITLE
Unable to build using VS2015 community on Windows 10.

### ISSUE THREAD

**Issue by CharlesLuotsinen** [opendnssec/SoftHSMv2#201]
Hi.
I am following the "Building SoftHSM2 for Windows" guide and have encountered issues.
Visual Studio 2015 community is failing to build with the following errors:
`Severity	Code	Description	Project	File	Category	Source
Error`
`LNK2001	unresolved external symbol "public: virtual class ByteString __thiscall AESKey::getKeyCheckValue(void)const " (?getKeyCheckValue@AESKey@@UBE?AVByteString@@XZ)	datamgrtest	C:\build\src\softhsm-2.1.0\win32\datamgrtest\convarch.lib(RFC4880.obj)		Build
`

This error repeats for the majority of the projects.

Any thoughts on what I should do to resolve it?

Attached are all the vs2015 errors and output of the Configuration script.
[softhsm2problems.txt](https://github.com/opendnssec/SoftHSMv2/files/181396/softhsm2problems.txt)

regards
Charles Luotsinen

**Comment by bellgrim** [comment]
It should now be fixed in #202

**Comment by CharlesLuotsinen** [comment]
Thank you! Very cool! I will test this when I get home!

**Comment by CharlesLuotsinen** [comment]
Hi.
I manually applied the fix and it builds great now. I ran the tests and p11test.exe fails with the following:

C:\build\src\SoftHSMv2\win32\Release>p11test.exe
..................F...........................................


!!!FAILURES!!!
Test Results:
Run:  61   Failures: 1   Errors: 0


1) test: InfoTests::testGetSlotInfoAlt (F) line: 209 ..\..\src\lib\test\InfoTests.cpp
assertion failed
- Expression: rv == CKR_OK

**Comment by bellgrim** [comment]
Ok, this is a similar issue as in #188. It has now been fixed in #202.
