### ISSUE TITLE
ecdsa very slow for Botan

### ISSUE THREAD

**Issue by larssilven** [opendnssec/SoftHSMv2#213]
I did these tests:

p11speed --slot 952532873 --sign --threads 20 --iterations 200 --mechanism ECDSA --keysize 384 --pin senderPass --module /usr/local/lib/softhsm-botan-1.10/libsofthsm2.so
Creating 200 signatures with ECDSA using 20 threads...
.
20 threads, 200 signatures per thread, 75.65 sig/s (ECDSA 384 bits)

p11speed --slot 952532873 --sign --threads 20 --iterations 200 --mechanism ECDSA --keysize 384 --pin senderPass --module /usr/local/lib/softhsm-openssl/libsofthsm2.so
Creating 200 signatures with ECDSA using 20 threads...
.
20 threads, 200 signatures per thread, 2528.53 sig/s (ECDSA 384 bits) 

I tried also to build with 1.11.29 but failed.

Is this a problem or is it just something fishy with the p11speed?

Is it possible to build with Botan 1.11.xx?

Cheers,
Lars

**Comment by larssilven** [comment]
Now I have also tested with botan 1.11.33. About the same figures.

So is botan just extremely slow or could it be something with  OpenHSM? Maybe some locking preventing threads to be executed simultaneously? But when I use top it seems that all threads are close to 100% cpu with botan.
If someone could just confirm that botan has very slow ecdsa we could close the issue.

**Comment by bellgrim** [comment]
Adding it to 2.3 so that we test and investigate the performance of ECDSA in Botan.

**Comment by bellgrim** [comment]
Here I have some results when comparing raw OpenSSL, raw Botan, SoftHSM with OpenSSL, and SoftHSM with Botan.

Versions:
```
$ openssl version
OpenSSL 1.1.0e  16 Feb 2017
$ botan version
2.1.0
```

Using the following commands. Not using multiple threads since the Botan speed tests does not support that. secp521r1 is available in SoftHSM, but not implemented in p11speed:
```
$ openssl speed ecdsap256 ecdsap384 ecdsap521
$ p11speed --sign --slot 1845771071 --mechanism ECDSA --keysize 256 --threads 1 --iterations 100000
$ p11speed --sign --slot 1845771071 --mechanism ECDSA --keysize 384 --threads 1 --iterations 100000
$ botan speed --msec=10000 ECDSA
$ p11speed --sign --slot 1845771071 --mechanism ECDSA --keysize 256 --threads 1 --iterations 10000
$ p11speed --sign --slot 1845771071 --mechanism ECDSA --keysize 384 --threads 1 --iterations 10000
```

Test summary:

Algo|OpenSSL|SoftHSM-O|Botan|SoftHSM-B
----|----------|-----------|------|------------
secp256r1 | 17472.3 | 9639.07 | 213 | 188.60
secp384r1 | 4067.4 | 1033.01 | 140 | 134.52
secp521r1 | 1951.9 | N/A | 98 | N/A

This issue is currently not in SoftHSM, but in Botan. Will forward the issue to the Botan developers.

**Comment by bellgrim** [comment]
Some additional information from https://github.com/randombit/botan/issues/664#issuecomment-253211974:

> Yes, ECDSA with secp256k1 curve is supported. But, Botan does not take advantage of the endomorphisms that allow fast scalar multiplies on the Koblitz curves or any other special curve-specific logic, it just uses the generic Weierstrass form, so it will be rather slower (guessing maybe 2-10x?) than special purpose code like libsecp256k1

**Comment by bellgrim** [comment]
Closing this issue. It is not an issue in SoftHSM but in Botan.
