### ISSUE TITLE
softhsm2-util fails to run on Mac OS X

### ISSUE THREAD

**Issue by mouse07410** [opendnssec/SoftHSMv2#215]
Platform: Mac OS X 10.11.5, Xcode-7.3.1, Macports-installed OpenSSL-1.0.2h
SoftHSMv2: 2.1.0 (current GitHub master)

Build process (after cloning):
```
$ bash ./autogen.sh
. . . . .
$ ./configure --prefix=/opt/local --enable-64bit
. . . . . [normal configuration]
$ make all && make check
. . . . . [normal build, all checks passed]
$ 
```

All the checks passed.

However, when I try to run `softhsm2-util --init-token --slot 0 --label "Soft Token 1"`, I'm getting this error:

```
$ softhsm2-util --init-token --slot 0 --label "Soft Token 1"
ERROR: Could not initialize the library.
$ softhsm2-util --version
2.1.0
$ otool -L /opt/local/bin/softhsm2-util
/opt/local/bin/softhsm2-util:
	/opt/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
$
```

System log has these (strange) entries:
```
7/5/16 19:36:45.480 softhsm2-util[8385]: SimpleConfigLoader.cpp(84): Could not open the config file: /Users/uri/softhsm.conf

7/5/16 19:36:45.480 softhsm2-util[8385]: Configuration.cpp(158): Failed to load the SoftHSM configuration

7/5/16 19:37:49.099 softhsm2-util[8388]: ObjectStore.cpp(59): Failed to enumerate object store in /opt/local/var/lib/softhsm/tokens/

7/5/16 19:37:49.099 softhsm2-util[8388]: SoftHSM.cpp(476): Could not load the object store
7/5/16 19:37:56.022 softhsm2-util[8389]: ObjectStore.cpp(59): Failed to enumerate object store in /opt/local/var/lib/softhsm/tokens/
```

Help would be appreciated!

**Comment by mouse07410** [comment]
It appears that `softhsm2-util` can only be used by privileged user. I wish documentation mentioned that fact.

It also looks like it searches for `~/softhsm.conf`, instead of `~/.config/softhsm2/softhsm2.conf` as the doc says it should.

**Comment by mouse07410** [comment]
I acknowledge there is no bug, but gracing this plea for help with a response wouldn't have killed you.

**Comment by bellgrim** [comment]
Sorry for a late reply (summer vacation).

It looks like this is a bug.

The Makefile.am will install the configuration file using this command:

```
test -f ${DESTDIR}${sysconfdir}/softhsm2.conf || \
		${INSTALL_DATA} ${top_builddir}/src/lib/common/softhsm2.conf ${DESTDIR}${sysconfdir}
```

Could you check what sysconfdir is set to in config.log, right after running configure?

It is also strange that man page is using another path to configuration file. It should be the same as the software is using. Which man page is have the bad info?

This issue could be related to the use of --prefix, which will change the behavior of acx_prefixhack.m4.

**Comment by bellgrim** [comment]
There should be nothing wrong with the man page for softhsm2.conf

This was from the man page when I used --prefix=/home/user/test/
```
FILES
       ~/.config/softhsm2/softhsm2.conf
              default  user-specific  location  of  the  SoftHSM configuration
              file; if it exists it will override the system  wide  configura‐
              tion

       /home/user/test/etc/softhsm2.conf
              default system-wide location of the SoftHSM configuration file

       /home/user/test/etc/softhsm2.conf.sample
              an example of a SoftHSM configuration file
```

As the doc says: `~/.config/softhsm2/softhsm2.conf` is a user-specific file. If it does not exist then it uses the system-wide location.

**Comment by bellgrim** [comment]
The location `/Users/uri/softhsm.conf`looks odd. The configuration file should be named softhsm2.conf by default. Are you using an environment variable to change the location of the configuration file?

**Comment by bellgrim** [comment]
As a comment to my previous comment: acx_prefixhack.m4 is behaving correctly when using --prefix.

**Comment by bellgrim** [comment]
The token directory has been granted some more liberal access in #185. This is so that all users can create tokens in a shared token directory, but only read their own tokens.

**Comment by bellgrim** [comment]
I could successfully initialize a token when running `softhsm2-util`from `${prefix}/bin`.

This was on Ubuntu, so it might be a problem on Mac OS X.

**Comment by mouse07410** [comment]
> Could you check what sysconfdir is set to in config.log, right after running configure?

```
$ ./configure --prefix=/opt/local -enable-64bit --with-openssl=/opt/local --with-botan=/opt/local
. . . . .
$ grep sysconfdir config.log
sysconfdir='${prefix}/etc'
```

> It is also strange that man page is using another path to configuration file. It should be the same as the software is using. Which man page is have the bad info?

It was not from the debug trace, when I was trying to find out what it is that `softhsm2-util` seems to be missing. And it was looking for `~/sofhhsm.conf` file. But after your question about env variables, I found that indeed one was set (no idea why). I've removed that setting now.

> As the doc says: `~/.config/softhsm2/softhsm2.conf` is a user-specific file. If it does not exist then it uses the system-wide location.

Yes I know. But `softhsm2-util` was unable to access tokens directory until I created that user-specific file and pointed at a directory within my home tree (with user-level access permitted). When user-privileged (not root-privileged) `softhsm2-util` tried to initialize a token using system-wide config file that pointed at `directories.tokendir = /opt/local/var/lib/softhsm/tokens/`, access failed. This is how it was installed:
```
$ ll /opt/local/var/lib/softhsm/
total 0
drwxr-xr-x  3 root  admin  102 Jan  3  2016 ./
drwxr-xr-x  5 root  admin  170 Jan  3  2016 ../
drwx------  4 root  admin  136 Jul  7 01:02 tokens/
$ 
```

> The location `/Users/uri/softhsm.conf` looks odd. 

I could not agree more. ;-)

> The configuration file should be named `softhsm2.conf` by default. 

I completely agree.

> Are you using an environment variable to change the location of the configuration file?

Shame on me - it appears that I did (no idea when/how/why that setting got into `.bashrc`). 

> The token directory has been granted some more liberal access in #185. This is so that all users can create tokens in a shared token directory, but only read their own tokens.

I don't think it was sufficient. One user commented in the #185 thread:

> If SoftHSMv2 is installed by an administrator for the use by anyone on the system, then this won't work.  The flags I suggested are AFAIK what is needed to make users create tokens on a system-wide install and still not being able to view each other's tokens.

Anyways, you saw how it is installed.

**Comment by bellgrim** [comment]
I could not replicate this on OSX. I installed it using the instructions in OSX-NOTES and with your additional configure flags.

```
$ ../configure --with-objectstore-backend-db  --with-openssl=/usr/local/opt/openssl  --with-sqlite3=/usr/local/opt/sqlite --prefix=/opt/local --enable-64bit
$ make
$ make check
$ sudo make install
```

Remove the global config and add a local config to the user. Just to show that SoftHSM can use a local configuration.

```
$ sudo mv /opt/local/etc/softhsm2.conf /opt/local/etc/softhsm2.conf.old
$ sudo mkdir -p /Users/user/.config/softhsm2/
$ sudo cp /opt/local/etc/softhsm2.conf.old /Users/user/.config/softhsm2/softhsm2.conf
$ sudo chown -R user:staff /Users/user/.config/
```

```
$ id
uid=503(user) gid=20(staff) groups=20(staff),701(com.apple.sharepoint.group.2),12(everyone),61(localaccounts),401(com.apple.sharepoint.group.1),100(_lpoperator)

$ ls -al /Users/user/.config/softhsm2/
total 8
drwxr-xr-x  3 user  staff  102 23 Sep 10:05 .
drwxr-xr-x  3 user  staff  102 23 Sep 10:03 ..
-rw-r--r--  1 user  staff  166 23 Sep 10:03 softhsm2.conf

$ softhsm2-util --show-slots
Available slots:
Slot 0
    Slot info:
        Description:      SoftHSM slot ID 0x0                                             
        Manufacturer ID:  SoftHSM project                 
        Hardware version: 2.1
        Firmware version: 2.1
        Token present:    yes
    Token info:
        Manufacturer ID:  SoftHSM project                 
        Model:            SoftHSM v2      
        Hardware version: 2.1
        Firmware version: 2.1
        Serial number:                    
        Initialized:      no
        User PIN init.:   no
        Label:                                            

$ softhsm2-util --init-token --slot 0 --label "Soft Token 1"
=== SO PIN (4-255 characters) ===
Please enter SO PIN: ****
Please reenter SO PIN: ****
=== User PIN (4-255 characters) ===
Please enter user PIN: ****
Please reenter user PIN: ****
The token has been initialized.

$ ls -al /opt/local/var/lib/softhsm/tokens/
total 0
drwxrwxrwt  3 root  admin  102 23 Sep 10:08 .
drwxr-xr-x  3 root  admin  102 23 Sep 09:06 ..
drwx------  5 user  admin  170 23 Sep 10:08 8d2ea9b1-2a57-11b2-d8df-fd12792b7d47
```

**Comment by yerlibilgin** [comment]
I experienced the same issue. I realized that /var/lib/softhsm2/tokens must exist and be accessible by the user (chmod ...)
