### ISSUE TITLE
OSSLCryptoFactory should provide option to not override OpenSSL locking callback

### ISSUE THREAD

**Issue by matthauck** [opendnssec/SoftHSMv2#216]
Suppose an application has its own implementation for CRYPTO_set_id_callback and CRYPTO_set_locking_callback, adding SoftHSM2 with openssl results in clobbering those callbacks with its own in OSSLCryptoFactory's constructor. There are no flags (either compile time or runtime) to turn off this behavior, which is rather unfortunate. It results in a segfault when SoftHSM gets unloaded but other OpenSSL operations continue...

**Comment by matthauck** [comment]
Hmm. Looks like this may have been only when linking against openssl dynamically. If linking statically, then these callbacks should still be set. Not sure the best way to handle this...

**Comment by bellgrim** [comment]
CRYPTO_set_locking_callback was removed (no-op macro) in OpenSSL 1.1.0. So we should add a version-ifdef to make this more clear.

We could also check CRYPTO_get_locking_callback(). If NULL, then we set our own callback.

**Comment by bellgrim** [comment]
Fixed in #295
