### ISSUE TITLE
Distributed Setup?

### ISSUE THREAD

**Issue by Freeaqingme** [opendnssec/SoftHSMv2#217]
I'm looking to use SoftHSM to use with DKIM. However, I do not want to introduce a SPOF, and so I'd like to set up SoftHSM in a distributed or clustered fashion.

Is there anything I'm missing, or is there no way to run SoftHSMv2 in cluster?

**Comment by rijswijk** [comment]
Hi Dolf,

Dolf Schimmel wrote:
> I'm looking to use SoftHSM to use with DKIM. However, I do not want to
> introduce a SPOF, and so I'd like to set up SoftHSM in a distributed or
> clustered fashion.
> 
> Is there anything I'm missing, or is there no way to run SoftHSMv2 in
> cluster?

SoftHSMv2 has no provisions to run in a master/master type of clustering
setup, but in principle, you should be able to replicate the files
created by SoftHSMv2 to a separate host using something like rsync. If
you don't create keys very often, but mostly sign using keys in the
token, this will probably be sufficient replication.

Best regards,

Roland van Rijswijk

**Comment by Freeaqingme** [comment]
Tnx!
