### ISSUE TITLE
Support for CKM_DES3_CMAC and CKM_AES_CMAC

### ISSUE THREAD

**Issue by nouaman1** [opendnssec/SoftHSMv2#220]
I would like to use the mechanisms CKM_DES3_MAC and CKM_AES_CMAC. Now SoftHSMv2 doesn’t support this Mechanisms.

**Comment by bellgrim** [comment]
Changed from CKM_DES3_MAC to CKM_DES3_CMAC. We will not implement CBC-MAC, reason:
* Botan has deprecated CBC-MAC.
* OpenSSL do not have functions similar to CBCMAC_Init, so we would need to make a implementation using the basic EVP Encrypt functions.

**Comment by bellgrim** [comment]
Fixed in #346
