### ISSUE TITLE
Change User PIN by SO

### ISSUE THREAD

**Issue by Ovomaltine85** [opendnssec/SoftHSMv2#224]
Hi,

what is the way to change the user PIN (eg. when the user forgot it) by using the SO PIN?

I read in the internet that it can be achieved due to use this command:
pkcs11-tool --module /usr/local/bin/lib/softhsm/libsofthsm2.so --login --login-type so --so-pin 3537363231383830 --change-pin --new-pin 0123456789012345

but this only changes the PIN for the SO. This not what I want.

Does softhsm2-util provide something for this issue?

Thank you

**Comment by bellgrim** [comment]
I am guessing that --change-pin for pkcs11-tool is calling C_SetPIN(). This function can only change the PIN for the current user. C_InitPIN() will let the SO set the normal user's PIN. Guessing again that --init-pin should be the appropriate flag when using pkcs11-tool.
