### ISSUE TITLE
Support alternate configuration loaders

### ISSUE THREAD

**Issue by matthauck** [opendnssec/SoftHSMv2#227]
I'm trying to write some unit tests in a library that is using softhsm and I am finding it very difficult to guarantee a clean configuration state in between tests using the environment variable configuration method (SOFTHSM2_CONF). This is difficult in particular on account of softhsm linking against the MSVC runtime dynamically (see #226). 

I'd like to expose a function in softhsm that supplies an alternate `ConfigLoader` that `C_Initialize` could use in place of `SimpleConfigLoader`. Does this sound like an idea that softhsm would be willing to take in upstream?

**Comment by jariq** [comment]
I don't understand what exactly is difficult with the environment variable approach. Could you please provide more details?

**Comment by jariq** [comment]
It is rather a blind shot but could you please check whether [this patch](https://github.com/jariq/SoftHSMv2/commit/52e7af281fda250c30ad31fe551adfe67fac248e) solves your problem?

**Comment by matthauck** [comment]
Sorry -- missed the updates here. I was thinking something more like this: https://github.com/matthauck/SoftHSMv2/commit/46aca4378f7b4675a700c119b712abcd4ed78da0. Not sure if that kind of thing may be interesting. Not sure the right way to expose it as an interface... 

We ended up working around it by setting the SOFTHSM2_CONF environment variable from the build system instead of from inside the test executable.

**Comment by jariq** [comment]
I understand suggested approach with custom configuration loader however I am more interested in finding out why environment variable approach did not suit you.  Could you please describe what issues you were having with the environment variable?

**Comment by matthauck** [comment]
I was trying to write a test suite that would dynamically set `SOFTHSM2_CONF` environment variable before each test so that each test had a fresh softhsm configuration. That did not work because whatever the SOFTHSM2_CONF environment variable was at _test executable startup time_ was cached and not modifiable later on. I believe this is because the softhsm2.dll is compiled with `/MD` and links against the runtime dynamically, whereas our test executables are compiled with `/MT` and link the runtime statically. I believe this leads to softhsm having a different view into the environment. 

Workaround: Set SOFTHSM2_CONF once from the build system to a fixed location, and then before each test just rewrite the configuration to point to a new/fresh tokens directory.

Does that make sense?

**Comment by jariq** [comment]
Yes it makes perfect sense. I have encountered similar strange issues with environment variables not being read properly (or rather cached) in [pkcs11-logger project](https://github.com/Pkcs11Interop/pkcs11-logger) and fixed them by using `GetEnvironmentVariable()` function instead of `getenv()` function. [My previously mentioned patch](https://github.com/jariq/SoftHSMv2/commit/52e7af281fda250c30ad31fe551adfe67fac248e) does exactly that and I believe it should resolve your issues without the need for custom configuration loader. I will surely open separate pull request for that patch but I would also be grateful if you could confirm it resolves your issues.

**Comment by matthauck** [comment]
Sorry, haven't gotten around to testing this fixes the old setup yet. Will try to carve out some time soon to do that.

**Comment by matthauck** [comment]
Commented on the PR, but might as well say it here too -- the proposed patch did indeed solve the issue I was having.

**Comment by pkalapat** [comment]
I'm interested in this usecase as well. Looks like the  path shared by @jariq is specific to windows. Does this also apply to linux deployments?

**Comment by rijswijk** [comment]
AFAIK, the names of the environment variables are the same on all operating systems.

pkalapat wrote:
