### ISSUE TITLE
Support for Multiple Sessions with single login

### ISSUE THREAD

**Issue by anitgandhi** [opendnssec/SoftHSMv2#228]
Is it currently possible to login to multiple concurrent sessions to a certain slot with a single PIN?
As of right now, if this is attempted, I get a `CKR_USER_ALREADY_LOGGED_IN` error.

For example, AWS CloudHSM allows multiple concurrent connections. Is it possible to add this functionality or was it disabled on purpose?

Thanks!

**Comment by bellgrim** [comment]
Yes, you can. Just use CKR_USER_ALREADY_LOGGED_IN as a positive return value and continue your execution.

You could also use C_GetSessionInfo() to check if your are in the state CKS_RW_USER_FUNCTIONS or CKS_RO_USER_FUNCTIONS. Then you know if need to do C_Login().
