### ISSUE TITLE
Support CKM_AES_CBC_PAD

### ISSUE THREAD

**Issue by wolvz** [opendnssec/SoftHSMv2#229]
I'm using SoftHSM to test a key management application, and I'm having a problem with key wrapping operation. The application is written in java and IAIK PKCS11 library is used to interface with the module.

After inspecting the application's source code, I was able to determine that the mechanism being used in key wrapping operation is CKM_AES_CBC_PAD.

I checked SoftHSM supports this mechanism using list-mechanisms command and checking pkcs11.h file, where CKM_AES_CBC_PAD identifier is defined as 0x1085, which matches 4229 in decimal, used by the java application to identify the mechanism.

Although the mechanism seems to be supported, the application throws CKR_MECHANISM_INVALID exception.

Does anyone have a clue on why this error occurs? Maybe I'm missing some detail or configuration...
I'm using CentOS7 and installed SoftHSMv2 through the github repository.

**Comment by bellgrim** [comment]
That is correct. CKM_AES_CBC_PAD is an invalid mechanism for wrapping in SoftHSM.

Please use CKM_AES_KEY_WRAP, CKM_AES_KEY_WRAP_PAD, CKM_RSA_PKCS, or CKM_RSA_PKCS_OAEP.

**Comment by wolvz** [comment]
@bellgrim can you please give me a short reference or explanation on why SoftHSM doesn't support key wrapping with AES CBC PAD? According to PKCS#11, RSA private keys should be wrapped in CBC mode with PKCS padding [[reference](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/errata01/os/pkcs11-curr-v2.40-errata01-os-complete.html#_Toc441850478)].

**Comment by bellgrim** [comment]
Because CKM_AES_CBC_PAD has not been implemented for the wrapping functions.

When you list the mechanisms, you should also check the flags if CKF_WRAP and CKF_UNWRAP has been set to know if the mechanism support wrapping.

Would like me to re-open this and change it to a feature request?

**Comment by wolvz** [comment]
No, it's not needed @bellgrim, thanks!
I was just asking because I wanted to know if there were any security concerns about CKM_AES_CBC_PAD.
I know that AES_KEY_WRAP, for instance, implicitly checks the integrity of the wrapped material. On the other hand, from what I know of CBC_PAD, it does not provide integrity checks. Actually I don't really understand why PKCS#11 recommends it.
That being said, I assumed you decided to not implement it because it doesn't provide integrity of wrapped keys.

**Comment by bellgrim** [comment]
Sorry, do not have the history behind the wrapping code. Maybe @fxdupont got some more info?

**Comment by fxdupont** [comment]
Key wrapping is a sensitive topic in cryptography so I chose to implement only mechanisms explicitly designed for this task. BTW as soon as you have something which can cover your need there is not reason to not use it. Of course you may think you need another so post a feature request... in particular if the requested mechanism is better/safer (unfortunately not the case for CKM_AES_CBC_PAD vs AES_KEY_WRAP_PAD).

**Comment by gustavokretzer88** [comment]
I need to import a generated key somewhere else for softhsm.
The strategy we use in another hsm is to generate a session key, then encrypt the key we want to import into hsm, and perform an unwrap.
We use to encrypt the key and perform the unwrap CKM_AES_CBC_PAD.
However softhsm does not implement this mechanism, or some other that it can use use with both C_Encrypt and C_UnwrapKey.
Would there be another strategy to perform key import, or would we have to implement this mechanism in C_UnwrapKey?

**Comment by lingxiankong** [comment]
please can we support CKM_AES_CBC_PAD for wrapping and unwrapping?

**Comment by bellgrim** [comment]
Opening this issue again as a feature request.

**Comment by bellgrim** [comment]
Closing this again since I see that you have opened another one.
