### ISSUE TITLE
Add windows continuous integration build

### ISSUE THREAD

**Issue by matthauck** [opendnssec/SoftHSMv2#237]
Verifying the fix for #236, I noticed that it did not build on windows without modifying the `util` project in visual studio to link against `crypt32.lib`. Supporting windows is important for us, and it will be hard to enforce that it continues to work on windows moving forward unless the build / tests are run there frequently. Is there any way to hook up a windows node to build on your jenkins instance?

**Comment by matthauck** [comment]
fwiw, the application I'm working on builds softhsm on each build and wasn't too hard to setup. We do something more or less like this on windows:

```
cd win32
python Configure.py disable-debug verbose without-cppunit with-crypto-backend=openssl with-openssl=<path-to-openssl> enable-64bit
msbuild /m /p:Configuration=Release /p:Platform=x64 softhhsm2.sln
```

You would also need an openssl build of course. You'd also probably want to build with cppunit instead of without it, but even just making sure it compiles on windows for each PR would be a step forward I think.

**Comment by bellgrim** [comment]
Yes, that would be really good.

@halderen There is some work going on with Jenkins. Do we have any plans on adding a Windows machine?

**Comment by jariq** [comment]
BTW we currently working with @peponeska on an automated SoftHSM2 build with [AppVeyor](https://www.appveyor.com/) service. It is free for open source projects, works quite well and is used for example by OpenSC project. We plan to open PR once it is finished and tested.

**Comment by bellgrim** [comment]
Thanks for creating the AppVeyor config and build scripts.

**Comment by peponeska** [comment]
Thanks for merging it.
