### ISSUE TITLE
Unknown mechanism 0x2109

### ISSUE THREAD

**Issue by lse-fabian** [opendnssec/SoftHSMv2#243]
Hi,

i am using PyCKS11 to fetch the list of mechanisms made available by SoftHSM, however apparently SoftHSM has a mechanism with id 0x2109, that is [not present in official standard](https://bitbucket.org/PyKCS11/pykcs11/issues/25/getmechanismlist-fails-for-opendnssec#comment-30812425).

Is this a custom extension of the standard? Which one is it and how should it be treated?

**Comment by jariq** [comment]
When you take a look at [source code](https://github.com/opendnssec/SoftHSMv2/blob/2.1.0/src/lib/cryptoki_compat/pkcs11.h#L857) you will find it is `CKM_AES_KEY_WRAP`. It is defined in stable [PKCS#11 v2.40](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.40/headers/pkcs11t.h#L970) and was present also in draft of [PKCS#11 v2.30](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.30_DRAFT/headers/pkcs11t.h#L891) but with a different value.

**Comment by bellgrim** [comment]
That is correct. It was added from the newer specification. Just so that we could have support for key wrapping using AES. The full move to v2.40 will be done in #130

**Comment by lse-fabian** [comment]
thanks for your help :+1:
