### ISSUE TITLE
sizeof(CK_KEY_DERIVATION_STRING_DATA) ?

### ISSUE THREAD

**Issue by igalco** [opendnssec/SoftHSMv2#245]
Hello,

I fought all day with DES & 3DES derivation and i found out what appears to be an error in the code :

src/lib/SoftHSM.cpp:8373 pMechanism->ulParameterLen == sizeof(CK_KEY_DERIVATION_STRING_DATA))
src/lib/SoftHSM.cpp:9414 pMechanism->ulParameterLen == sizeof(CK_KEY_DERIVATION_STRING_DATA))

Here you are comparing pMechanism->ulParameterLen witch is the size of the input buffer sent to be encrypted and sizeof(CK_KEY_DERIVATION_STRING_DATA) = sizeof(struct ck_key_derivation_string_data) witch contains a pointer and a long.

i fixed my issue by replacing the lines with :
|-           pMechanism->ulParameterLen == sizeof(CK_KEY_DERIVATION_STRING_DATA))
|+           (pMechanism->ulParameterLen == 8 || pMechanism->ulParameterLen == 16))

But this should be fixed according the the mechanisms too ... 

i let you specialist find the better solution.

Thanks for your amazing work

**Comment by jariq** [comment]
Your report is missing mechanisms (CKM... defines) which you were using. Could you please add those?

**Comment by igalco** [comment]
The issue occures when derivating using DES3_ECB_ENCRYPT_DATA

Exemple : 
algorithm.name : DES3_ECB_ENCRYPT_DATA
algorithm.params : 0x1234123412341234
template.class : SECRET_KEY
template.keyType : DES2
template.encrypt : true

C_DeriveKey answers : CKR_MECHANISM_PARAM_INVALID

Is this enough for you to work with ?

**Comment by jariq** [comment]
[PKCS#11 specification v2.20](https://github.com/Pkcs11Interop/PKCS11-SPECS/raw/master/v2.20/pkcs-11v2-20.pdf) states in chapter 12.14.2 that `CKM_DES_ECB_ENCRYPT_DATA` mechanism should be used with `CK_KEY_DERIVATION_STRING_DATA` structure as a parameter. IMO SoftHSM code is correct and you need to adjust your code to look like this:

```
CK_KEY_DERIVATION_STRING_DATA ck_key_derivation_string_data;
ck_key_derivation_string_data.Data = new byte[] { 0x12, 0x34, 0x12, 0x34, 0x12, 0x34, 0x12, 0x34 };
ck_key_derivation_string_data.Len = 8;

CK_MECHANISM ck_mechanism;
ck_mechanism.Mechanism = DES3_ECB_ENCRYPT_DATA;
ck_mechanism.Parameter = &ck_key_derivation_string_data;
ck_mechanism.ParameterLen = sizeof(CK_KEY_DERIVATION_STRING_DATA);
```

**Comment by bellgrim** [comment]
The parameter given to the mechanism is not in the correct format. You should follow the example given by @jariq
