### ISSUE TITLE
Move AppVeyor to an organizational account

### ISSUE THREAD

**Issue by bellgrim** [opendnssec/SoftHSMv2#247]
AppVeyor is currently linked with by personal account.

We need to set up an organizational account, link it with GitHub, and add a team to it.

https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization

**Comment by bellgrim** [comment]
Also remember to:

* Update [README.md](https://github.com/opendnssec/SoftHSMv2/blob/develop/README.md) with a new URL to the build logo
* Update [APPVEYOR-NOTES.md](https://github.com/opendnssec/SoftHSMv2/blob/develop/testing/appveyor/APPVEYOR-NOTES.MD) if there there are any changes

**Comment by bellgrim** [comment]
The current configuration of AppVeyor does not build any pull requests. It only build the development branch once you merge the pull request. Perhaps I have missed some configuration?

**Comment by peponeska** [comment]
@bellgrim  You need to [enable it in webhook settings](http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests) on github.

Did not try it myself but maybe it will help.

**Comment by bellgrim** [comment]
Thanks for the hint, but I only have member privileges on GitHub and cannot make those changes. So will have to wait for Jakob.

**Comment by jariq** [comment]
@bellgrim @jschlyter any chance to get this working before 2.3.0 release?

**Comment by jschlyter** [comment]
Sorry, I've missed this. I've made @bellgrim admin for the repos so he can fix it.

**Comment by bellgrim** [comment]
Thank you @jschlyter 

AppVeyor is now running automatically for opendnssec/SoftHSMv2
