### ISSUE TITLE
2.2.0 RC1 tar.gz bundle has no configure script

### ISSUE THREAD

**Issue by matthauck** [opendnssec/SoftHSMv2#263]
Looks like the 2.2.0 RC1 bundle has no `./configure` script, and requires us to have autotools installed and run `autogen.sh` to generate it. I assume this was not intentional.

**Comment by bellgrim** [comment]
I can find one in: https://dist.opendnssec.org/source/testing/softhsm-2.2.0rc1.tar.gz

**Comment by bellgrim** [comment]
```
user@user:~/softhsm-2.2.0rc1$ ls -al
total 1204
drwxr-xr-x  6 user user   4096 nov 11 20:58 .
drwxr-xr-x 17 user user   4096 nov 11 20:57 ..
-rw-r--r--  1 user user  43057 nov  1 11:02 aclocal.m4
drwxr-xr-x  2 user user   4096 nov  1 11:06 aes_wrap_key_with_pad
-rwxr-xr-x  1 user user   7333 nov  1 11:02 compile
-rwxr-xr-x  1 user user  42938 nov  1 11:02 config.guess
-rw-r--r--  1 user user   3657 nov  1 11:02 config.h.in
-rwxr-xr-x  1 user user  35987 nov  1 11:02 config.sub
-rwxr-xr-x  1 user user 623043 nov  1 11:02 configure
-rw-r--r--  1 user user   5789 nov  1 11:00 configure.ac
-rwxr-xr-x  1 user user  23566 nov  1 11:02 depcomp
-rw-r--r--  1 user user   1664 nov  1 10:57 FIPS-NOTES.md
-rwxr-xr-x  1 user user  14675 nov  1 11:02 install-sh
-rw-r--r--  1 user user   1389 nov  1 10:57 LICENSE
-rw-r--r--  1 user user 283477 nov  1 11:02 ltmain.sh
drwxr-xr-x  2 user user   4096 nov  1 11:06 m4
-rw-r--r--  1 user user   2787 nov  1 11:00 Makefile.am
-rw-r--r--  1 user user  32160 nov  1 11:02 Makefile.in
-rwxr-xr-x  1 user user   6872 nov  1 11:02 missing
-rw-r--r--  1 user user   8117 nov  1 11:00 NEWS
-rw-r--r--  1 user user   6020 nov  1 11:00 OSX-NOTES.md
-rw-r--r--  1 user user   4589 nov  1 11:00 README.md
-rw-r--r--  1 user user    145 nov  1 11:00 softhsm2.module.in
drwxr-xr-x  4 user user   4096 nov  1 11:06 src
-rwxr-xr-x  1 user user   4640 nov  1 11:02 test-driver
drwxr-xr-x 14 user user   4096 nov  1 11:06 win32
-rw-r--r--  1 user user  13088 nov  1 11:00 WIN32-NOTES.md
```

**Comment by matthauck** [comment]
Hmm. We clearly have different versions then. 

```
$ shasum softhsm-2.2.0-rc1.tar.gz && rm -fr SoftHSMv2-2.2.0rc1 && tar xf softhsm-2.2.0-rc1.tar.gz  && ls -l SoftHSMv2-2.2.0rc1
081ec8bea7940e0a11b7f26be865e6c65d6f349e  softhsm-2.2.0-rc1.tar.gz
total 92
drwxrwxr-x  2 user  4096 Nov  1 03:00 aes_wrap_key_with_pad
-rw-rw-r--  1 user    40 Nov  1 03:00 autogen.sh
-rw-rw-r--  1 user  5789 Nov  1 03:00 configure.ac
-rw-rw-r--  1 user  1664 Nov  1 03:00 FIPS-NOTES.md
-rw-rw-r--  1 user  1389 Nov  1 03:00 LICENSE
drwxrwxr-x  2 user  4096 Nov  1 03:00 m4
-rw-rw-r--  1 user  2787 Nov  1 03:00 Makefile.am
-rw-rw-r--  1 user  8117 Nov  1 03:00 NEWS
-rw-rw-r--  1 user  6020 Nov  1 03:00 OSX-NOTES.md
-rw-rw-r--  1 user   390 Nov  1 03:00 prepdist.sh
-rw-rw-r--  1 user  4589 Nov  1 03:00 README.md
-rw-rw-r--  1 user   145 Nov  1 03:00 softhsm2.module.in
drwxrwxr-x  4 user  4096 Nov  1 03:00 src
drwxrwxr-x  4 user  4096 Nov  1 03:00 testing
drwxrwxr-x 14 user  4096 Nov  1 03:00 win32
-rw-rw-r--  1 user 13088 Nov  1 03:00 WIN32-NOTES.md
```

**Comment by matthauck** [comment]
Getting the same thing with RC2.

```
$ shasum 2.2.0rc2.tar.gz && rm -fr SoftHSMv2-2.2.0rc2 && tar xf 2.2.0rc2.tar.gz  && ls -l SoftHSMv2-2.2.0rc2
85abc0b0ca62d1f714cf4778cc6b12e9ce544e01  2.2.0rc2.tar.gz
total 96
drwxrwxr-x  2 user  4096 Nov 14 01:50 aes_wrap_key_with_pad
-rw-rw-r--  1 user    40 Nov 14 01:50 autogen.sh
-rw-rw-r--  1 user  5789 Nov 14 01:50 configure.ac
-rw-rw-r--  1 user  1664 Nov 14 01:50 FIPS-NOTES.md
-rw-rw-r--  1 user  1389 Nov 14 01:50 LICENSE
drwxrwxr-x  2 user  4096 Nov 14 01:50 m4
-rw-rw-r--  1 user  2787 Nov 14 01:50 Makefile.am
-rw-rw-r--  1 user  8308 Nov 14 01:50 NEWS
-rw-rw-r--  1 user  6020 Nov 14 01:50 OSX-NOTES.md
-rw-rw-r--  1 user   390 Nov 14 01:50 prepdist.sh
-rw-rw-r--  1 user  4589 Nov 14 01:50 README.md
-rw-rw-r--  1 user   145 Nov 14 01:50 softhsm2.module.in
drwxrwxr-x  4 user  4096 Nov 14 01:50 src
drwxrwxr-x  4 user  4096 Nov 14 01:50 testing
drwxrwxr-x 14 user  4096 Nov 14 01:50 win32
-rw-rw-r--  1 user 13088 Nov 14 01:50 WIN32-NOTES.md
```

**Comment by bellgrim** [comment]
I see, you are downloading the file from GitHub. It is just an archive of the tagged release.

The official download is here: https://dist.opendnssec.org/source/testing/softhsm-2.2.0rc2.tar.gz

**Comment by matthauck** [comment]
Ah ok. That's kinda confusing. Would be cool for github releases to be the same thing as the official release.

**Comment by bellgrim** [comment]
@halderen is it possible to make the GitHub release tarball to match the one on the OpenDNSSEC website?

**Comment by halderen** [comment]
Not really.  A distribution is made with automake using "make dist".  Although the configure script is already present, the make dist does collect only the files from the distribution into the package and also makes sure some other files are created.  While what you are downloading from github isn't the release.  Just a branch or a tag.  These aren't static and contain all files, including testing, git meta files etcetera.  This might actually mess up your installation.  It is just unfortunate that Github allows you to download a tarball (and not, like what would be the git-way allow you to download an archive.  The way Github does it makes people think they are downloading something special, while their just downloading a particular commit.

Please note that a "make dist" really isn't the same as the commit in Github.

**Comment by matthauck** [comment]
Roger.

**Comment by matthauck** [comment]
Maybe just don't put up github releases then? If all it is is a tag, then you really don't need to put up a tarball, people can just clone and checkout that tag. Or, you can just use github's API to grab a tag's tarball: e.g. https://github.com/opendnssec/SoftHSMv2/archive/master.tar.gz

**Comment by matthauck** [comment]
And I don't believe all tags are made to be releases by github. This is not the case for other projects of mine. Creating releases is a manual process I'm pretty sure: https://help.github.com/articles/creating-releases/

**Comment by halderen** [comment]
I did not create a release on github, I don't believe it is done by Rickard either.  I believe (but I've not looked into it) it is triggered by merging into master and/or setting a tag.  Since these are the only visible changes to github (all actions are undertaken in git itself).  Now merging into master isn't particular tied to a release either.  But reading about the link above, I do think that github makes a 1:1 correspondence with git tags as releases, based on the sentence "Versions are based on Git tags.".

In all, the github model doesn't work with having a "make dist".  There are some pretty good reasons to keep a "make dist" as you don't particular want to ship the testing stuff in your release that is picked up by package maintainers.  In the Java world this is more common, a whole lot less to in the C/C++ and other system languages.
Since releases are signed externally, this will always conflict with Github.
