### ISSUE TITLE
Derive shared secret with ECC

### ISSUE THREAD

**Issue by Ovomaltine85** [opendnssec/SoftHSMv2#265]
Hi,

I stored a private and public ECC key to the hsm Slot. If I check the supported mechanisms with pkcs11-tool the mechanism for CKM_ECDH1 is supported. 
But if I use the pkcs11-tool with the --derive option then it is stated that the mechanism is not supported. How can the public and private ECC keys be used to derive a shared secret out of the hsm?

regards!

**Comment by Ovomaltine85** [comment]
I also put this issue to the forum of OpenSC because I thought it could also be a pkcs11-tool issue.

This is the reply of my issue: https://github.com/OpenSC/OpenSC/issues/898

Maybe you can help me, why the operation throws an CKR_TEMPLATE_INCOMPLETE error?

Thank you

**Comment by dengert** [comment]
As also stated in https://github.com/OpenSC/OpenSC/issues/898#issuecomment-258619835
it could an issue with the CKA_VALUE_LEN which is optional. 

6312 // CKA_VALUE_LEN must be specified
6313 if (keyLen == 0)
6314 {
6315 INFO_MSG("Missing CKA_VALUE_LEN in pTemplate");
6316 return CKR_TEMPLATE_INCOMPLETE;
6317 }

PKCS#11 v2.40 (pkcs110curr-v2.40-cs01.pdf) has:

2.3.9 Elliptic curve Diffie-Hellman key derivation
"This mechanism derives a secret value, and truncates the result according to the CKA_KEY_TYPE
attribute of the template and, if it has one and the key type supports it, the CKA_VALUE_LEN attribute of
the template. (The truncation removes bytes from the leading end of the secret value.) The mechanism
contributes the result as the CKA_VALUE attribute of the new key; other attributes required by the key
type must be specified in the template."

This implies CKA_VALUE_LEN is optional.

**Comment by Ovomaltine85** [comment]
Hi!
I introduced manually the changes you proposed to SoftHSM.cpp and OSSLUtil.cpp and built the application again.
If I perform now the following command:
`pkcs11-tool --module /usr/local/lib/softhsm/libsofthsm2.so --slot 1 -l -p 1234 --id 1234 --derive --input-file pubkey.der -m ECDH1-DERIVE --output-file shared`
I get the following error:
`Using derive algorithm 0x00001050 ECDH1-DERIVE
error: PKCS11 function C_DeriveKey failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.`
Thank you for having a look!

**Comment by dengert** [comment]
I am still looking at the pkcs11-tool side. It still needs to add in pkcs11-tool.c in derive_ec_key
in the template:
` {CKA_SENSITIVE, &false, sizeof(false)},`
` {CKA_EXTRACTABLE, &true, sizeof(true)},`
This will allow the key to be extracted. You can try this if you want. 

I am in the process of adding even more code to pkcs11-tool.c to get around the softhsm2 problems, as I have not gotten any feed back on  #266, and don't expect them to fix it the near future. 

In addition I am trying to clean up the derive code in pkcs11-tool.c to allow DES2, DES3, AES and the generic derived key to be output. 

This is more complicated then one might expect. PKCS#11 implementation have short time session keys and long term keys that reside on the token or only in software. This is important when using a real hardware that that may be able to derive a key but not store it on the token, such as a smart card where the user can not modify it. pkcs11-tool.c currently only derives session keys. What softhsm does with 
with the   `{CKA_TOKEN, &false, sizeof(false)}, /* session only object */` is not clear. 

To make sure libsofthsm2.so  is finding the correct libraries run:
`ldd /usr/local/lib/softhsm/libsofthsm2.so`
and look at what libraries it is including. 

So I am not done yet with your OpenSC issue https://github.com/OpenSC/OpenSC/issues/898

**Comment by Ovomaltine85** [comment]
Thanks for your effort.

I did the adjustments to pkcs11-tool.c concerning the key template but it had no effect, still the same error message of:
`PKCS11 function C_DeriveKey failed: rv = CKR_GENERAL_ERROR (0x5)`

I also checked `ldd /usr/local/lib/softhsm/libsofthsm2.so`:
`	linux-vdso.so.1 (0x00007ffc2afbb000)
	libbotan-1.10.so.1 => /usr/local/lib/libbotan-1.10.so.1 (0x00007f1a8d8e7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1a8d6e3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1a8d3d8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1a8d0d7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1a8cd2c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1a8cb16000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f1a8c893000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1a8c676000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1a8c46e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1a8e0aa000)`

I'll wait until you're done with this issue. Thank you!

**Comment by dengert** [comment]
Softhsm can use either OpenSSL or Botan my change included src/lib/crypto/OSSLUtil.cpp which is for OpenSSL only. 
Commit https://github.com/opendnssec/SoftHSMv2/pull/266/commits/71cdd9ea61001649eb188df1ed0d8c6ff444c76a says: "Only OSSLUtil was changed. Other places in the code may need to be fixed."

I would hope SoftHSM developers would have a look at the Botan version of this routine. I did not look at it and there may be a better way to detect if the public key is passed in as ASN1 octet string or RAW. 
They both start with 0x04 which could lead to the wrong choice. Using the field size in the test could resolve this issue.  

Can you try and compile softhsm using OpenSSL 1.0.2?

**Comment by Ovomaltine85** [comment]
I built now softhsm 2.2.0rc1 together with OpenSSL 1.0.2j and get the following error:
`Using derive algorithm 0x00001050 ECDH1-DERIVE
error: PKCS11 function C_DeriveKey failed: rv = CKR_TEMPLATE_INCOMPLETE (0xd0)
Aborting.`

**Comment by bellgrim** [comment]
Yes, agree that CKA_VALUE_LEN should be optional.

**Comment by bellgrim** [comment]
Fixed in #288
