### ISSUE TITLE
Support for Botan 2.0

### ISSUE THREAD

**Issue by pgnd** [opendnssec/SoftHSMv2#276]
building opendnssec 2 prereqs on linux64

prereq botan v1.11.34 is installed

    /usr/local/botan/bin/botan version --full
        Botan 1.11.34 (released, dated 20161128, revision git:b816a3652c1359028f59d64a2f742564547ab782, distribution unspecified)

building softhsm v2.2.0

    export LDFLAGS="-L/usr/local/ssl/lib64 -Wl,-rpath,/usr/local/ssl/lib64 -lssl -lcrypto -L/usr/local/botan/lib64"
    export CPPFLAGS+=" -I/usr/local/ssl/include -I/usr/local/botan/include"

    make distclean
    ./configure \
    --prefix=/usr/local/softHSM \
    --libdir=/usr/local/softHSM/lib64 \
    --localstatedir=/var/lib \
    --enable-shared --disable-static \
    --enable-64bit \
    --with-crypto-backend=botan \
    --with-botan=/usr/local/botan \
    --with-openssl=/usr/local/ssl \
    --enable-ecc \
    --disable-gost \
    --with-objectstore-backend-db \
    --with-sqlite3=/usr \
    --with-gnu-ld
building opendnssec 2 prereqs on linux64

prereq botan v1.11.34 is installed

    /usr/local/botan/bin/botan version --full
         Botan 1.11.34 (released, dated 20161128, revision git:b816a3652c1359028f59d64a2f742564547ab782, distribution unspecified)

building softhsm v2.2.0

    export LDFLAGS="-L/usr/local/ssl/lib64 -Wl,-rpath,/usr/local/ssl/lib64 -lssl -lcrypto -L/usr/local/botan/lib64"
    export CPPFLAGS+=" -I/usr/local/ssl/include -I/usr/local/botan/include"

    make distclean
    ./configure \
    --prefix=/usr/local/softHSM \
    --libdir=/usr/local/softHSM/lib64 \
    --localstatedir=/var/lib \
    --enable-shared --disable-static \
    --enable-64bit \
    --with-crypto-backend=botan \
    --with-botan=/usr/local/botan \
    --with-openssl=/usr/local/ssl \
    --enable-ecc \
    --disable-gost \
    --with-objectstore-backend-db \
    --with-sqlite3=/usr \
    --with-gnu-ld

    make V=1
        ...
        libtool: compile:  /usr/bin/g++-6 -DHAVE_CONFIG_H -I. -I../../.. -I./../common -I./../cryptoki_compat -I./../data_mgr -I./.. -I/usr/local/botan/include/botan-1.11 -O3 -Wall -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=native -mtune=native -D_FORTIFY_SOURCE=2 -I/usr/local/include -I/usr/local/ssl/include -I/usr/local/include -I/usr/local/ssl/include -I/usr/local/include -I/usr/local/ssl/include -I/usr/local/botan/include -m64 -O3 -Wall -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=native -mtune=native -std=c++14 -Wall -Wextra -fvisibility=hidden -MT BotanDSAPrivateKey.lo -MD -MP -MF .deps/BotanDSAPrivateKey.Tpo -c BotanDSAPrivateKey.cpp  -fPIC -DPIC -o .libs/BotanDSAPrivateKey.o
        BotanDSAPrivateKey.cpp: In member function 'virtual bool BotanDSAPrivateKey::PKCS8Decode(const ByteString&)':
        BotanDSAPrivateKey.cpp:180:66: error: no matching function for call to 'Botan::DSA_PrivateKey::DSA_PrivateKey(Botan::AlgorithmIdentifier&, Botan::secure_vector<unsigned char>&, Botan::RandomNumberGenerator&)'
           key = new Botan::DSA_PrivateKey(alg_id, keydata, *rng->getRNG());
                                                                          ^
        In file included from BotanDSAPrivateKey.h:38:0,
                         from BotanDSAPrivateKey.cpp:35:
        /usr/local/botan/include/botan-1.11/botan/dsa.h:73:7: note: candidate: Botan::DSA_PrivateKey::DSA_PrivateKey(Botan::RandomNumberGenerator&, const Botan::DL_Group&, const Botan::BigInt&)
               DSA_PrivateKey(RandomNumberGenerator& rng,
               ^~~~~~~~~~~~~~
        /usr/local/botan/include/botan-1.11/botan/dsa.h:73:7: note:   no known conversion for argument 1 from 'Botan::AlgorithmIdentifier' to 'Botan::RandomNumberGenerator&'
        /usr/local/botan/include/botan-1.11/botan/dsa.h:64:7: note: candidate: Botan::DSA_PrivateKey::DSA_PrivateKey(const Botan::AlgorithmIdentifier&, Botan::secure_vector<unsigned char>&)
               DSA_PrivateKey(const AlgorithmIdentifier& alg_id,
               ^~~~~~~~~~~~~~
        /usr/local/botan/include/botan-1.11/botan/dsa.h:64:7: note:   candidate expects 2 arguments, 3 provided
        /usr/local/botan/include/botan-1.11/botan/dsa.h:55:17: note: candidate: Botan::DSA_PrivateKey::DSA_PrivateKey(const Botan::DSA_PrivateKey&)
         class BOTAN_DLL DSA_PrivateKey : public DSA_PublicKey,
                         ^~~~~~~~~~~~~~
        /usr/local/botan/include/botan-1.11/botan/dsa.h:55:17: note:   candidate expects 1 argument, 3 provided
        /usr/local/botan/include/botan-1.11/botan/dsa.h:55:17: note: candidate: Botan::DSA_PrivateKey::DSA_PrivateKey(Botan::DSA_PrivateKey&&)
        /usr/local/botan/include/botan-1.11/botan/dsa.h:55:17: note:   candidate expects 1 argument, 3 provided
        Makefile:721: recipe for target 'BotanDSAPrivateKey.lo' failed
        make[5]: *** [BotanDSAPrivateKey.lo] Error 1
        make[5]: Leaving directory '/usr/local/src/softhsm-2.2.0/src/lib/crypto'
        Makefile:741: recipe for target 'all-recursive' failed
        make[4]: *** [all-recursive] Error 1
        make[4]: Leaving directory '/usr/local/src/softhsm-2.2.0/src/lib/crypto'
        Makefile:610: recipe for target 'all-recursive' failed
        make[3]: *** [all-recursive] Error 1
        make[3]: Leaving directory '/usr/local/src/softhsm-2.2.0/src/lib'
        Makefile:380: recipe for target 'all-recursive' failed
        make[2]: *** [all-recursive] Error 1
        make[2]: Leaving directory '/usr/local/src/softhsm-2.2.0/src'
        Makefile:541: recipe for target 'all-recursive' failed
        make[1]: *** [all-recursive] Error 1
        make[1]: Leaving directory '/usr/local/src/softhsm-2.2.0'
        Makefile:447: recipe for target 'all' failed
        make: *** [all] Error 2

not sure where the problem is – softhsm, botan, other?

EDIT:

from Jira,

     Comment by Rickard Bellgrim [ 14/Dec/16 ]

     The problem is that Botan made some API-changes in the development branch (1.11). Have fixed and handled the API-changes up to 1.11.33, but not 1.11.34.

**Comment by pgnd** [comment]
@bellgrim 

At the OP where I reported this issue,

    https://issues.opendnssec.org/browse/SUPPORT-204

b4 mv'ing it here, it's marked

    Status: Resolved
    Resolution: Fixed

but I'm not finding the code fix here/above.

Was that 'fix' only for closing the issue THERE, and it's still to-do HERE? or have I missed a commit somewhere?

**Comment by bellgrim** [comment]
The 'fixed' was for updating the documentation on how to report the bugs on GitHub.

**Comment by pgnd** [comment]
> ... was for updating ...
ok, thx

**Comment by bellgrim** [comment]
Updating title to "Support for Botan 2.0"

**Comment by bellgrim** [comment]
Fixed in #294
