### ISSUE TITLE
C_GetMechanismInfo HMAC question

### ISSUE THREAD

**Issue by finerrecliner** [opendnssec/SoftHSMv2#280]
Hello,
I have a question regarding something I saw in C_GetMechanismInfo() in the SoftHSMv2 code. In this function, I see that the min and max key sizes are set to 0 for all of the SHA HMAC functions (see here: https://github.com/opendnssec/SoftHSMv2/blob/7fd1d77e75edfeb79add6a1a867cfbaf14516839/src/lib/SoftHSM.cpp#L857). I find this odd, because the HMAC algorithm requires a key size greater than zero to use properly. Is there a reason why the Mechanism Info key size fields are not set to 20 for CKM_SHA_1_HMAC, 28 for CKM_SHA224_HMAC, 32 for CKM_SHA256_HMAC, etc ?

**Comment by bellgrim** [comment]
From [RFC2104](https://tools.ietf.org/html/rfc2104#section-3)
>    The key for HMAC can be of any length (keys longer than B bytes are
>    first hashed using H).  However, less than L bytes is strongly
>    discouraged as it would decrease the security strength of the
>    function.  Keys longer than L bytes are acceptable but the extra
>    length would not significantly increase the function strength. (A
>    longer key may be advisable if the randomness of the key is
>    considered weak.)

PKCS#11 v2.20:
> For some mechanisms, the ulMinKeySize and ulMaxKeySize fields have meaningless values.

Our interpretation has been that we set ulMinKeySize/ulMaxKeySize to 0 if they key size is implicit to the selected algorithm. But I now think that we should set the key size explicitly (so we should check e.g. CKM_GOSTR3411_HMAC and CKM_DES3_ECB).

Although there is no key size limit for HMAC, there is a key size restriction in Botan between 0 and 512 bytes. Cannot find one for OpenSSL, after doing a quick review of the code.

Should we update to:
* ulMinKeySize = 0
* ulMaxKeySize = 512

**Comment by bellgrim** [comment]
Since sizes less than L bytes is strongly discouraged, maybe we should set a lower bound to this and check this when doing HMAC?

**Comment by bellgrim** [comment]
Fixed in #306
