### ISSUE TITLE
SoftHSM2 & SSL question

### ISSUE THREAD

**Issue by MartinvdGraaff** [opendnssec/SoftHSMv2#282]
I guess I have to use Apache web server/OpenSSL when I want to use SoftHSM2 to store the private key of an SSL certificate.

Or is this also somehow possible when using IIS as a web server? I guess not, but may be I am wrong.

Thanks in advance.

**Comment by bellgrim** [comment]
You can use SoftHSM to store certificates and private keys. The requirement is that the server/application is using PKCS#11.

But this is off-topic for SoftHSM, unless you are hitting any issues related to SoftHSM.
