### ISSUE TITLE
Exceedingly unhelpful error message in softhsm2-util

### ISSUE THREAD

**Issue by kkeane** [opendnssec/SoftHSMv2#283]
If there is a problem with softhsm2.conf, softhsm2-util will produce an error message that really tells nothing about the problem, and in fact sent me on a wild goose chase for a while:

ERROR: Could not initialize the library.

I had to search through the source code to find that "the library" seems to refer to the PKCS11 library, and dig again to find that it probably is related to an error in my softhsm2.conf.

It would be helpful if the error message included:

- That the culprit is libsofthsm2.so (preferably show the correct path)
- The nature of the problem.
- Which path the library tried to load the softhsm2.conf from
- And ideally exactly which line in the configuration file was wrong.

**Comment by bellgrim** [comment]
Yes, but as an application (softhsm2-util loads libsofthsm2.so (or any other PKCS#11 library if you use --module)) you will not get more error info from the PKCS#11 library than e.g. CKA_GENERAL_ERROR.

In the case with SoftHSM, you will find more info in syslog. This is where the library can display its output.

Could you check syslog and see if you get the desired error message?

**Comment by kkeane** [comment]
Well, this error message doesn't even indicate that the problem is with the PKCS#11 library or that the error is CKA_GENERAL_ERROR! If somebody uses multiple repositories, it wouldn't even tell you WHICH one was the problem. Incidentally, another related problem is terminology: what is called "library" in this error message is called "module" in the command line argument.

Based on the message, I actually assumed that it was a problem with dynamic linking and was chasing my tail for a while until I looked at the source code.

A more useful, and still doable, message might be "ERROR: initialization of PKCS#11 library /usr/lib/softhsm/libsofthsm2.so failed. Is your configuration file correct?" - specific enough to be helpful, yet generic enough to apply to softhsm as well as other libraries. Of course, the actual path to the library should be substituted.

I didn't see anything useful in syslog, either (and looking at the source code for libsofthsm2.so suggests that there isn't all that much logging).

BTW, the actual problem turned out to be that I had used a version 1 softhsm.conf file with version 2.2.0 - doh, but not surprising given what I am working on (compiling OpenDNSSEC from scratch on Alpine Linux to put into a docker container). I also later got the exact same message (also without helpful syslog messages) when the token directory didn't exist.

**Comment by bellgrim** [comment]
Thanks for making this more clear. We will review and update relevant code, when it comes to reading the configuration.

**Comment by cryptohat** [comment]
Just built on CentOS 7.  Passed test but softhsm2-util is reporting the library not found.  Would love to get this working but not a C++ dev so digging into code is less than helpful.  No errors or details in /var/logs/messages.  Hopefully there is a better place to look.  Please advise.

**Comment by bellgrim** [comment]
I will give this some attention next time I am working on SoftHSM.

**Comment by bellgrim** [comment]
Is it better with #304 ?

**Comment by bellgrim** [comment]
Fixed in #304

**Comment by shuchivt** [comment]
how should the following statement change if softhsm is installed on windows 10
pkcs11.load("/usr/local/lib/softhsm/libsofthsm2.so");

**Comment by bellgrim** [comment]
This is not related to the current issue, please open a new one.

**Comment by gaia** [comment]
For reference, I got this on Debian 9 (Raspian) and a simple `mkdir -p /var/lib/softhsm/tokens/` fixed it.

**Comment by avastmick** [comment]
@gaia - I can confirm that the `/var/lib/softhsm/tokens` dir is **not** created on install on Ubuntu 18.04.1. The `mkdir` fix resolves the error.

**Comment by linas** [comment]
why is this closed? This is still not fixed in Dec 2020!
