### ISSUE TITLE
Key wrapping fails using CKM_AES_KEY_WRAP

### ISSUE THREAD

**Issue by corporategoth** [opendnssec/SoftHSMv2#305]
I am wrapping an RSA private key with an AES key.

I am using CKM_AES_KEY_WRAP (my OpenSSL does not support the CKM_AES_KEY_WRAP_PAD).

I added a bunch of debug lines, and found out the:
    `if ((wrappedlen < 16) || ((wrappedlen % 8) != 0))`

check is failing in SoftHSM::WrapKeySym (SoftHSM.cpp, line 5334 right now).

This is because using OpenSSL for the RSA private key, it does a PKCS8 encode of the private key and takes the DER output, which ends up with a variable length text blob.

This means the wrappedlen is not evenly divisible by 8, and as such this check fails 7 out of 8 times.

You should be padding this DER output value yourself, as the output here is created deep within code I won't ever be able to manipulate directly from my client code, and failing 7 out of 8 times when trying to wrap a key is not a great experience.  ie. put in code that says 'if it's the AES_KEY_WRAP and not AES_KEY_WRAP_PAD, pad to next 8 byte boundary with nulls.

**Comment by bellgrim** [comment]
Thank you for reporting this. Will #307 fix your issue?

**Comment by corporategoth** [comment]
I will test it out and let you know.  Thanks for the rapid response! :)

**Comment by corporategoth** [comment]
I tried the code, and sure enough, my wrapping / unwrapping test works now every time.

**Comment by bellgrim** [comment]
Thanks, have now merged the code.
