### ISSUE TITLE
Cannot build SoftHSMv2 windows 10 vs 2015

### ISSUE THREAD

**Issue by hinhmd** [opendnssec/SoftHSMv2#308]
Hi, here my build command:
`python Configure.py disable-debug disable-gost with-crypto-backend=openssl with-openssl=C:\build\bin\openssl-1.0.2d-x86\ with-cppunit=C:\build\bin\cppunit-1.13.2-x86\`

And input:
```
testrfc3394.c
testrfc5649.c
testrfc5649.obj : error LNK2019: unresolved external symbol _EVP_aes_128_wrap_pad referenced in function _main
testrfc5649.exe : fatal error LNK1120: 1 unresolved externals
Configured.
```

What is wrong here or I am missing something ?

**Comment by jariq** [comment]
Those two lines that look like an error...

```
testrfc5649.obj : error LNK2019: unresolved external symbol _EVP_aes_128_wrap_pad referenced in function _main
testrfc5649.exe : fatal error LNK1120: 1 unresolved externals
```

...are actually not an error. It is just an output of configuration subroutine that was detecting whether your OpenSSL supports key wrapping with AES algorithm. The important thing is that you got the last line...

`Configured.`

...which confirms that configuration process was successful and you can continue with building.

**Comment by hinhmd** [comment]
yeah, I got it. Thanks you
