### ISSUE TITLE
Threading and RSA context

### ISSUE THREAD

**Issue by dansackinger** [opendnssec/SoftHSMv2#311]
I'm working on a project that services incoming requests on multiple threads.

The project uses openssl (Using OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013) and utilizes the PKCS11 interface to connect with SoftHSM.

For each request my app receives, the following calls are being done:
```
ENGINE_init(engine_handle); // Increment the lock count on the engine

EVP_PKEY * key = ENGINE_load_private_key(engine_handle, 
   "pkcs11:token=xyz;pin-value=pdq", NULL, NULL);
RSA*rsa = EVP_PKEY_get1_RSA(key);
EVP_PKEY_free(key);

RSA_private_decrypt(inlen, indata, outdata, rsa, RSA_NO_PADDING)

ENGINE_free(engine_handle); // Decrement the lock count on the engine
```
And then I move on to process outdata.  My app works fine using a single thread, but as soon as I open up multiple threads, my app core dumps whenever any two decrypt operations overlap.

I have set up for threading using:
```
  CRYPTO_set_id_callback(fn_thread_id);
  CRYPTO_set_locking_callback(fn_lock_function);
```

I noticed that **SoftHSM is returning the same RSA context** each time that I call load_key.  This would explain the crash below because doing simultaneous operations using the same context is invalid.

Here is a partial stack of the crash:

*** Clip
bn_mul_add_words() at 0x7ffff747870b	
BN_from_montgomery_word() at 0x7ffff747d35e	
BN_from_montgomery() at 0x7ffff747d70a	
BN_mod_exp_mont_consttime() at 0x7ffff746f81d	
RSA_eay_mod_exp() at 0x7ffff748c7e7	
RSA_eay_private_decrypt() at 0x7ffff748db6e	
OSSLRSA::decrypt() at 0x7fffa3db94b3	
SoftHSM::C_Decrypt() at 0x7fffa3d8590d	
C_Decrypt() at 0x7fffa3d68a63	
proxy_C_Decrypt() at 0x7fffbc9a0a12	
binding_C_Decrypt() at 0x7fffbc9a4be2	
ffi_closure_unix64_inner() at 0x7fffbc77eb9b	
ffi_closure_unix64() at 0x7fffbc77ef14	
pkcs11_private_decrypt() at 0x7fffbcbcfff7	
ingenu::ozone::CryptoRsaPrivate::decrypt() at crypto.cpp:292 0x5210fa	
.
.
.
*** Clip

**Comment by bellgrim** [comment]
SoftHSM will not return any RSA context to your application. That would be the PKCS#11 engine in OpenSSL.

Or do you mean that SoftHSM will use the same context internally?
https://github.com/opendnssec/SoftHSMv2/blob/develop/src/lib/crypto/OSSLRSA.cpp#L595

**Comment by bellgrim** [comment]
Is libp11 the OpenSSL PKCS#11 engine? Have you set the callbacks according to?: https://github.com/OpenSC/libp11#thread-safety-in-libp11

**Comment by dansackinger** [comment]
Thank you for pointing me at the thread-safety-in-libp11.

I had hooked up the following thread functions:
CRYPTO_set_id_callback(fn_thread_id);
CRYPTO_set_locking_callback(fn_lock_function);

but did not set up:
CRYPTO_set_dynlock_create_callback(...);
CRYPTO_set_dynlock_lock_callback(...);
CRYPTO_set_dynlock_destroy_callback(...);

Once I implemented these three functions, everything worked as expected.

Thank you for taking a look into this.  Please feel free to close the issue.

Regards,

**Comment by pkalapat** [comment]
@dansackinger  could you please share an example snippet on how/where to set these call backs.

**Comment by rijswijk** [comment]
Hi,

pkalapat wrote:
> @dansackinger <https://github.com/dansackinger> could you please share
> an example snippet on how/where to set these call backs.

The description of the callbacks is here:

https://github.com/OpenSC/libp11#thread-safety-in-libp11

You need to set these OpenSSL callbacks first thing in your code, before
you do anything else. And you should also make sure not to clean them up
before your code is completely done, or risk running into a segfault.

Typically, on a POSIX-compliant system, I would expect you to use
pthread_mutex_* functions to implement these callbacks.

Cheers,

Roland

-- 
-- Roland M. van Rijswijk-Deij
-- SURFnet bv
-- w: https://www.surf.nl/en/about-surf/subsidiaries/surfnet
-- e: roland.vanrijswijk@surfnet.nl
