### ISSUE TITLE
Using SoftHSMv2 to sign PDFs with an Adobe trusted Certificate

### ISSUE THREAD

**Issue by manuschiller** [opendnssec/SoftHSMv2#312]
We developed a server side solution to create and sign PDFs automatically for our customers.
In order to sign the PDFs with a certificate from the Adobe AATL (trusted CAs) list, we ne a HSM solution that can be deployed to amazon aws. 
Would that be possible with SoftHSMv2? 

Thanks!

**Comment by bellgrim** [comment]
You can do some testing with SoftHSM, but you are not allowed to use it according to Adobe and its trusted CAs. SoftHSM is not a FIPS 140 Level 2 HSM.

You could have a look at e.g: https://aws.amazon.com/cloudhsm/
