### ISSUE TITLE
Where are the SoftHSM logs written?

### ISSUE THREAD

**Issue by varrat** [opendnssec/SoftHSMv2#314]
Hi.

I have tried using SoftHSM as a PKCS#11 key store configured for an encrypted DB2 environment.
I have followed the steps into the DB2 documentation for migrating from a local key store to a PKCS#11 one.
But, the step supposed to perform the effective migration of the keys to the PKCS#11 key store fails.
I would want to figure out if there would be some SoftHSM logs somewhere which could help me figuring out the problem I encounter.
But, I have not managed to find any log file related to SoftHSM on my machine.
I have configured SoftHSM with its configuration parameter log.level set to DEBUG.
Could you please tell me how to generate SoftHSM log files, and where to find them?

Thanks and regards.
Vincent

**Comment by bellgrim** [comment]
Have updated the README in #318 

> Log information is sent to syslog or the Windows event log and the log level is set in the configuration file. Each log event is prepended with the source file name and line number.

**Comment by varrat** [comment]
Thanks for your reply.
I have changed the /etc/rsyslog.conf content in order to write any application system log into the /var/log/messages file, and then I have restarted the rsyslog service.
I can now see the SoftSHM logs into the /var/log/messages file.

Regards.
Vincent

**Comment by pkalapat** [comment]
does softhsm.conf allow for specifying custom logging directory? If so which property can we use to set it?

**Comment by bellgrim** [comment]
@pkalapat No, SoftHSM only uses syslog or Windows event log depending on platform.

**Comment by dipnile2009** [comment]
@varrat Could you Please share the changes done in rsyslog.conf?

I tried with * for /var/log/messeges , but didn't worked for me.

**Comment by varrat** [comment]
@dipnile2009, here is what I have into my /etc/rsyslog.conf file:
*.info;mail.none;authpriv.none;cron.none                /var/log/messages
