### ISSUE TITLE
How to keep a key label when importing it into SoftHSM from a PKCS#8 file?

### ISSUE THREAD

**Issue by varrat** [opendnssec/SoftHSMv2#315]
Hi.

I have used a PKCS#8 file containing a key having a label named DB2_LABEL_NAME, for importing this key into SoftHSM.
In order to do that, I have used the following command which worked perfectly:
[i1111@lat117 ~]$ softhsm2-util --import /home/i1111/key.pem --token "DB2Partition" --label "DB2_LABEL_NAME" --id A3B2 --pin mypassword --no-public-key
Found slot 1042076245 with matching token label.
The key pair has been imported.

As a result, I can dump it using the softhsm2-dump-file command.
But the result of this dump output seems to show that the key label is lost when the key is imported in SoftHSM.
Am I true with my assumption that this label information is lost during a key import?
If yes, is there any way to keep it?

The reason why I ask this is that I am trying to configure an encrypted DB2 environment based on the usage of a SoftHSM PKCS#11 key store.
But, even if my DB2 environment is configured as expected for that, and even if the master key to be used is stored in SoftHSM, DB2 still does not succeed in locating it through the usage of its associated label.
Maybe because this label is not part of what is stored into SoftHSM for the key concerned.

Regards.
Vincent

**Comment by bellgrim** [comment]
No, it is there. When you dump the token file, you will just see the encrypted string.

```
# openssl genrsa -out private.pem 1024

# openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in private.pem -out private.p8

# softhsm2-util --pin 1234 import private.p8 --token test2 --label testkey --id A1B2 --no-public-key
Found slot 1845771071 with matching token label.
The key pair has been imported.

# pkcs11-tool --module /usr/local/lib/softhsm/libsofthsm2.so -O -p 1234 -l
Using slot 0 with a present token (0x6e043b3f)
Private Key Object; RSA 
  label:      testkey
  ID:         a1b2
  Usage:      decrypt, sign, unwrap

# softhsm2-dump-file /var/lib/softhsm/tokens/74a4205b-6121-f5aa-b185-b4b4ee043b3f/3c6e53b2-8ba5-6090-1c7f-a5118603558f.object
Dump of object file "/var/lib/softhsm/tokens/74a4205b-6121-f5aa-b185-b4b4ee043b3f/3c6e53b2-8ba5-6090-1c7f-a5118603558f.object"
[...]
00 00 00 00 00 00 00 03 CKA_LABEL
00 00 00 00 00 00 00 03 byte string attribute
00 00 00 00 00 00 00 20 (length 32)
b4 f9 e2 c2 90 da 3f 8f <......?.>
50 92 87 3f 73 62 9f 68 <P..?sb.h>
02 fe 79 a7 a3 aa e7 6f <..y....o>
92 6a cd 24 96 90 a5 ac <.j.$....>
[...]
```
