### ISSUE TITLE
Building on CentOS 7.2 (1511)

### ISSUE THREAD

**Issue by Batouu** [opendnssec/SoftHSMv2#316]
Hi,

I'm having some trouble building softhsm2 on centOS 7.2(1511).
When i do "make install", i got an error with the library libsofthsm2.
"/bin/mkdir -p '/usr/local/lib/softhsm'
/bin/sh ../../libtool --mode=install /bin/install -c  /libsofthsm2.la  '/usr/local/lib/softhsm'
libtool: install:  /bin/install -c .libs/libsofthsm2.so  /usr/local/lib/softhsm/libsofthsm2.so
/bin/install: cannot stat '.libs/libsofthsm2.so' : No such file or directory
make[4]: *** [install-libLTLIBRARIES] Error 1
... "
I think the .libs directory is created during the library installation but it would seem that not.
Am i doing something wrong ?

(Note : My installation steps :
./configure --with-objectstore-backend-db --disable-gost
make 
make install )

Thanks,
Jeremy.

**Comment by Batouu** [comment]
apparently, the libtool packet needed wasn't properly installed. I solved my issue by adding the libtool packet.

**Comment by camilog** [comment]
Hello @Batouu I'm having the same problem but I didn't understand how you solved it, can you help me please?

**Comment by Batouu** [comment]
Hi @camilog , 
sorry for the late answer. To fix my problem, i used : 
`yum install libtool` to reinstall libtool package which doesn't seem to be correctly installed.

**Comment by camilog** [comment]
Thanks @Batouu for your answer
I fixed it also but only when I installed `libtool-ltdl-devel` package and then `make` the project.

**Comment by xyakimo1** [comment]
I faced the same issue on `Debian Bullseye`. The solution was to install `libtool-bin` package.
