### ISSUE TITLE
EdDSA support

### ISSUE THREAD

**Issue by fxdupont** [opendnssec/SoftHSMv2#323]
For DNSSEC we need EdDSA support for Ed25519 and Ed448 curves. The first one is supported by a recently merged PR in github OpenSSL (1.1.1), there is nothing on the PKCS#11 side but it already has an ECC framework and extension mechanisms so I decided to experiment for DNSSEC usages (cf RFC 8080) and ISC Bind 9 (working)...

**Comment by bellgrim** [comment]
Moving this to 2.5.0. EDDSA is still a draft in PKCS#11.

**Comment by rijswijk** [comment]
I think it would be good to implement the draft spec from PKCS #11 in 2.5.0

**Comment by bellgrim** [comment]
Fixed

**Comment by jariq** [comment]
Can you please post link to mentioned "PKCS#11 EDDSA draft 4" ?

**Comment by bellgrim** [comment]
https://www.oasis-open.org/committees/document.php?document_id=62198&wg_abbrev=pkcs11
