### ISSUE TITLE
Support for CKM_AES_GCM

### ISSUE THREAD

**Issue by bellgrim** [opendnssec/SoftHSMv2#325]
Add support for AES GCM mode. This feature request was originally in #142.

**Comment by bellgrim** [comment]
Fixed in #344

**Comment by fqutishat** [comment]
@bellgrim I tried to use CKM_AES_GCM to Decrypt but I have this error EVP_DecryptFinal failed (0x00000000): error:00000000:lib(0):func(0):reason(0).

To make sure the key i used for decryption is correct i get CKA_VALUE for the key and decrypted outside softhsm and it's working

**Comment by bellgrim** [comment]
@fqutishat The implementation can encrypt and decrypt using the test vectors from NIST. Do you have some test data I can try with?

**Comment by fqutishat** [comment]
@bellgrim I solve the issue it was in the ulTagBits I was putting wrong value it's working now.

Thanks
