### ISSUE TITLE
Documentation and example for AES and RSA key wrapping

### ISSUE THREAD

**Issue by iTestAndroid** [opendnssec/SoftHSMv2#328]
I'm trying to use SoftHSMv2 and have AES and RSA key wrapping enabled. I can't figure out where and how. Can we have some documentation and maybe example code?

Mainly I'm trying to use it along with nodejs pkcs11 and graphene, but even C++ sample would be nice so I can port it to Node

**Comment by jariq** [comment]
There's [C# code sample](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/3.3.0/src/Pkcs11Interop/Pkcs11InteropTests/HighLevelAPI/_24_WrapAndUnwrapKeyTest.cs) which demonstrates how to wrap and unwrap key and you might also want to read page 178-181 of [official PKCS#11 v2.20 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/tree/master/v2.20).

**Comment by iTestAndroid** [comment]
Thanks a lot for very quick response! I'm going to go through it all.

Just one little question. Between these two scenarios which one you think is correct way to use HSM to store master encryption key of data we'll be putting in DB. We are going to encrypt all the sensitive password and credentials using HSM.

1) Make HSM generate a public/private key pair and it will keep the private key inside it and it will never leave. Now I can create a random symmetric key per entry I want to encrypt. I encrypt the data with random AES key, encrypt the AES key with public key generated in HSM and store result of encrypted data + encrypted key data in each row in DB. Now everytime I want to access the data, I send encrypted key data to HSM, HSM will decrypt it and send me back the decrypted AES key, I use that to actually decrypt data.

2) Per row/per entry, I make HSM to generate AES key and store the symmetric key token in it. I send data in plaintext to it, it sends me back in encrypted form. Everytime I want to access the data, I send encrypted data to HSM and it will decrypt and send it back to me.

HSM server will be a professional and fast one like Thales, so it can handle the traffic with good speed (hopefully).

The thing with first one is I only have to login as SO (Security Officer) to generate and store my public/private key pair in HSM and from now on, I just have to login as Read only user. But its slower and lenghty process compared to number 2.

Number 2 (as far as I know) will require me to have SO access to device whole time.

What do you suggest? Please advise.

**Comment by bellgrim** [comment]
No, you should not log in as SO since it can only create public objects. You must login as the normal user.

```
R/W Public Session | The application has opened a read/write session. The application has read/write access to all public objects.
R/W SO Functions | The Security Officer has been authenticated to the token. The application has read/write access only to public objects on the token, not to private objects. The SO can set the normal user’s PIN.
R/W User Functions | The normal user has been authenticated to the token. The application has read/write access to all objects.
```

Specific questions on Thales or application design should be directed to other forums.
