### ISSUE TITLE
Security: Authorization problem with multiple open sessions

### ISSUE THREAD

**Issue by mheese** [opendnssec/SoftHSMv2#329]
Hey guys,

Unfortunately, I can't share any code examples of the problem. However I'm trying my best to explain the issue - and maybe this is even expected?!

Here is the scenario:
1. Open a new pkcs11 context loading the softhsm2 module
2. There are 10 objects in the token; 8 of them have the CKA_PRIVATE attribute set to true.
3. Open a new public and read-only session A
4. list all objects ("empty" search template to get everything), and we'll get 2 objects with all their attributes as expected
5. Open a new user role and read-write session B
6. using B, list all objects, and we'll get 10 objects with all their attributes (among them also the ones with CKA_PRIVATE attribute of course)
7. now here comes the problem: using session A, and issuing another _list all objects_ ... now it looks like the session got an "upgrade": it will list 10 objects (!), also all the ones which have the CKA_PRIVATE attribute set to true
8. using session A, trying to delete an object (with CKA_PRIVATE) fails 
9. using session B, trying to delete an object (with CKA_PRIVATE) succeeds
10. closing session B
11. using session A, and issuing another _list all objects_ ... now the session is back to the expected behaviour: we see only 2 objects

I'm using SoftHSM v2.2.0 compiled against OpenSSL 1.1.x if this is important somehow.

Regards,
Marcus

**Comment by bellgrim** [comment]
Everything up to 10 is expected behavior. 11 might have an issue.

7. Yes, it will be upgraded. PKCS#11 v2.40: "Since all sessions an application has with a token have a shared login state, C_Login only needs to be called for one of the sessions."
8. It fails because it is read-only session.
9. It can delete an object because it is a read-write session.
11. It should still see all 9 objects, unless you also logged out in 10?

**Comment by mheese** [comment]
Yes, I also logged out in 10.

OK, good to see that this is expected behaviour. I was guessing that already because that looked too obvious to miss to me. I'm closing this issue now then.

@bellgrim Thanks for the quick answer - much appreciated! And thanks for the good work on this project btw.

**Comment by pkalapat** [comment]
Thanks for sharing the question and the answer. I was interested in this use case as well. But doesn't step 10 automatically mean logging out of session? I.e isn't calling close on session going to log out the user automatically? Do we have to explicitly logout?  I'm asking so as to double check we are not leaving out any vulenerabilities in our implementation

**Comment by pkalapat** [comment]
Also I hope this will not be the case across PKCS11 client contexts. In our application there are about 5-6 client nodes that open a PKCS11 context and connect to a common softhsm server running in a docker. I will test this out and share the findings but my expectation is that the Login r/w permissions are not upgraded/downgraded automatically across PKCS11 client contexts. Will keep you posted on what I find

**Comment by mheese** [comment]
@pkalapat as long as your clients are running in separate processes, you really get a new/fresh client context, and you should be good then.

It was a bit tricky to find out, however, the important part is that the module gets loaded twice. If you are doing it in the same process, you  are able to create two contexts, however, as the module as dynamically loaded, the dynamic loader will not load the module twice if it was already loaded before (there is just a counter increased). The two contexts are then essentially the same - they might look different at first, but they are pointing to the same state (which makes sense when one reasons about it).

There is a small workaround to still make it happen within one process though: copy the pkcs11 module to another file (using the same configuration for it), and load the module from that file. Now to the dl it looks like it is a new module and it will load it again giving you really a fresh context.

However, there is a drawback to this: you might see increased PKCS11 errors (that's what I saw) due to not thread-safe access basically.

Anyway, I hope this is helpful for you @pkalapat !

**Comment by pkalapat** [comment]
Thanks  for the detailed explanation @mheese
