### ISSUE TITLE
configure: error: C++ compiler cannot create executables

### ISSUE THREAD

**Issue by dnyati** [opendnssec/SoftHSMv2#337]
Hi,

    I am trying to configure softHSM  It gives me below messge :
configure: error: C++ compiler cannot create executables
I have c++  complier installed in my system. Is there anything I am missing?

Thanks

**Comment by bellgrim** [comment]
Check the config.log for more details on the error. 

What OS are you running? If you are using Ubuntu, have you tried installing this:

```
sudo apt-get install build-essential
```
