### ISSUE TITLE
Generate ZMK using Clear components

### ISSUE THREAD

**Issue by dnyati** [opendnssec/SoftHSMv2#338]
I need to "Generate ZMK using Clear components". Could you please let me know how to generate ZMK using clear components using software. Is HSM (hardware ) mandatory for this or it is possible using software as well? If yes how? Can I use Thales simulator (I believe this is software) in production up to 7000 transactions a day.

**Comment by bellgrim** [comment]
Sorry do not know what "ZMK" is, are you talking about ZSK (Zone Signing Key) used for DNSSEC? Then you should add SoftHSM as an HSM in the software responsible for handling the DNSSEC keys. Usually you configure a path to the SoftHSM library, the token label, and the PIN.

If it is mandatory to use an HSM depends on what purpose the keys are going to be used. E.g. financial transactions. You should check with applicable regulations and laws. It could also be the case the you want to use an HSM to mitigate some threats found during your risk analysis.

Any questions on other HSM:s or how to configure HSM:s in a application should be directed to the HSM vendor or the application developer.
