### ISSUE TITLE
Private objects are presented to security officer in search results

### ISSUE THREAD

**Issue by jariq** [opendnssec/SoftHSMv2#345]
I am working on resolving [a simple issue in Pkcs11Admin application](https://github.com/Pkcs11Admin/Pkcs11Admin/issues/12) and I am using SoftHSM 2.3.0 statically linked to OpenSSL 1.1.0f on Windows 10 to test the results of my work. I am having trouble to read objects and their attributes when logged in as `CKU_SO` user. The root cause of the problem is that private objects are presented to security officer in search results.

Steps to reproduce:
1. Initialize new token with `softhsm2-util.exe`
2. Login as `CKU_USER`
3. Generate AES key with `CKA_PRIVATE=CK_TRUE` 
4. Logout
5. Login as `CKU_SO`
6. Search for objects with search template containing `CKA_CLASS=CKO_SECRET_KEY`  
Note: AES key generated in step 3 will be found.
7. Read any attribute of the found object  
Note: `C_GetAttributeValue` will fail with `CKR_GENERAL_ERROR` and event log will contain message [`..\..\src\lib\SoftHSM.cpp(1639): User is not authorized`](https://github.com/opendnssec/SoftHSMv2/blob/2.3.0/src/lib/SoftHSM.cpp#L1639). 

Quick search in [PKCS#11 v2.20 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/tree/master/v2.20) reveals that:

> Only the normal user is allowed access to private objects on the token, and that access is granted only after the normal user has been authenticated.

There is also description of `CKS_RW_SO_FUNCTIONS` session state: 

> The Security Officer has been authenticated to the token. The application has read/write access only to public objects on the token, not to private objects. The SO can set the normal user’s PIN.

IMHO objects with `CKA_PRIVATE=CK_TRUE` should not be presented to the `CKU_SO` user in search results.

**Comment by bellgrim** [comment]
Thanks for spotting this. The SO should only find public objects. The fix is to this line:
https://github.com/opendnssec/SoftHSMv2/blob/2.3.0/src/lib/SoftHSM.cpp#L1728

**Comment by bellgrim** [comment]
Fixed in #347

**Comment by jariq** [comment]
I can confirm that change introduced in #347 fixes the issue. Thank you very much @bellgrim,
