### ISSUE TITLE
headers are not installed on make install

### ISSUE THREAD

**Issue by gijzelaerr** [opendnssec/SoftHSMv2#352]
what happened to this file?

https://github.com/opendnssec/SoftHSMv2/blob/b924869b83c0dac2a8364401f62de7d2c7c5b5dd/src/lib/cryptoki_compat/pkcs11.h

In the debian package it is manually installed:

https://anonscm.debian.org/git/pkg-dns/softhsm2.git/tree/debian/rules#n49

**Comment by gijzelaerr** [comment]
what happened to this file?

https://github.com/opendnssec/SoftHSMv2/blob/b924869b83c0dac2a8364401f62de7d2c7c5b5dd/src/lib/cryptoki_compat/pkcs11.h

In the debian package it is manually installed:

https://anonscm.debian.org/git/pkg-dns/softhsm2.git/tree/debian/rules#n49

**Comment by bellgrim** [comment]
It is an internal file of SoftHSM and should not be installed. An application who want to use PKCS#11 should download the header files from the authoritative source:
http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/include/pkcs11-v2.40/

**Comment by gijzelaerr** [comment]
ok clear, will do that.
