### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by gijzelaerr** [opendnssec/SoftHSMv2#353]
Just to let you know, there is a homebrew formula work in progress PR:

https://github.com/Homebrew/homebrew-core/pull/19885

**Comment by gijzelaerr** [comment]
the formula is complete, but there is one remaining issue:

```
It looks like the formula is installing libsofthsm2.so not libsofthsm2.dylib, which is a porting issue that needs to be fixed upstream before we can include this software in Homebrew.
```

**Comment by bellgrim** [comment]
Thanks, will add a reference to it once it has been published

**Comment by bellgrim** [comment]
@gijzelaerr I did not get any feedback on the Homebrew PR. Have you had any discussions with the developers?

> PKCS#11 should be considered as dynamically loadable modules (.so/.bundle) and not as shared libraries (.dylib). That you dynamically load (dlopen) and not via dynamic linking.
>
> Compare with another PKCS#11 library: http://brewformulas.org/Opensc
>
> They even reverted from .dylib to .so: OpenSC/OpenSC@630e7ee#diff-67e997bcfdac55191033d57a16d1408a

**Comment by gijzelaerr** [comment]
Hi @bellgrim. Sorry for not getting back to you. I trust your judgment so I agree. Problem is that homebrew people don't seem to be convinced. I don't have time to convince them at the moment, might try to do this at some point again. Thanks for your time.
