### ISSUE TITLE
Missing mechanism CKM_AES_MAC

### ISSUE THREAD

**Issue by Ovomaltine85** [opendnssec/SoftHSMv2#354]
Hi!

I'm using softhsm 2.3.0 and I have a secret 256 bit AES key stored on my token. It is marked as sensitive and non-extractable. Therefore I would like to use the AES MAC functionality of the HSM. The documentation says that the regarding mechanism CKM_AES_MAC should be available (0x1083). But if I have a look to my softhsm with `pkcs11-tool -M` I get the following output:

`Supported mechanisms:
  MD5, digest
  SHA-1, digest
  mechtype-0x255, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5-HMAC, keySize={16,512}, sign, verify
  SHA-1-HMAC, keySize={20,512}, sign, verify
  mechtype-0x256, keySize={28,512}, sign, verify
  mechtype-0x251, keySize={32,512}, sign, verify
  mechtype-0x261, keySize={48,512}, sign, verify
  mechtype-0x271, keySize={64,512}, sign, verify
  RSA-PKCS-KEY-PAIR-GEN, keySize={512,16384}, generate_key_pair
  RSA-PKCS, keySize={512,16384}, encrypt, decrypt, sign, verify, wrap, unwrap
  RSA-X-509, keySize={512,16384}, encrypt, decrypt, sign, verify
  MD5-RSA-PKCS, keySize={512,16384}, sign, verify
  SHA1-RSA-PKCS, keySize={512,16384}, sign, verify
  RSA-PKCS-OAEP, keySize={512,16384}, encrypt, decrypt, wrap, unwrap
  mechtype-0x46, keySize={512,16384}, sign, verify
  SHA256-RSA-PKCS, keySize={512,16384}, sign, verify
  SHA384-RSA-PKCS, keySize={512,16384}, sign, verify
  SHA512-RSA-PKCS, keySize={512,16384}, sign, verify
  SHA1-RSA-PKCS-PSS, keySize={512,16384}, sign, verify
  mechtype-0x47, keySize={512,16384}, sign, verify
  mechtype-0x43, keySize={512,16384}, sign, verify
  mechtype-0x44, keySize={512,16384}, sign, verify
  mechtype-0x45, keySize={512,16384}, sign, verify
  DES-KEY-GEN, generate
  DES2-KEY-GEN, generate
  DES3-KEY-GEN, generate
  DES-ECB, encrypt, decrypt
  DES-CBC, encrypt, decrypt
  DES-CBC-PAD, encrypt, decrypt
  mechtype-0x1100, derive
  mechtype-0x1101, derive
  DES3-ECB, encrypt, decrypt
  DES3-CBC, encrypt, decrypt
  DES3-CBC-PAD, encrypt, decrypt
  mechtype-0x1102, derive
  mechtype-0x1103, derive
  AES-KEY-GEN, keySize={16,32}, generate
  AES-ECB, keySize={16,32}, encrypt, decrypt
  AES-CBC, keySize={16,32}, encrypt, decrypt
  AES-CBC-PAD, keySize={16,32}, encrypt, decrypt
  mechtype-0x1086, keySize={16,32}, encrypt, decrypt
  mechtype-0x2109, keySize={16,2147483648}, wrap, unwrap
  mechtype-0x210A, keySize={1,2147483648}, wrap, unwrap
  mechtype-0x1104, derive
  mechtype-0x1105, derive
  DSA-PARAMETER-GEN, keySize={512,1024}, generate
  DSA-KEY-PAIR-GEN, keySize={512,1024}, generate_key_pair
  DSA, keySize={512,1024}, sign, verify
  DSA-SHA1, keySize={512,1024}, sign, verify
  mechtype-0x13, keySize={512,1024}, sign, verify
  mechtype-0x14, keySize={512,1024}, sign, verify
  mechtype-0x15, keySize={512,1024}, sign, verify
  mechtype-0x16, keySize={512,1024}, sign, verify
  DH-PKCS-KEY-PAIR-GEN, keySize={512,10000}, generate_key_pair
  DH-PKCS-PARAMETER-GEN, keySize={512,10000}, generate
  DH-PKCS-DERIVE, keySize={512,10000}, derive
  ECDSA-KEY-PAIR-GEN, keySize={112,521}, generate_key_pair, other flags=0x1900000
  ECDSA, keySize={112,521}, sign, verify, other flags=0x1900000
  ECDH1-DERIVE, keySize={112,521}, derive`

I compiled softhsm with openssl 1.1.0f.

Thank you

**Comment by bellgrim** [comment]
Sorry, that mechanism is not supported. Which documentation are you referring to?

(CKM_AES_CMAC was however added to the develop branch some days ago: https://github.com/opendnssec/SoftHSMv2/commit/bdeb7827c794c297438e06f7f795dd3b66ceb70)

**Comment by Ovomaltine85** [comment]
Thank you for your reply. I'm referring to this docu: http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/os/pkcs11-curr-v2.40-os.html#_Toc416960057

What do you think when the new release will come?

**Comment by bellgrim** [comment]
Yes, that is the official PKCS#11 mechanisms specification. But it does not require a vendor to implement all mechanisms. I interpreted your initial request, not as a feature request, but as a remark that CKM_AES_MAC was mentioned in the documentation of SoftHSM and that it was not advertised in its mechanism list.

We will not implement CBC-MAC mechanisms since it has been deprecated in Botan, as mentioned in #220.

The next release will come before the end of this year, which will have the CMAC support for DES3 and AES.
