### ISSUE TITLE
Can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file 'libsofthsm2.so'

### ISSUE THREAD

**Issue by gijzelaerr** [opendnssec/SoftHSMv2#355]
When I try to link against SoftHSMv2 on OS X my linker complains about libsofthsm2.so being a bundle, while it should be a dylib.

**Comment by bellgrim** [comment]
Do you have some more context for this issue? What commands have you used? Some snippets of the output?

**Comment by gijzelaerr** [comment]
I'm linking against softhsm2 on OS X.

Project: https://github.com/arpa2/keehive

When I compile my program:

```
/Library/Developer/CommandLineTools/usr/bin/cc  -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/wrap.dir/wrap.c.o  -o wrap /usr/local/Cellar/cmocka/1.1.1/lib/libcmocka.dylib -L/usr/local/lib/cmake/Quick-DER/../../ -lquickder /usr/local/lib/softhsm/libsofthsm2.so /usr/lib/libssl.dylib /usr/lib/libcrypto.dylib
```

I get the error:
```
ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file '/usr/local/lib/softhsm/libsofthsm2.so' for architecture x86_64
```

When I examine the shared library it indeed is a bundle:

```
$  file /usr/local/lib/softhsm/libsofthsm2.so
/usr/local/lib/softhsm/libsofthsm2.so: Mach-O 64-bit bundle x86_64
$  file /usr/lib/libssl.dylib
/usr/lib/libssl.dylib: Mach-O universal binary with 2 architectures: [i386: Mach-O dynamically linked shared library i386] [x86_64: Mach-O 64-bit dynamically linked shared library x86_64]
/usr/lib/libssl.dylib (for architecture i386):  Mach-O dynamically linked shared library i386
/usr/lib/libssl.dylib (for architecture x86_64):        Mach-O 64-bit dynamically linked shared library x86_64
```

First of all, shared libraries should have the .dylib extension on OS X. Secondly, after reading this article:

https://docstore.mik.ua/orelly/unix3/mac/ch05_03.htm

I think SoftHSMv2 is compiled with -bundle by default on OS X?

**Comment by bellgrim** [comment]
I compared with http://brewformulas.org/Opensc and they do not install .dylib but .so for their PKCS#11 libraries (opensc-pkcs11.so and pkcs11-spy.so).

It also seems that they reverted from .dylib to .so for OS X: https://github.com/OpenSC/OpenSC/commit/630e7ee08efe01c4a8db621df373f19153f8a2fd#diff-67e997bcfdac55191033d57a16d1408a

Have you tried to use dlopen() instead of linking with the PKCS#11 library?

**Comment by gijzelaerr** [comment]
it would be interesting to know why they switched back to `.so`. As far is I know any shared library needs to have the dylib postfix on OS X.

I tried dlopen() and that works.

Meanwhile, the homebrew formula for SoftHSMv2 got rejected because of the .so extension in the lib.

**Comment by bellgrim** [comment]
I think that PKCS#11 libraries should be considered as dynamically loadable modules (.so/.bundle) and not as shared libraries (.dylib). That you dynamically load (dlopen) and not via dynamic linking.

**Comment by gijzelaerr** [comment]
Sorry for not replying anymore. I'm convinced by your answer :) Sorry for the noise.
