### ISSUE TITLE
HMAC Mechanisms missing?

### ISSUE THREAD

**Issue by daviddob** [opendnssec/SoftHSMv2#372]
I just installed SoftHSMv2 2.3.0 and 2.4.0 and tried using CKM_SHA256_HMAC which says it is supported in the documentation.

When checking machanisms via pkcs11-tool it appears that almost all of the HMAC mechanisms are not listed, though they are stated as supported here (https://wiki.opendnssec.org/display/SoftHSM/v2+Mechanisms)

pkcs11-tool --module /usr/local/bin/softhsm/lib/softhsm/libsofthsm2.so -M | grep HMAC
Using slot 0 with a present token (0x69347933)
  MD5-HMAC, keySize={16,512}, sign, verify
  SHA-1-HMAC, keySize={20,512}, sign, verify

I have also tried with openssl versions 1.0.2g and 1.0.1f

Is there something that I am missing on the install or are newer versions of openssl/other dependencies required?

Thanks

**Comment by bellgrim** [comment]
It is not missing. You just need to upgrade your pkcs11-tool: https://github.com/OpenSC/OpenSC/commit/41796ff0ed3125bebe29479fc831165ba40c9a3b

Check the output from the pkcs11-tool for "unknown" mechanisms. CHM_SHA256_HMAC is e.g. "mechtype-593".
