### ISSUE TITLE
Support for CKM_GENERIC_SECRET_KEY_GEN

### ISSUE THREAD

**Issue by daviddob** [opendnssec/SoftHSMv2#375]
Currently using HMAC with PKCS11 2.4.0 is difficult as SoftHSM does not support generating generate secret generation via CKM_GENERIC_SECRET_KEY_GEN that many software packages require for using HMAC. Is there a planned addition for this in the near future?

Thanks.

**Comment by bellgrim** [comment]
Thank you for the request and implementation. Will review it once I have worked through some of the issues on my backlog.
