### ISSUE TITLE
./configure ECC support error 

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#378]
I'm in the process of trying to get softHSM-2.4 built and working. I have just built and installed openssl-1.1.1-pre2 successfully.

However, when i come to run ./configure for softHSM it seems to succeed until the very end when it states:

checking for OpenSSL ECC support --- Cannot find P256, P384, or P521
configure: error: OpenSSL library has no ECC support

The default build of OpenSSL is to include ECC (so I believe)

Is there some mismatch between what softHSM is checking for and what OpenSSL supports

**Comment by bellgrim** [comment]
It should work.

Is EC in the list of support algorithms in OpenSSL?

```
$ openssl list -public-key-algorithms
...
Name: OpenSSL EC algorithm
	Type: Builtin Algorithm
	OID: id-ecPublicKey
	PEM string: EC
...
```

Are you building against the correct OpenSSL? You can specify e.g. --with-openssl=/usr/local/ssl/ when configuring SoftHSM to find OpenSSL.
