### ISSUE TITLE
Slot ID is not assigned as given from the command line.

### ISSUE THREAD

**Issue by pramodrj07** [opendnssec/SoftHSMv2#382]
Hi,

When i try to create a initialize a token in slot 1, the output is successful, but it is trying to assign it to another slot number. 

command - softhsm2-util --init-token --slot 1 --label "My token 2" --pin 1234 --so-pin 1234

 output - "The token has been initialized and is reassigned to slot 1331691202"

Can anyone give me an insight ? 
 
I am using the 2.3.0' s latest stable branch

Regards,
Pramod

**Comment by bellgrim** [comment]
Yes, this is expected behaviour. From latest README:

> Initialized tokens will be reassigned to another slot (based on the token serial number). It is recommended to find and interact with the token by searching for the token label or serial number in the slot list / token info.
