### ISSUE TITLE
Add  support for PublicKeyInfo Attribute 

### ISSUE THREAD

**Issue by pkalapat** [opendnssec/SoftHSMv2#393]
Our implementation needs to use PublicKeyInfo. The current implementation of this library doesn't enable this attribute. Upon testing and inspection of the code it was found that the support for the attribute was missing primarily due to wrong type being set in the attribute constructor. The type is wrongly being set as CKA_OBJECT_ID instead of setting as CKA_PUBLIC_KEY_INFO.

A simple fix of assigning the right type in the constructor as below
fixed the issue. here is git diff P11Attributes.h

```
@@ -345,7 +345,7 @@ class P11AttrPublicKeyInfo : public P11Attribute
{
public:
// Constructor
  P11AttrPublicKeyInfo(OSObject* inobject, CK_ULONG inchecks) : P11Attribute(inobject) { type = CKA_OBJECT_ID; checks = inchecks; }
  P11AttrPublicKeyInfo(OSObject* inobject, CK_ULONG inchecks) : P11Attribute(inobject) { type = CKA_PUBLIC_KEY_INFO; checks = inchecks; 
}
```
With the fix we can now create and set pkcs11.NewAttribute(pkcs11.CKA_PUBLIC_KEY_INFO, info) There are several attributes disabled in current implementation of PKCS11 Private and Public objects we plan to find and patch them as well eventually.

Wondering if there is interest to accept a pull request for the fix for CKA_PUBLIC_KEY_INFO or if this has been fixed by other means.

**Comment by bellgrim** [comment]
Thanks for spotting this, will merge the pull request.
