### ISSUE TITLE
Import AES key

### ISSUE THREAD

**Issue by lorenzotomasini** [opendnssec/SoftHSMv2#398]
Hello,

I'm currently using SoftHSM even in docker containers, without big issues. However, I have a requirement that forces me to import an AES key in the HSM. Is it possible to import a AES key into SoftHSM? if yes how can i do that? i am currently struggling with `softhsm2-utils --import` command without success...

Thank you!

**Comment by bellgrim** [comment]
`softhsm2-utils --import` only support asymmetric keys, but it is supported if you use the PKCS#11 API of SoftHSM.

However, you can try `pkcs11-tool --write-object` if you want to use a command line tool.

**Comment by lorenzotomasini** [comment]
Sorry for bothering, i found out the right api call. (For who is interested is [this one](https://www.cryptsoft.com/pkcs11doc/v220/pkcs11__all_8h.html#aC_CreateObject) with correct AES attributes).

And btw, with the `pkcs11-tool --write-object` i was not able to import a secret key, only private, public or data.

Thank you anyway
