### ISSUE TITLE
Windows Setup: No key available for 4EE17CD2

### ISSUE THREAD

**Issue by chenx832** [opendnssec/SoftHSMv2#401]
When I do the following command, there's no key to receive. Could you please upload a public key?

win32Setup: line 219
gpg --keyserver pgp.mit.edu --recv-keys 4EE17CD2

Thanks!

**Comment by bellgrim** [comment]
@halderen Could you have a look at this?

**Comment by halderen** [comment]
The mentioned key and keyserver are actually incorrect.  The correct keyserver is pgp.surfnet.nl and the key-id is Issue #401, so the command mentioned in the documentation should actually have been:

    gpg --keyserver pgp.surfnet.nl --recv-keys 4FCB0B94
