### ISSUE TITLE
update attribute when algo does not support

### ISSUE THREAD

**Issue by hgreinim** [opendnssec/SoftHSMv2#406]
Hi,
In P11Attributes.cpp in function updateAttr the check value always set to the attribute without chacking the value.
In my case the des implementation does not support (from security reason), and thus the check value wae return with empty biteString (size ==0) but it is set to the attribute and then the load function failed.

my suggestion is to add the following lines in line 1046:
`if(checkValue.size() == 0) 
return CKR_GENERAL_ERROR;`

thanks,
Hill

**Comment by bellgrim** [comment]
The key check value (CKA_CHECK_VALUE) is supported in SoftHSM and any crypto backend in SoftHSM must return a value. If the application does not want the KCV, it must supply the attribute in the template as a no-value (0 length) entry.

Have you implemented a custom crypto backend for SoftHSM?
