### ISSUE TITLE
C_GenerateKey() gives error CKR_TEMPLATE_INCOMPLETE on Windows

### ISSUE THREAD

**Issue by ramesh23gupta** [opendnssec/SoftHSMv2#411]
I get error CKR_TEMPLATE_INCOMPLETE while calling function C_GenerateKey() on Windows platform.
However, same code works on Linux platform (even with few attributes than mentioned below).
Below are my usage details.

CK_MECHANISM 	mechanism = { CKM_AES_KEY_GEN, NULL_PTR, 0 };
CK_OBJECT_CLASS 	class = CKO_SECRET_KEY;
CK_KEY_TYPE 		keytype = CKK_AES;
CK_BBOOL 		truevalue = CK_TRUE;
CK_BBOOL 		falsevalue = CK_FALSE;
CK_ULONG 		value_len = 32; /* key size in bytes *
char 			        uuid_str[] = "ef76bf84e16c5240d6aeac4b2fc94346";
CK_ATTRIBUTE          aes_template[] = {
		{CKA_CLASS, &class, sizeof(class)},
		{CKA_TOKEN, &truevalue, sizeof(truevalue)},
		{CKA_PRIVATE, &truevalue, sizeof(truevalue)},
		{CKA_LOCAL, &truevalue, sizeof(truevalue)},
		{CKA_MODIFIABLE,&falsevalue, sizeof(falsevalue)},
		{CKA_LABEL, label, sizeof(label)-1},
		{CKA_KEY_TYPE, &keytype, sizeof (keytype) },
		{CKA_ID, uuid_str, sizeof(uuid_str)-1},
		{CKA_SENSITIVE, &truevalue, sizeof(truevalue)},
		{CKA_ENCRYPT, &truevalue, sizeof (truevalue) },
		{CKA_DECRYPT, &truevalue, sizeof (truevalue) },
		{CKA_SIGN, &falsevalue, sizeof(falsevalue)},
		{CKA_VERIFY, &falsevalue, sizeof(falsevalue)},
		{CKA_EXTRACTABLE, &falsevalue, sizeof(falsevalue)},
		{CKA_VALUE_LEN, &value_len, sizeof(value_len)},
		{CKA_WRAP, &truevalue, sizeof(truevalue)},
		{CKA_UNWRAP, &truevalue, sizeof(truevalue)}
	};

C_GenerateKey(*session, &mechanism, aes_template, sizeof(aes_template)/sizeof(CK_ATTRIBUTE), &hkey);

I have got the SoftHSM installer from https://github.com/disig/SoftHSM2-for-Windows

Can some one tell me which attribute is missing in my template?

Thanks.

**Comment by rijswijk** [comment]
The following attributes are mandatory, and will fail AES key generation with CKR_TEMPLATE_INCOMPLETE:

CKA_VALUE_LEN
CKA_CLASS
CKA_KEY_TYPE

It looks like all of these are set; have you tried enabling logging in SoftHSM? It should log the reason it thinks the template is incomplete (see P11Objects.cpp, line 274 in trunk)

**Comment by rijswijk** [comment]
In your original example, you already had CKA_VALUE_LEN set, right? But yet you report that you got CKR_TEMPLATE_INCONSISTENT. Unfortunately, I cannot help you to enable logging on Cygwin, since I don't have a Windows system handy to test on. I suggest you ask the packagers of the Windows version if they can assist you.

**Comment by ramesh23gupta** [comment]
Yes, in my original example, I already had CKA_VALUE_LEN.

**Comment by dengert** [comment]
The problem could be `{CKA_ID, uuid_str, sizeof(uuid_str)-1},`
PKCS\#11 v2.4  "4.7.2 Overview "says "CK_ID In the case of secret keys, the meaning of the CKA_ID attribute is up to the application." It might be that the code is only assuming CK_ID is for public keys, private keys and certificates. 

It easy to try without the CKA_ID.  You could also try removing other attributes from the template, till you get it to work especially ones that have a default value.

**Comment by dengert** [comment]
In your original post this line:
`CK_ULONG value_len = 32; /* key size in bytes *`
is missing a final "/". Is that just a cut-and-paste error or is it the problem?

In your test program  you are only passing 1 CK_ATTRIBUTE. You may need others. 
In `rc = pFunc(session, &mechanism, crt_aes_template, 1, hkey);` 
should that be `&hkey`?

To debug look at [cygin gdb](https://cygwin.com/cygwin-ug-net/gdb.html)

You may need to modify the [SoftHSM2-for-Windows](https://github.com/disig/SoftHSM2-for-Windows)
to add -g to the compile and link steps.

**Comment by bellgrim** [comment]
CKA_CLASS and CKA_KEY_TYPE are not required in the template since they are implicitly given when using CKM_AES_KEY_GEN. If they are provided they must be CKO_SECRET_KEY and CKK_AES otherwise we will return CKR_TEMPLATE_INCONSISTENT.

CKA_VALUE_LEN is required in the template. Without it, we cannot know which key size to generate. Thus you need to provide 16, 24, or 32 as a value. CKR_TEMPLATE_INCOMPLETE will be returned if it is missing. CKR_ATTRIBUTE_VALUE_INVALID will be returned if it is not a CK_ULONG or the wrong value.

CKR_TEMPLATE_INCOMPLETE will in this case (CKM_AES_KEY_GEN) only be returned if the CKA_VALUE_LEN is missing.

CKR_ATTRIBUTE_VALUE_INVALID will only be returned if CKA_VALUE_LEN is not a CK_ULONG, if CKA_CHECK_VALUE is provided with a no-value (0 length) entry, or if CKA_VALUE_LEN is not equal to 16, 24, or 32.

**Comment by dengert** [comment]
You original said: "I get error CKR_TEMPLATE_INCOMPLETE while calling function C_GenerateKey() on Windows platform. **However, same code works on Linux platform.**"

You also said: "I am using cygwin on Windows machine to compile and run my program."

That sounds more like 32/64 problem, cygwin problem, a compiler problem, uninitialized variable, header file problem or different libraries.  You could compile it yourself, or report problem to @jariq who put together the Windows version use VS from a tar file which should be the current version of SoftHSM2.  Ask for a debug version so you can use GDB or other debugger.

**Comment by ramesh23gupta** [comment]
Thanks a lot to all of you for your valuable feedback.

After enabling logging on Windows and using "Visual Studio Command Prompt", it seems that the error is coming from below location:

**..\..\src\lib\SoftHSM.cpp(6905): CKA_VALUE_LEN does not have the size of CK_ULONG** 

CK_RV SoftHSM::generateAES():
                        case CKA_VALUE_LEN:
                                if (pTemplate[i].ulValueLen != sizeof(CK_ULONG))
                                {
                                        INFO_MSG("CKA_VALUE_LEN does not have the size of CK_ULONG");
                                        return **CKR_ATTRIBUTE_VALUE_INVALID**;
                                }

(Reference: my second program above with only CKA_VALUE_LEN attribute)

**Some diagnostic information obtained on Windows:**
**sizeof(CK_ULONG) = 4**, **sizeof(unsigned long int) = 4**, sizeof(value_len) = 4
value_len = 32, *aes_template[0].pValue = 32
aes_template[0].ulValueLen = 4

**Some diagnostic information obtained on Linux (I have build the library: libsofthsm2.so):**
**sizeof(CK_ULONG) = 8**, **sizeof(unsigned long int) = 8**, sizeof(value_len) = 8
value_len = 32, *aes_template[0].pValue = 32
aes_template[0].ulValueLen = 8

I am using library: **softhsm2-x64.dll** (Got it from from https://github.com/disig/SoftHSM2-for-Windows)
Windows edition: Windows Server 2008 R2 Standard (Service Pack 1)
System:
Processor: Intel(R) Xeon(R) CPU ...
Sytem type: 64-bit Operating System.

**Comment by ramesh23gupta** [comment]
Hi All,

I have complied my application on Windows using 32 bit and 64 bit SoftHSM library.
My application works for 32 bit library but fails for 64 bit library.
Please see function create_aes() of my application and outputs below.

For 64 bit case the error is coming from
..\..\src\lib\SoftHSM.cpp(6905): CKA_VALUE_LEN does not have the size of CK_ULONG

It seems that the softhsm2-x64.dll expects CK_ULONG to be of size 8 bytes but the application on VS x64 Win64 is showing sizeof(CK_ULONG) = 4.
Note that sizeof(crt_aes_template) = 24 in case of 64 bit and sizeof(crt_aes_template) = 12 in case of 32 bit.

typedef struct CK_ATTRIBUTE {
  CK_ATTRIBUTE_TYPE type;   // typedef CK_ULONG CK_ATTRIBUTE_TYPE; 
  CK_VOID_PTR pValue;	// typedef void  CK_PTR   CK_VOID_PTR;  (CK_PTR == *) 
  CK_ULONG ulValueLen;
} CK_ATTRIBUTE;

It seems to me a data type size miss match in my 64 bit application and in library softhsm2-x64.dll
How can I ensure that my application consider 8 bytes for CK_ULONG?

------------------------
CK_RV create_aes( CK_SESSION_HANDLE session, CK_OBJECT_HANDLE_PTR hkey)
{
    CK_RV                rc;
    CK_BBOOL truevalue = CK_TRUE;
    CK_BBOOL falsevalue = CK_FALSE;
    CK_MECHANISM mechanism = { CKM_AES_KEY_GEN, NULL_PTR, 0 };
    CK_ULONG value_len = 32;//key size in bytes
    CK_RV  (*pFunc)();

    CK_ATTRIBUTE crt_aes_template[] = {
	{CKA_VALUE_LEN, &value_len, sizeof(value_len)}
    };

   printf ("\ncreate_aes() entered.");
   printf ("\nsizeof(CK_ULONG) = %d, sizeof(unsigned long int) = %d\n",sizeof(CK_ULONG), sizeof(unsigned long int));
   printf ("sizeof(crt_aes_template) = %d\n", sizeof(crt_aes_template));
   printf ("&crt_aes_template = 0x%p\n", &crt_aes_template[0]);
   printf ("&truevalue = 0x%p\n", &truevalue);
   printf ("&falsevalue = 0x%p\n", &falsevalue);
   printf ("crt_aes_template[0].ulValueLen = %d\n", crt_aes_template[0].ulValueLen);
   printf ("sizeof(crt_aes_template[0].ulValueLen) = %d\n", sizeof(crt_aes_template[0].ulValueLen));
   printf ("crt_aes_template[0].pValue = 0x%p\n", crt_aes_template[0].pValue);
   printf ("&value_len = 0x%p\n", &value_len);
   printf ("*crt_aes_template[0].pValue = %d\n", *(CK_ULONG *)crt_aes_template[0].pValue);

   pFunc = (CK_RV (*)())GetProcAddress(d,"C_GenerateKey");
   if (pFunc == NULL ) {
      printf("C_GenerateKey() not found in module\n");
      return !CKR_OK;
   }

   printf ("\n\tCalling C_GenerateKey()...");
   rc = pFunc(session, &mechanism, crt_aes_template, 1, hkey);
   if (rc != CKR_OK) {
      printf("\n\tC_GenerateKey returned Error: %d (0x%0x) ", rc, rc);
      if (rc == CKR_ATTRIBUTE_VALUE_INVALID) {
	      printf ("CKR_ATTRIBUTE_VALUE_INVALID \n");
      }
      *hkey = CK_INVALID_HANDLE;
   }
   printf("\nKey handle = %u\n",*hkey);
   
   return CKR_OK;
}

**-----Output on Visual Studio Command Prompt (2010): 32 bit-----**

D:\guptar>cl -c -Zi demo.c
D:\guptar>link /debug demo.obj
d:\guptar>file demo.exe
demo.exe: PE32 executable (console) Intel 80386, for MS Windows
d:\guptar>demo.exe
Getting the PKCS11 function list...
        Library location: **D:\guptar\softhsm2.dll**
Initializing the PKCS11 environment...

start_session() entered.
        flags = 6
        slotId = 1880128118
        Calling C_OpenSession()...

login() entered.
        Calling C_Login()...

create_aes() entered.
**sizeof(CK_ULONG) = 4,** sizeof(unsigned long int) = 4
**sizeof(crt_aes_template) = 12**
&crt_aes_template = 0x0022F6E8
&truevalue = 0x0022F6F7
&falsevalue = 0x0022F6DB
crt_aes_template[0].ulValueLen = 4
sizeof(crt_aes_template[0].ulValueLen) = 4
crt_aes_template[0].pValue = 0x0022F6F8
&value_len = 0x0022F6F8
*crt_aes_template[0].pValue = 32

        **Calling C_GenerateKey()...
Key handle = 2**

destroy_aes() entered.
        Destroying AES key.
                Key handle: 2
                Calling C_DestroyObject()...

logout() entered.
        Calling C_Logout()...

end_session() entered.
        Calling C_CloseSession()...
Test completed successfully!

**------Output on Visual Studio x64 Win64 Command Prompt (2010): 64 bit-------**

D:\guptar>cl -c -Zi demo.c
D:\guptar>link /debug demo.obj
D:\guptar>file demo.exe
demo.exe: PE32+ executable (console) x86-64, for MS Windows
D:\guptar>demo.exe
Getting the PKCS11 function list...
        Library location: **D:\guptar\softhsm2-x64.dll**
Initializing the PKCS11 environment...

start_session() entered.
        flags = 6
        slotId = 1880128118
        Calling C_OpenSession()...

login() entered.
        Calling C_Login()...

create_aes() entered.
**sizeof(CK_ULONG) = 4,** sizeof(unsigned long int) = 4
**sizeof(crt_aes_template) = 24**
&crt_aes_template = 0x00000000001DF9C8
&truevalue = 0x00000000001DF9C4
&falsevalue = 0x00000000001DF9F8
crt_aes_template[0].ulValueLen = 4
sizeof(crt_aes_template[0].ulValueLen) = 4
crt_aes_template[0].pValue = 0x00000000001DF9C0
&value_len = 0x00000000001DF9C0
*crt_aes_template[0].pValue = 32

        **Calling C_GenerateKey()...
        C_GenerateKey returned Error: 19 (0x13) CKR_ATTRIBUTE_VALUE_INVALID  
Key handle = 0**

destroy_aes() entered.
        Destroying AES key.
                Key handle: 0
                Calling C_DestroyObject()...
   C_DestroyObject #1 returned: HSM operation error: 130 (0x82) CKR_OBJECT_HANDLE_INVALID

logout() entered.
        Calling C_Logout()...

end_session() entered.
        Calling C_CloseSession()...
Test completed successfully!
------------------------

**Comment by dengert** [comment]
Since CK_ULONG is normally defined as `unsigned int long`, This might help:
https://software.intel.com/en-us/articles/size-of-long-integer-type-on-different-architecture-and-os

Have you filed an issue here: https://github.com/disig/SoftHSM2-for-Windows/issues
How was it built? Was it built with long as 8 bytes? and why? 

Does the Cygwin compiler say long is 4 or 8 bytes? Are there any options?

PKCS\#11 says a CK_ULONG is at least 32 bits, so 4 bytes should work for all. 

The pkcs11.h was changes in SoftHSM a few days ago. Maybe the old version had a problem. 







https://github.com/opendnssec/SoftHSMv2/pull/412

**Comment by jariq** [comment]
Hi all and sorry for not noticing this issue sooner.

I'm publishing Windows builds at https://github.com/disig/SoftHSM2-for-Windows and I can confirm that **`CK_ULONG` is always 4 bytes long on both 32-bit and 64-bit Windows**. That's standard Windows behavior and it cannot be changed in any way known to me.

@ramesh23gupta could you please create [MCVE](2) console application that generates the key and replicates your problem? I believe such application would help us to spot and resolve your problem easier.

[1]: https://github.com/disig/SoftHSM2-for-Windows/blob/master/BUILDING.md
[2]: https://stackoverflow.com/help/mcve

**Comment by ramesh23gupta** [comment]
Hi Jariq,

Thanks for extending your help and support to resolve this issue.
Please find below the steps that I followed and my repro program.
Steps:
1) Download SoftHSM 2.4.0 MSI installer and install it in directory C:\SoftHSMv2.4

2) Open "Visual Studio x64 Win64 Command Prompt (2010)" and initialize the token.
C:\SoftHSMv2.4\bin>softhsm2-util.exe --init-token --slot 0 --label "My token 1"
User PIN: User123
Slot Id: 322656693

3) Change logging INFO to `DEBUG` in the config file.
D:\guptar>cat c:\SoftHSMv2.4\etc\softhsm2.conf
`#SoftHSM` v2 configuration file
directories.tokendir = C:\SoftHSMv2.4\var\softhsm2\tokens\
objectstore.backend = file
log.level = DEBUG
slots.removable = false

4) For 32-bit use library: "C:\\SoftHSMv2.4\\lib\\softhsm2.dll" in the repro program.

5) Open new "Visual Studio Command Prompt (2010)" and compile and excute the repro program.
D:\guptar>cl -c -Zi mcve.c
D:\guptar>link /debug mcve.obj
D:\guptar>mcve.exe
Loading library from location: C:\SoftHSMv2.4\lib\softhsm2.dll
Calling C_Initialize()
        slotId = 322656693
Calling C_OpenSession()
Calling C_Login()
Calling C_GenerateKey()
        Key handle = 2       <---------- This is expected behavior.
Calling C_DestroyObject()
Calling C_Logout()
Calling C_CloseSession()
Calling C_Finalize()
Test completed successfully!

6) For 64-bit use library: "C:\\SoftHSMv2.4\\lib\\softhsm2-x64.dll" in the repro program.

7) Open new "Visual Studio x64 Win64 Command Prompt (2010)" and excute the repro program.
D:\guptar>cl -c -Zi mcve.c
D:\guptar>link /debug mcve.obj
D:\guptar>mcve.exe
Loading library from location: C:\SoftHSMv2.4\lib\softhsm2-x64.dll
Calling C_Initialize()
        slotId = 322656693
Calling C_OpenSession()
Calling C_Login()
Calling C_GenerateKey()
C_GenerateKey returned Error: 19 (0x13)CKR_ATTRIBUTE_VALUE_INVALID   <---------- This is not expected.
        Key handle = 0
Calling C_DestroyObject()
C_DestroyObject returned: HSM operation error: 130 (0x82)
Calling C_Logout()
Calling C_CloseSession()
Calling C_Finalize()
Test completed successfully!

8) Got below SoftHSM logging message in the Windows Event Viewer
..\..\src\lib\SoftHSM.cpp(6905): CKA_VALUE_LEN does not have the size of CK_ULONG

9) Below is my repro program:
#include <stdio.h>
#include <windows.h>
#include "pkcs11.h"

//char 		  library_path[] = "C:\\SoftHSMv2.4\\lib\\softhsm2.dll";
char 		  library_path[] = "C:\\SoftHSMv2.4\\lib\\softhsm2-x64.dll";
char 		  user_pin[] = "User123";
CK_SLOT_ID        slotID = 322656693;

int main( int argc, char **argv )
{
	CK_C_INITIALIZE_ARGS	cinit_args;
	void    		*handle;
	CK_SESSION_HANDLE 	session;
	CK_RV        		rc, i;
	CK_RV  			(*pFunc)();
	CK_OBJECT_HANDLE	hkey;
	CK_ULONG		value_len = 32;//key size in bytes
	CK_MECHANISM mechanism = { CKM_AES_KEY_GEN, NULL_PTR, 0 };
	CK_ATTRIBUTE crt_aes_template[] = {
		{CKA_VALUE_LEN, &value_len, sizeof(value_len)}
	};
   
	hkey = CK_INVALID_HANDLE;
	handle = NULL;

	printf("Loading library from location: %s\n",library_path);
	handle = LoadLibrary(library_path);
	if ( handle == NULL ) {
		printf("Unable to load library %s.\n",library_path);
		printf("GetLastError = %d\n", GetLastError());
		return !CKR_OK;
	}

	memset( &cinit_args, 0x0, sizeof(cinit_args) );
	cinit_args.flags = CKF_OS_LOCKING_OK;

	printf("Calling C_Initialize()\n");
	pFunc = (CK_RV (*)())GetProcAddress(handle,"C_Initialize");
	if (pFunc == NULL ) {
		printf("C_Initialize() not found.\n");
		return !CKR_OK;
	}
	rc = pFunc(&cinit_args);
	if (rc != CKR_OK) {
		printf("C_Initialize returned: HSM operation error: %d (0x%0x)\n", rc, rc );
		return !CKR_OK;
	}

	session = CK_INVALID_HANDLE;
	printf("\tslotId = %d\n", slotID);
	
	printf("Calling C_OpenSession()\n");
	pFunc = (CK_RV (*)())GetProcAddress(handle,"C_OpenSession");
	if (pFunc == NULL ) {
		printf("C_OpenSession() not found\n");
	}
	rc = pFunc(slotID, (CKF_SERIAL_SESSION | CKF_RW_SESSION), NULL, NULL, &session);
	if (rc != CKR_OK) {
		printf("C_OpenSession returned: HSM operation error: %d (0x%0x)\n", rc, rc );
	}
	
	printf("Calling C_Login()\n");
	pFunc = (CK_RV (*)())GetProcAddress(handle,"C_Login");
	if (pFunc == NULL ) {
		printf("C_Login() not found\n");
	}
	rc = pFunc(session, CKU_USER, user_pin, strlen((char *)user_pin));
	if (rc != CKR_OK) {
		printf("C_Login returned: HSM operation error: %d (0x%0x)\n", rc, rc );
	}

	printf ("Calling C_GenerateKey()\n");
	pFunc = (CK_RV (*)())GetProcAddress(handle,"C_GenerateKey");
	if (pFunc == NULL ) {
		printf("C_GenerateKey() not found\n");
	}

	rc = pFunc(session, &mechanism, crt_aes_template, 1, &hkey);
	if (rc != CKR_OK) {
		printf("C_GenerateKey returned Error: %d (0x%0x)", rc, rc);
		if (rc == CKR_ATTRIBUTE_VALUE_INVALID) {
			printf ("CKR_ATTRIBUTE_VALUE_INVALID \n");
		}
	}
	printf("\tKey handle = %u\n",hkey);

	printf ("Calling C_DestroyObject()\n");
	pFunc = (CK_RV (*)())GetProcAddress(handle,"C_DestroyObject");
	if (pFunc == NULL ) {
		printf("C_DestroyObject() not found in module \n");
	}
	rc = pFunc(session, hkey);
	if (rc != CKR_OK) {
		printf("C_DestroyObject returned: HSM operation error: %d (0x%0x)\n", rc, rc );
	}

	printf("Calling C_Logout()\n");
	pFunc = (CK_RV (*)())GetProcAddress(handle,"C_Logout");
	if (pFunc == NULL ) {
		printf("C_Logout() not found\n");
	}
	rc = pFunc(session);
	if (rc != CKR_OK) {
		printf("C_Logout returned: HSM operation error: %d (0x%0x)\n", rc, rc );
	}

	printf("Calling C_CloseSession()\n");
	pFunc = (CK_RV (*)())GetProcAddress(handle,"C_CloseSession");
	if (pFunc == NULL ) {
		printf("C_CloseSession() not found\n");
	}
	rc = pFunc(session);
	if (rc != CKR_OK) {
		printf("C_CloseSession returned: HSM operation error: %d (0x%0x)\n", rc, rc );
	}

	printf("Calling C_Finalize()\n");
	pFunc = (CK_RV (*)())GetProcAddress(handle,"C_Finalize");
	if (pFunc == NULL ) {
		printf("C_Finalize() not found\n"); 
	}
	rc = pFunc( NULL );
	if (rc != CKR_OK) {
		printf("C_Initialize returned: HSM operation error: %d (0x%0x)\n", rc, rc );
		return !CKR_OK;
	}
	printf("Test completed successfully!\n");

	return CKR_OK;
}

**Comment by ramesh23gupta** [comment]
Hi  jariq,

Thanks for working on my sample program code.
I compared the header files in my setup and found that there was problem with them.
I made the changes into them as per the latest headers you pointed in your reply.
The above program works now for me.

I am very thankful to all of you for getting this issue resolve.

Thanks,
--Ramesh
