### ISSUE TITLE
Possible bug in unwrapped key bytes

### ISSUE THREAD

**Issue by jananguyen** [opendnssec/SoftHSMv2#414]
I am trying to retrieve the key bytes of a wrapped key. We are using IAIK with SoftHSM 2.4.0.

When I unwrap the key, the key object returned but when we get the key bytes, I get null.

Key template has been initialized with “sensitive=false” and below code works find with the Thales HSM appliance, but not with SoftHSM.

    long CKM_AES_KEY_WRAP = 0x00002109L;
         Mechanism wrappingMechanism = new Mechanism(CKM_AES_KEY_WRAP);
        InitializationVectorParameters ivParam = new InitializationVectorParameters(iv);
        wrappingMechanism.setParameters(ivParam);
        AESSecretKey key = session.unwrapKey(wrappingMechanism, keyEncryptionKey, wrappedKey, keyTemplate);
    byte[] plaintextkey = key.getValue().getByteArrayValue();
    
Error I'm getting:
 (plaintextkey is null)

Any ideas or workaround to get this to work?

**Comment by bellgrim** [comment]
From PKCS#11:

> Cannot be revealed if object has its CKA_SENSITIVE attribute set to CK_TRUE or its CKA_EXTRACTABLE attribute set to CK_FALSE.

What value do you have on CKA_EXTRACTABLE?

**Comment by jananguyen** [comment]
Hi Richard,

The CKA_EXTRACTABLE is set to false:

  // sensitive means keep key material on HSM side unless explicitly
extracted

USER_AES256_KEY_SOFTHSM.getSensitive().setBooleanValue(Boolean.TRUE);

        // this needs to be set in order to make key wrappable

USER_AES256_KEY_SOFTHSM.getExtractable().setBooleanValue(Boolean.FALSE);

**Comment by jananguyen** [comment]
So look like the issue got resolved once I set CKA_EXTRACTABLE to TRUE.

Thank you, I will close out this bug.
