### ISSUE TITLE
SoftHSM + engine_pkcs11 + openssl fails with EC keys when compiled with openssl 1.1.1

### ISSUE THREAD

**Issue by parasssh** [opendnssec/SoftHSMv2#417]
See https://github.com/OpenSC/libp11/issues/249 for details. 
The issue is that when SoftHSM and libp11 is compiled with openssl-1.1.1, trying to access EC keys on the SoftHSM via openssl engine fails. But when compiled with openssl-1.0.2p, issue is not seen. 

Opened a issue here since I am not sure if this will be a bug with openssl or opensc or softhsm

**Comment by bellgrim** [comment]
Was this issue resolved with the closed OpenSC issue and #418?
