### ISSUE TITLE
brute force login 

### ISSUE THREAD

**Issue by daviddanielzivi** [opendnssec/SoftHSMv2#421]
I've seen that the SoftHsm allow endless retries on login operation both for SO (security officer) and for normal user. The PKCS#11 requires an ability to lock both SO and normal user i.e. setting token flags to CKF_USER_PIN_LOCKED and CKF_SO_PIN_LOCKED.
Does someone is aware of this behavior or plan to fix it ? 
Thanks

**Comment by jariq** [comment]
Take a look at issue https://github.com/opendnssec/SoftHSMv2/issues/399.

**Comment by daviddanielzivi** [comment]
thanks for the explanation
