### ISSUE TITLE
multiple users in softhsm

### ISSUE THREAD

**Issue by daviddanielzivi** [opendnssec/SoftHSMv2#422]
Hi,
Does SoftHsm support multiple users ? I'd like to have SoftHsm as a server that concurrent clients connect to it. For that I thought that every client will belong to different user. Does it supported ? 
thanks
david

**Comment by bellgrim** [comment]
SoftHSM only supports the basic normal user and SO user. Also, the authorization model in PKCS#11 is not per object but per token. It would thus be one token per user.
