### ISSUE TITLE
SoftHSMv2 is unable to handle multithreading with more than 10 threads

### ISSUE THREAD

**Issue by pramodrj07** [opendnssec/SoftHSMv2#426]
Hi All,

I have a java application which calls the softhsmv2 for it's crypto operations. In have observed that if the i create to threads more than 10, I am getting the below error. For threads below 10, it works perfectly fine. I just want to know if this is the expected behavior? Or is there any fix for the same?

Error 

Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
	at sun.security.pkcs11.wrapper.PKCS11.C_SignFinal(Native Method)
	at sun.security.pkcs11.P11Signature.engineSign(P11Signature.java:553)

**Comment by bellgrim** [comment]
There is no set limit in SoftHSM and no known issues.

Do you have any relevant logs from SoftHSM?

How are the threads using SoftHSM? Are you only using one session per thread?

**Comment by pramodrj07** [comment]
Great I verified there were multiple session. I have resolved this issue Thanks @bellgrim
