### ISSUE TITLE
Softhsm2 only supports up to 31chars PIN

### ISSUE THREAD

**Issue by michalmedvecky** [opendnssec/SoftHSMv2#428]
I'm migrating my app stack from softhsm1 to softhsm2 and realized this weird issue: Any PIN longer than 31 characters results in incorrect behavior:

    pass='This_is_32_character_long_string'
    rm -fr /var/lib/softhsm/tokens/
    mkdir /var/lib/softhsm/tokens/
    softhsm2-util --slot 0 --init-token --label something --pin "$pass" --so-pin whatever --id FB
    softhsm2-util --token something --import /tmp/0.key.pk8 --label something --pin "$pass" --id FB
    p11tool --login --list-privkeys "pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project" --set-pin=$pass

Results:

    # ./test.sh
    The token has been initialized.
    
    Found slot 2058548990 with matching token label.
     
    The key pair has been imported.
    
    *** Only few tries left before locking!
    *** Wrong PIN has been provided!
    Token 'something' with URL 'pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=d206bc0a7ab2f6fe;token=something' requires user PIN
    Cannot continue with a wrong password in the environment.

If the PIN is 31 or less (down to 4), works as expected.

According to STDIN, the pin should be 4 to 255 characters, so I would expect this to work.

Tried with Ubuntu 18.04 softhsm (2.2.0) and latest master, compiled from source (on Ubuntu 18.04)

**Comment by rijswijk** [comment]
SoftHSM v2 (and as far as I know, this also goes for v1) does not put a limit on the maximum length of the PIN or passphrase used for the user or SO. I see from the PKCS #11 URI that you are probably using GNUTLS, could this be a limitation that GNUTLS imposes?

**Comment by michalmedvecky** [comment]
Hard to say; I'm not that educated so I could easily dig into gnutls.

Anyway, I have a golang application, which uses `/usr/lib/softhsm/libsofthsm2.so` for interacting with softhsm; this app is not linked to gnutls and fails to interact with >31char-pin protected token too.

**Comment by rijswijk** [comment]
If you look for MAX_PIN_LEN in the SoftHSM v2 source code, you will see that it is defined to be 255 bytes (not characters, due to UTF-8 encoding) in all of the code, this limitation of 31 characters sounds very odd. How did you initialise the token? Through softhsm2-util? For verification I have just re-run the SoftHSM v2 test suite and added an explicit test case with a 50 character PIN; that works fine on Ubuntu 18.04

**Comment by michalmedvecky** [comment]
You can see that in the snippet above:

    softhsm2-util --slot 0 --init-token --label something --pin "$pass" --so-pin whatever --id FB

**Comment by rijswijk** [comment]
The output of your test suggests that softhsm2-util successfully logs in with the PIN that is provided, so it appears that the issue somehow occurs in p11tool.

**Comment by michalmedvecky** [comment]
Hmm, any other suggestion how to debug this issue?

**Comment by rijswijk** [comment]
If you build SoftHSM from source, you could put some debug print statements in the code for C_Login and see what p11tool supplies as PIN, to verify if it somehow truncates the PIN before passing it to C_Login.

**Comment by michalmedvecky** [comment]
So I tried, C_Login gets the full pin...

**Comment by rijswijk** [comment]
Did you also check what the value is passed for the PIN length by any chance? It would be good to know both.

**Comment by michalmedvecky** [comment]
Nov 16 10:32:31 test.com softhsm2-util: SoftHSM.cpp(1392): Pin: This_is_32_character_long_stringxxxxxxxxxxxxxxxxxx
    Nov 16 10:32:31 test.com softhsm2-util: SoftHSM.cpp(1393): Length: 50

**Comment by rijswijk** [comment]
I've written a small test program that works on Ubuntu 18.04. If I used softhsm2-util to initialize a token with your test PIN and then run the program, it works fine. Can you give it a try? If this test program works, then the bug is definitely in p11tool.

[test-p11.tar.gz](https://github.com/opendnssec/SoftHSMv2/files/2589459/test-p11.tar.gz)

**Comment by michalmedvecky** [comment]
Sorry, for now I went with 31char password, but will definitely come back to this one day.
