### ISSUE TITLE
make p11test gives fatal error 

### ISSUE THREAD

**Issue by antoineVa** [opendnssec/SoftHSMv2#431]
Hi ! 

I'm trying to verify my installation of SoftHSM with the tests given in `src/lib/test/`
I successfully compiled and installed SoftHSM from the sources (at least I think, since `softhsm2-util --show slots` is giving me the expected informations)

```
[ENVIRONMENT]
OS : CentOS 7.2-1511 (64 bits)
SoftHSMv2 : 2.5.0
```

When trying to execute : 
`make p11test`

I get the following result : 
```
depbase=`echo p11test.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../../..  -I./.. -I./../common -I./../pkcs11    -g -O2 -Wall -Wextra -std=c++11 -fvisibility=hidden -MT p11test.o -MD -MP -MF $depbase.Tpo -c -o p11test.o p11test.cpp &&\
mv -f $depbase.Tpo $depbase.Po
p11test.cpp:33:52: fatal error: cppunit/extensions/TestFactoryRegistry.h : No such file or directory 
#include <cppunit/extensions/TestFactoryRegistry.h>
                                                    ^
compilation terminée.
make: *** [p11test.o] Erreur 1
```

I used this to test my previous installation of SoftHSM (which was 2.1.0 if I remember correctly) has it changed ?

Thanks,

Antoine

**Comment by bellgrim** [comment]
You are missing the CppUnit header files. Install them and run the configure script again. Check the output from the configure script for further information.

**Comment by antoineVa** [comment]
Thanks,
I needed to install the cppunit-devel package in CentOS, which made me overcome the fatal error, but it seems that cppunit 1.14 is required (right ?) which isn't available from repositories in CentOS 7.
I'll probably need to build cppunit 1.14 from sources.

**Comment by bellgrim** [comment]
No, cppunit 1.14 should not be required. 1.13 should also work.
