### ISSUE TITLE
Portability (macOS / Windows) - locating the provider library

### ISSUE THREAD

**Issue by Lekensteyn** [opendnssec/SoftHSMv2#433]
SoftHSM is a great tool for testing PKCS #11 functionality (it is used for example in the test suite for GnuTLS and I plan to use it for Wireshark as well). My goal is to discover `softhsm2-util` and the provider library such that it can be used in test suites for some popular platforms (macOS, Linux, Windows).

The main questions:
- What is the recommended way to install SoftHSM on these platforms? Clear for Linux, not so clear for Windows.
- How should applications locate the provider library? On Linux (and macOS with brew) the p11-kit package provides autodiscovery, what about Windows?

A survey of platforms:

- Linux:
  - Generally installed as /usr/lib/softhsm/libsofthsm2.so
  - Ubuntu / Debian install /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so (with the above path being a symlink to this) since [2.4.0-0.1](https://salsa.debian.org/debian/softhsm2/commit/d0021bb487e1fb22d54c843a81caf1ff333c3f7e).
- macOS package via Homebrew (https://formulae.brew.sh/formula/softhsm):
  - Pretty standard configure + make: https://github.com/Homebrew/homebrew-core/blob/master/Formula/softhsm.rb
  - Prebuilt package: https://bintray.com/homebrew/bottles/softhsm
  - **Question**: the provider is installed as .../lib/softhsm/**libsofthsm2.so**. Shouldn't it be called `libsofthsm2.dylib`?
- Windows:
  - Instructions in https://github.com/opendnssec/SoftHSMv2/blob/develop/WIN32-NOTES.md
  - Separate build instructions and a prebuilt zip/installer (by @disig): https://github.com/disig/SoftHSM2-for-Windows (previous request for integration with main repo: https://github.com/disig/SoftHSM2-for-Windows/issues/1).
  - @disig's MSI installer creates `C:\SoftHSM2\lib\softhsm2-x64.dll` and `C:\SoftHSM2\lib\softhsm2.dll` (and puts the lib dir in PATH). `C:\SoftHSM2\bin` contains `softhsm2-util.exe` (not in PATH).
  - Following WIN32-NOTES.md, `C:\build\bin\SoftHSMv2-x64` will contain both `softhsm2.dll` and `softhsm2-util.exe`. (Likewise for `SoftHSMv2-x86`)

**Comment by bellgrim** [comment]
In general, I would say that you should use the binaries available for your OS distribution. But that depends on how updated they are and how important it is that you have the latest features and bug fixes.

p11-kit is the only autodiscovery tool that I know about and is supported by SoftHSM. Usually, you have to manually configure your application with the correct P11 provider.

See my comment on .dylib vs. .so: https://github.com/opendnssec/SoftHSMv2/issues/353#issuecomment-366784750

**Comment by Lekensteyn** [comment]
> In general, I would say that you should use the binaries available for your OS distribution.

True for Linux distributions, but what what about Windows? Who is the "official" distributor for this platform? (Is there a standard path to look for softhsm2-util and the provider dll?)

> See my comment on .dylib vs. .so: https://github.com/opendnssec/SoftHSMv2/issues/353#issuecomment-366784750

Thanks, I did not know this (not a macOS user). It looks like p11-kit 0.23.14 does the same thing: .../lib/pkcs11/p11-kit-client.so

**Comment by jariq** [comment]
Why do you need to discover `softhsm2-util`?

**Comment by jariq** [comment]
I see. Have you considered using `C_Initialize` function instead of `softhsm2-util` application?

This is how I use SoftHSM2 to test [Pkcs11Interop.X509Store][0] project:
- I'm [distributing][1] `softhsm2.conf`, `softhsm2.dll` and `softhsm2-x64.dll` with my tests. This gives me total control over the SoftHSM2 version I'm testing with and I can also be 100% sure I won't mess with any SoftHSM2 installation performed by the user.
- Before the test are executed I'm programmatically initializing two tokens and importing all the keys and other objects I need for testing. See [`SoftHsm2Manager` class][2] for more details.

Would something like this work for you?

[0]: https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/
[1]: https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/tree/master/src/Pkcs11Interop.X509Store.Tests/SoftHsm2
[2]: https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/blob/master/src/Pkcs11Interop.X509Store.Tests/SoftHsm2/SoftHsm2Manager.cs

**Comment by Lekensteyn** [comment]
Calling `C_Initialize` directly might be challenging as the application under test only reads keys while the tests are executed from Python. Calling external processes (like softhsm2-util) is fine though. I also tried `p11tool` (part of GnuTLS), but as no slot is available it refuses to create a token. So softhsm2-util it is :)

My current approach to locate the provider is:
- Locate softhsm2-util in `%PATH%;C:\SoftHSM\bin`
- If found, assume libsofthsm2-x64.dll and libsofthsm2.dll in ..\lib\.
- (For Linux/macOS, assume libsofthsm2.dll in ../lib/softhsm/ instead).

...and apparently I have not bothered to check the documentation enough. The [download page][1] refers to @disig's installer for Windows, so I guess it can be considered "official". And based on your project and the different suggested layout in WIN32-NOTES.md, I suppose there is no standard way for an arbitrary program to locate SoftHSM on Windows (other than the installer).

I think that this issue can be marked as resolved, unless you have more input? Thanks for the replies so far!

 [1]: https://www.opendnssec.org/download/packages/
