### ISSUE TITLE
undefined symbol: _ZN17BotanEDPrivateKeyD1Ev (build with botan, without EDDSA)

### ISSUE THREAD

**Issue by Lekensteyn** [opendnssec/SoftHSMv2#435]
Building 2.3.0-153-gf3b8a96 (actually, https://github.com/opendnssec/SoftHSMv2/pull/434) with botan on Ubuntu 14.04 results in an unusable library. (The reason for me to try to build such on such an outdated Ubuntu version is because I was investigating an issue in Travis CI.)

This is possibly a regression due to commit 27515558969c38cfef9c6a6999498807a7492b8d by @fxdupont which does not guard all users of `BotanEDPrivateKey` (see for example src/lib/crypto/BotanEDKeyPair.cpp).

To reproduce:
```
printf 'directories.tokendir = %s\nobjectstore.backend = file\n' "$HOME/tokens" > ~/s.conf
mkdir ~/tokens
mkdir build && cd build
cmake -GNinja -DWITH_CRYPTO_BACKEND=botan -DDISABLE_NON_PAGED_MEMORY=ON -DENABLE_GOST=OFF .. -DENABLE_ECC=OFF -DCMAKE_INSTALL_PREFIX=$HOME/prefix -DENABLE_P11_KIT=OFF
ninja
SOFTHSM2_CONF=/home/user/s.conf src/bin/util/softhsm2-util --module src/lib/libsofthsm2.so --show-slots
```
Output:
```
ERROR: Could not load the PKCS#11 library/module: src/lib/libsofthsm2.so: undefined symbol: _ZN17BotanEDPrivateKeyD1Ev
ERROR: Please check log files for additional information.
```

To rule out an issue with CMake, I reproduced it with autotools as well:
```
autoreconf -vifs
mkdir au && cd au
../configure --with-crypto-backend=botan --disable-ecc --disable-gost --disable-eddsa
make -j10
SOFTHSM2_CONF=$HOME/s.conf src/bin/util/softhsm2-util --module src/lib/.libs/libsofthsm2.so --show-slots
# installing it makes no difference:
#sudo mkdir /usr/local/lib/softhsm
#sudo ln -sv $PWD/src/lib/.libs/libsofthsm2.so /usr/local/lib/softhsm/
#SOFTHSM2_CONF=$HOME/s.conf src/bin/util/softhsm2-util --show-slots
```

Environment details:
- OS: Ubuntu 14.04 Trusty (64-bit)
- libbotan1.10-dev 1.10.5-1+deb7u1ubuntu0.14.04.1

**Comment by fxdupont** [comment]
BTW Botan 1.x will be End of Live in 19 days (2018-12-31)...

Nevertheless please propose a patch adding the missing guard.

**Comment by Lekensteyn** [comment]
See #436 for a proposed patch that adds guards.
