### ISSUE TITLE
ECDSA multipart

### ISSUE THREAD

**Issue by TomerAvi** [opendnssec/SoftHSMv2#437]
HI,

I saw in SoftHsm.cpp that AsymSignInit using ECDSA mechanism does not support multipart signing/
Why ECDSA multi part is not supported?

Thanks
Tomer

**Comment by dengert** [comment]
PKCS\#11 2.40 Section 2.3.6  "ECDSA without hashing" says: "The ECDSA without hashing mechanism, denoted CKM_ECDSA, is a mechanism for **single-part signatures** and verification for ECDSA." with a footnote: "3 Input the entire raw digest. Internally, this will be truncated to the appropriate number of bits."

2.3.7 "ECDSA with SHA-1" is the only hash supported. For others the caller is expected to calculate the hash and use "ECDSA without hashing".
