### ISSUE TITLE
Performance poor in combination with other signing software

### ISSUE THREAD

**Issue by vigodeltoro** [opendnssec/SoftHSMv2#439]
Hi, 
I use SoftHSM for signing a zone with KnotDNS. If I sign without KnotHSM I got with multithreaded signing with 8 cores 7630 sig/s. If I use KnotDNS with Softhsm I got only 521 sigs/s. 
Same environment. Same hardware. 
I'm running the stuff on Kubernetes with an alpine 3.8 Container. Kernel Version is 3.10 ( Centos Base OS ). But the Kernel Version doesn't have impact. I verified this.

I use SoftHSM 2.5.0 .. with openssl .. 
Here is my configuration:

SoftHSM v2 configuration file

---
directories.tokendir = /var/lib/softhsm/tokens/
objectstore.backend = file

ERROR, WARNING, INFO, DEBUG
log.level = ERROR

If CKF_REMOVABLE_DEVICE flag should be set
slots.removable = false

---

Compile parameters are: ./configure --with-crypto-backend=openssl --enable-64bit --enable-static --enable-p11-kit

Maybe anybody have a suggestion for me, how to improve the performance ? Maybe to compile/configure to use multicore ? 

I made tests around 3 years ago with OpenDNSSEC and SoftHSM and I remember that with the ods-speedtest I got the possibility for multicore support.. but I don't know if it depends of SoftHSM or OpenDNSSEC.. 

thanks a lot 
regards

Christian

**Comment by rijswijk** [comment]
Hello Christian,

There may be several factors that influence the performance when using SoftHSM in combination with Knot to sign zones:

- Knot uses GNUTLS under the hood to access the PKCS #11 library, it may be that there is some shared lock in that code that limits performance.

- SoftHSM takes a number of security measures to protect sensitive data in memory, which means that SoftHSM has a lower performance than directly using a crypto library. This is a deliberate design choice, to protect, e.g. against memory snooping (inside or outside a virtual environment for example).

If you are looking for raw signing speed, you may want to use a crypto library directly. If, on the other hand, you want a reasonable measure of security even though key material is stored in software, then you are better off using SoftHSM.

Best regards,

Roland

> On 15 Jan 2019, at 11:56, Christian Petrasch <notifications@github.com> wrote:
> 
> Hi,
> I use SoftHSM for signing a zone with KnotDNS. If I sign without KnotHSM I got with multithreaded signing with 8 cores 7630 sig/s. If I use KnotDNS with Softhsm I got only 521 sigs/s.
> Same environment. Same hardware.
> I'm running the stuff on Kubernetes with an alpine 3.8 Container. Kernel Version is 3.10 ( Centos Base OS ). But the Kernel Version doesn't have impact. I verified this.
> 
> I use SoftHSM 2.5.0 .. with openssl ..
> Here is my configuration:
> 
> SoftHSM v2 configuration file
> 
> directories.tokendir = /var/lib/softhsm/tokens/
> objectstore.backend = file
> 
> ERROR, WARNING, INFO, DEBUG
> 
> log.level = ERROR
> 
> If CKF_REMOVABLE_DEVICE flag should be set
> 
> slots.removable = false
> 
> Compile parameters are: ./configure --with-crypto-backend=openssl --enable-64bit --enable-static --enable-p11-kit
> 
> Maybe anybody have a suggestion for me, how to improve the performance ? Maybe to compile/configure to use multicore ?
> 
> I made tests around 3 years ago with OpenDNSSEC and SoftHSM and I remember that with the ods-speedtest I got the possibility for multicore support.. but I don't know if it depends of SoftHSM or OpenDNSSEC..
> 
> thanks a lot
> regards
> 
> Christian
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- Roland M. van Rijswijk-Deij
-- NLnet Labs

**Comment by vigodeltoro** [comment]
Hi Roland, 

thanks a lot for your answer and for your explanation.. this answers my questions.
I expected that the measures for security are limiting the performance. I need the securiy for shure.. so I will deal with the design choices and the perfomance. 

With my issue I wanted to exclude, that I have done sth. wrong with my compile parameters or configuration.. 

Best regards

Christian
