### ISSUE TITLE
undefined reference to `RSA_set0_factors

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#448]
I'm in the process of upgrading from openssl 1.1.0h and SoftHSM 2.4.0 to openssl 1.1.1a and the latest develop version of SoftHSMv2 (2.5.0+). Openssl builds fine.  Configuring SoftHSMv2-develop is OK as well. However, when I come to do a make I  get the following errors:

softhsm2-keyconv-ossl.o: In function `save_rsa_pkcs8(char*, char*, key_material_t*)':
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:107: undefined reference to `RSA_set0_factors'
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:108: undefined reference to `RSA_set0_crt_params'
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:109: undefined reference to `RSA_set0_key'
softhsm2-keyconv-ossl.o: In function `save_dsa_pkcs8(char*, char*, key_material_t*)':
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:201: undefined reference to `DSA_set0_pqg'
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:202: undefined reference to `DSA_set0_key'
softhsm2-keyconv-ossl.o: In function `crypto_init()':
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:54: undefined reference to `OPENSSL_init_crypto'

Not sure what is going on

John

**Comment by rijswijk** [comment]
The functions that the linker fails to find are new since OpenSSL 1.1.0; the OpenSSL folks made some structures opaque so developers now need to use explicit getter/setter functions. SoftHSM has a compatibility layer for older versions of OpenSSL as suggested by the OpenSSL dev team, so in principle, it should compile with any OpenSSL version.

What is your compilation environment exactly? Because it almost looks like you are either a) compiling with headers of one OpenSSL version, but linking to a shared library of a different version or b) your platform-provided OpenSSL has these functions somehow turned off, or c) you have a hand-built OpenSSL and these functions were not enabled in the build.

Please also see [https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes) and look at OSSLComp.[ch] in the SoftHSM repository.

**Comment by johughes99** [comment]
It could be something like that.

I’m using Ubuntu 16.04 LTS.  I downloaded openssl-1.1.1a from the openssl web site.

I then did the usual
make
make test (to make sure working)
sudo make install.

I already had openssl-1-1.0h installed the first time I did it so the second time I went into the openssl-1.1.0h directory and did a sudo make uninstall (which did seem to remove a lot of stuff).

I then built softhsm with:
sh autogen.sh
./configure --enable-ecc --disable-gost -with-openssl=/usr/src/openssl-1.1.1.a
make

make then gave same errors.  So perhaps there are still some remnants of open-1.1.0h lying around. But sure how to remove them

**Comment by johughes99** [comment]
For completeness the errors are:

/bin/bash ../../../libtool  --tag=CXX   --mode=link g++  -g -O2 -Wall -Wextra -std=c++11 -fvisibility=hidden   -o softhsm2-keyconv softhsm2-keyconv.o base64.o softhsm2-keyconv-ossl.o ../../lib/crypto/OSSLComp.o  -L/usr/src/openssl-1.1.1a/lib -lcrypto -ldl
libtool: link: g++ -g -O2 -Wall -Wextra -std=c++11 -fvisibility=hidden -o softhsm2-keyconv softhsm2-keyconv.o base64.o softhsm2-keyconv-ossl.o ../../lib/crypto/OSSLComp.o  -L/usr/src/openssl-1.1.1a/lib -lcrypto -ldl
softhsm2-keyconv-ossl.o: In function `save_rsa_pkcs8(char*, char*, key_material_t*)':
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:107: undefined reference to `RSA_set0_factors'
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:108: undefined reference to `RSA_set0_crt_params'
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:109: undefined reference to `RSA_set0_key'
softhsm2-keyconv-ossl.o: In function `save_dsa_pkcs8(char*, char*, key_material_t*)':
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:201: undefined reference to `DSA_set0_pqg'
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:202: undefined reference to `DSA_set0_key'
softhsm2-keyconv-ossl.o: In function `crypto_init()':
/home/johughes/Downloads/SoftHSMv2-develop/src/bin/keyconv/softhsm2-keyconv-ossl.cpp:54: undefined reference to `OPENSSL_init_crypto'
collect2: error: ld returned 1 exit status
Makefile:515: recipe for target 'softhsm2-keyconv' failed

**Comment by rijswijk** [comment]
You should check:

- Your LD_LIBRARY_PATH (to make sure it's not sourcing libcrypto from somewhere else; it will use the first shared object it finds in the path)

- The symbols in libcrypto in /usr/src/openssl-1.1.1a/lib, to ensure that the symbols the linker is trying to find are actually there; if the symbols are not in that libcrypto that would explain the linker error, but not why the symbols aren't present (for AFAICS, these symbols should be in OpenSSL 1.1.1).

**Comment by johughes99** [comment]
I don't have LD_LIBRARY_PATH set in my environment. I have just checked that I only have two locations of libcrypto.so and libcrypto.a on my machine - either /usr/local/lib or /usr/src/openssl-1.1.1a

I checked for the missing symbols with nm - and they all appear to be present.

Bizarre

**Comment by rijswijk** [comment]
Is /usr/local/lib in your ld.so.conf by any chance? Anyway, you could try renaming the versions in /usr/local/lib to be sure it is linking against whatever is in /usr/src/openssl-1.1.1a/lib.

W.r.t. the symbols: did you check if the symbols were public as well? That is the only other thing I can think of.

**Comment by johughes99** [comment]
I added in /usr/local/lib into ld.so.conf - and then still got link error

I then deleted the libcrypto.so and libcrypto.a files in both /usr/local/lib and /usr/src/openssl-1.1.1a folders.

Then I rebuilt openssl from scratch. But still got the same link error in making softhsm.

I checked libcrypto.so and the symbols are public.  See a sample output below for 3 of the symbols


00000000001c80d0 T RSA_set0_crt_params
00000000001c8060 T RSA_set0_factors
00000000001c7fd0 T RSA_set0_key

**Comment by rijswijk** [comment]
That is weird indeed, this should just work. I'm afraid I don't have time to reproduce this issue for you at the moment, can you perhaps try this on either a fresh machine or on a different OS as well? (e.g. 18.04LTS)

> On 25 Feb 2019, at 14:51, johughes99 <notifications@github.com> wrote:
> 
> I added in /usr/local/lib into ld.so.conf - and then still got link error
> 
> I then deleted the libcrypto.so and libcrypto.a files in both /usr/local/lib and /usr/src/openssl-1.1.1a folders.
> 
> Then I rebuilt openssl from scratch. But still got the same link error in making softhsm.
> 
> I checked libcrypto.so and the symbols are public. See a sample output below for 3 of the symbols
> 
> 00000000001c80d0 T RSA_set0_crt_params
> 00000000001c8060 T RSA_set0_factors
> 00000000001c7fd0 T RSA_set0_key
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- Roland M. van Rijswijk-Deij
-- NLnet Labs

**Comment by johughes99** [comment]
OK - I will do it on 18.04LTS.  Im working in a VirtualBox environment right now - so I have one set up already

**Comment by rijswijk** [comment]
One more thing: are you sure it's not trying to link to the system-supplied shared library? Ubuntu 16.04 comes with OpenSSL 1.0.2, which does not have these symbols...

> On 25 Feb 2019, at 15:03, johughes99 <notifications@github.com> wrote:
> 
> OK - I will do it on 18.04LTS. Im working in a VirtualBox environment right now - so I have one set up already
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- Roland M. van Rijswijk-Deij
-- NLnet Labs

**Comment by johughes99** [comment]
How do i check this - or fix this problem.

So I installed openssl-1.1.1a and softhsmv2-develop on my 18.04LTS and it works fine!! The standard openssl on 18.04LTS was I think 1.1.0g (which I removed).  If we don’t solve this on 16.04LTS i guess I will have to move all my dev env to 18.04 (gulp)

**Comment by rijswijk** [comment]
The problem is that the linker tries to link with the first shared library it can find in the linker path (ld.so.conf, LD_LIBRARY_PATH). The path you provide to the configure script of SoftHSM is only a hint to where it can find OpenSSL, that is meant to be used in case OpenSSL is installed in a non-default location on the system. It doesn't force the build system to link with a specific library in any way, so if there is another library that the linker finds in its path configuration before it finds the one you point to, it will use that one.

One approach you could take is to use something like Docker to set up a virtual environment, if you specifically want to build with a particular version of OpenSSL. I am no expert in that I'm afraid, but I heard it should be pretty easy ;-)

Anyway, out of curiosity, is there a specific reason you want to build SoftHSM against OpenSSL 1.1.1?

**Comment by johughes99** [comment]
But there aren’t any libcrypto.* libraries on the system any more (other than 1.1.1a)  Unless they are lurking!:-)

I have a PKCS#11 compatibility tool. It was originally developed well over 12 years ago. I have slowly but surely been adding in lots more tests of various types and making it conform to PKCS#11 2.40. I'm using softhsmv2 as my "reference" library because I know it has been well tested.  Although using 2.4.0 previously I wanted to use that latest version of softhsmv2 as well as the latest version openssl. In due course I will report some of the minor issues I have found whilst doing the testing.

I was going to upgrade to 18.04LTS at some point anyway - this has just forced me to do it earlier. Its now just the pain to set up the dev env again.  I should have documented better what I did!

**Comment by rijswijk** [comment]
Glad to hear that it works now, any issues you run into and report are of course appreciated!

> On 25 Feb 2019, at 17:34, johughes99 <notifications@github.com> wrote:
> 
> But there aren’t any libcrypto.* libraries on the system any more (other than 1.1.1a) Unless they are lurking!:-)
> 
> I have a PKCS#11 compatibility tool. It was originally developed well over 12 years ago. I have slowly but surely been adding in lots more tests of various types and making it conform to PKCS#11 2.40. I'm using softhsmv2 as my "reference" library because I know it has been well tested. Although using 2.4.0 previously I wanted to use that latest version of softhsmv2 as well as the latest version openssl. In due course I will report some of the minor issues I have found whilst doing the testing.
> 
> I was going to upgrade to 18.04LTS at some point anyway - this has just forced me to do it earlier. Its now just the pain to set up the dev env again. I should have documented better what I did!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- Roland M. van Rijswijk-Deij
-- NLnet Labs

**Comment by johughes99** [comment]
Certianly will.  

Ive set up my dev env now - and starting to do soem TESTU01 testing again.  

For some reason the testing is a lot quicker. Im just wondering whether in openssl-1.1.1a Ubuntu 18.04 they have changed the RNG is so its a lot quicker.

One aside I noticed in softhsmv2 you could not open more than 4 current PKCS#11 sessions. In 2.5.0-develop this limit seems to have been removed and I'm seeing it is possible to open 8 sessions

**Comment by rijswijk** [comment]
W.r.t. the maximum number of open sessions: the maximum number of sessions has always been set to "CK_EFFECTIVELY_INFINITE" in SoftHSM v2 as far as I can tell, so I'm surprised you were not able to open more sessions. Did you experience SoftHSM from stopping you to do this, or did you experience errors?

> On 25 Feb 2019, at 21:08, johughes99 <notifications@github.com> wrote:
> 
> Certianly will.
> 
> Ive set up my dev env now - and starting to do soem TESTU01 testing again.
> 
> For some reason the testing is a lot quicker. Im just wondering whether in openssl-1.1.1a Ubuntu 18.04 they have changed the RNG is so its a lot quicker.
> 
> One aside I noticed in softhsmv2 you could not open more than 4 current PKCS#11 sessions. In 2.5.0-develop this limit seems to have been removed and I'm seeing it is possible to open 8 sessions
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- Roland M. van Rijswijk-Deij
-- NLnet Labs

**Comment by johughes99** [comment]
I just redid the test with 8 concurrent threads - and C_OpenSession did seem to provide a separate session for each one. SO not sure what was going on last time!

**Comment by Chia-hung-tw** [comment]
Hi,
I also have the same problem build softHSM2.5 on ubuntu 16.04.
I finally understand what goes on.
As @rijswijk mentioned ubuntu 16.04 has default openssl at /usr/lib/x86_64-linux-gnu/libcrypto.a,
which is version 1.0.2g. (by calling -lcrypto, gcc will find this path.)
1. Download openssl 1.1.1d from https://www.openssl.org/source/
2. Build openssl at path/to/openssl
(1) cd path/to/openssl
(2) ./config
(3) make
3. Specify the path by ./configure --with-openssl=path/to/openssl
However, it actually search path/to/openssl/lib.
So one has to 
(1) cd path/to/openssl
(2) mkdir lib
(3) cp lib*.* lib
4. Go back to SoftHSMv2
(1) ./configure --with-openssl=path/to/openssl
(2) make --> make check --> sudo make install

DONE!

**Comment by rijswijk** [comment]
Thanks for sharing this useful info @Chia-hung-tw

**Comment by ArtemShypotilov** [comment]
> Hi, I also have the same problem build softHSM2.5 on ubuntu 16.04. I finally understand what goes on. As [@rijswijk](https://github.com/rijswijk) mentioned ubuntu 16.04 has default openssl at /usr/lib/x86_64-linux-gnu/libcrypto.a, which is version 1.0.2g. (by calling -lcrypto, gcc will find this path.)
> 
>     1. Download openssl 1.1.1d from https://www.openssl.org/source/
> 
>     2. Build openssl at path/to/openssl
>        (1) cd path/to/openssl
>        (2) ./config
>        (3) make
> 
>     3. Specify the path by ./configure --with-openssl=path/to/openssl
>        However, it actually search path/to/openssl/lib.
>        So one has to
>        (1) cd path/to/openssl
>        (2) mkdir lib
>        (3) cp lib*.* lib
> 
>     4. Go back to SoftHSMv2
>        (1) ./configure --with-openssl=path/to/openssl
>        (2) make --> make check --> sudo make install
> 
> 
> DONE!

Thanks bro! Your instructions saved me quite some time!
