### ISSUE TITLE
CKO_SO C_Login always fails with CKR_SESSION_READ_ONLY_EXISTS

### ISSUE THREAD

**Issue by space88man** [opendnssec/SoftHSMv2#451]
With 2.5.0, SO logins are always failing with `CKR_SESSION_READ_ONLY_EXISTS`.

1. Init a brand new token
2. `p11tool --provider /usr/lib64/pkcs11/libsofthsm2.so --write --mark-trusted --load-certificate certificate.pem --label trustedcrt --so-login 'pkcs11:token=token0'`
3. Result:
```
21: C_Login
2019-03-05 14:38:51.832
[in] hSession = 0x2
[in] userType = CKU_SO
[in] pPin[ulPinLen] 000055d6fc47be30 / 5
    00000000  73 6F 70 69 6E                                   sopin           
Returned:  183 CKR_SESSION_READ_ONLY_EXISTS
```
4. The check for `sessionManager->haveROSession` in SoftHSM.cpp always seems to return true

**Comment by rijswijk** [comment]
What environment are you running this on? Do the SoftHSM unit tests report the same issue? (there are testcases that verify this behaviour)

**Comment by space88man** [comment]
Fedora 29, x86_64, v2.5.0 - distro package

**Comment by rijswijk** [comment]
did you build this package from source? if so, can you run the test set?

**Comment by space88man** [comment]
No - but here are the distro settings - 

```
./configure --with-openssl --enable-ecc --enable-eddsa --disable-gost --with-migrate --enable-visibility --with-p11-kit=/usr/share/p11-kit/modules/
```

**Comment by space88man** [comment]
When doing an SO C_Login this is what p11tool sees
```
13: C_OpenSession
2019-03-05 15:10:47.212
[in] slotID = 0x271566bf
[in] flags = 0x4
pApplication=(nil)
Notify=(nil)
[out] *phSession = 0x2
Returned:  0 CKR_OK

14: C_GetSessionInfo
2019-03-05 15:10:47.212
[in] hSession = 0x2
[out] pInfo: 
      slotID:                  655713983
      state:                  '           CKS_RO_PUBLIC_SESSION'
      flags:                   4
        CKF_SERIAL_SESSION               
      ulDeviceError:           0
Returned:  0 CKR_OK

15: C_Login
2019-03-05 15:10:49.180
[in] hSession = 0x2
[in] userType = CKU_SO
[in] pPin[ulPinLen] 000055a4ed767650 / 5
    00000000  73 6F 70 69 6E                                   sopin           
Returned:  183 CKR_SESSION_READ_ONLY_EXISTS
```

**Comment by space88man** [comment]
I'm closing this because it is an artifact of `p11tool`, it works with `pkcs11-tool`. The former may be doing too much and leaving sessions open.

**Comment by rijswijk** [comment]
OK, maybe you can open an issue with the ```p11tool``` folks, because this is not correct behaviour. Thanks for checking and closing the issue.

**Comment by space88man** [comment]
The difference I am seeing is 
pkcs11-tool
```
C_OpenSession
C_Login
 # and SO stuff works
```

p11tool does
```
C_OpenSession
C_CloseSession

C_OpenSession
C_GetSessionInfo <--- here sees CKS_RO_PUBLIC_SESSION
C_Login
# SO stuff fails
```

**Comment by rijswijk** [comment]
No, ```C_GetSessionInfo``` does not modify any internal state. What is likely that ```p11tool``` has another session open somewhere, that is an RO session, because otherwise SoftHSM should not report any open sessions.

**Comment by rijswijk** [comment]
Can you attach a full log of the interaction between ```p11tool``` and SoftHSM?

**Comment by space88man** [comment]
[logfile-bad.zip](https://github.com/opendnssec/SoftHSMv2/files/2929785/logfile-bad.zip)

**Comment by rijswijk** [comment]
Ah, that helps:

```
0x6 == CKS_RW_PUBLIC_SESSION | CKS_RW_SO_FUNCTIONS
0x4 == CKS_RW_SO_FUNCTIONS
```

It seems ```p11tool``` is opening the session without setting ```CKS_RW_PUBLIC_SESSION```, this is incorrect, as the SO may not be logged in in a read-only session, and SoftHSM correctly returns ```CKR_SESSIONS_READ_ONLY_EXISTS```.

**Comment by space88man** [comment]
Based on the test code  of https://github.com/opendnssec/SoftHSMv2/files/2926725/testissue.zip
this is a minimal reproducer which shows the issue.

```
   // this fails because the session is not RW when subsequently logging in as SO
    status = pkcs11->C_OpenSession(slotids[0], CKF_SERIAL_SESSION, NULL, NULL, &session);
    assert(!status);

    CK_SESSION_INFO info;
    printf("session info\n");
    status = pkcs11->C_GetSessionInfo(session, &info);
    assert(!status);

    printf("logging in\n");
    status = pkcs11->C_Login(session, CKU_SO, (unsigned char*) "sopin", strlen("sopin"));
    assert(!status);
    return 
```

**Comment by rijswijk** [comment]
The behaviour SoftHSM shows is correct given the code you list above, it should return an error when trying to log in the SO on a read-only session, as that PKCS #11 specification disallows this.

**Comment by space88man** [comment]
Thank you! I will follow up with gnutls...

**Comment by rijswijk** [comment]
FYI, here are the relevant screenshots from the PKCS #11 spec:

![screenshot 2019-03-05 at 08 59 48](https://user-images.githubusercontent.com/1721583/53789608-22b2e500-3f25-11e9-8d9a-720be96d7976.png)

![screenshot 2019-03-05 at 08 59 57](https://user-images.githubusercontent.com/1721583/53789625-28a8c600-3f25-11e9-8bb7-976d2cd3caa2.png)

**Comment by space88man** [comment]
Fixed in upstream GnuTLS
https://gitlab.com/gnutls/gnutls/issues/721

**Comment by rijswijk** [comment]
Thanks for reporting back, glad to see this got fixed!
