### ISSUE TITLE
ERROR: Could not load the SoftHSM configuration. ERROR: Please verify that the SoftHSM configuration is correct.

### ISSUE THREAD

**Issue by okbaz** [opendnssec/SoftHSMv2#457]
I compiled the library as the following:

```
export BOTAN_LIBS="-L/home/headless/share/Botan-2.0 -l:libbotan-2.0.so"
export BOTAN_CFLAGS="-I/home/headless/share/Botan-2.0/build/include"
./configure --with-crypto-backend=botan --host x86_64-pc-linux-gnu
```

When I run `export SOFTHSM_CONF=./softhsm.conf` and then `softhsm2-util --show-slots` for example I get the following error:

**ERROR: Could not load the SoftHSM configuration.
ERROR: Please verify that the SoftHSM configuration is correct.**

This is the content of the configuration file:

```
# SoftHSM configuration file
#
# Format:
# <Slot ID>:<Path to the token database>
#
# The given paths are just an indication to SoftHSM on where it should 
# store the information for each token.

0:/var/lib/softhsm/slot0.db

```

**Comment by rijswijk** [comment]
It looks like you're combining a SoftHSM v1 configuration for SoftHSM v2 code, please look at the documentation for information on the correct config file format.

> On 11 Mar 2019, at 15:30, okbaz <notifications@github.com> wrote:
> 
> I compiled the library as the following:
> 
> export BOTAN_LIBS="-L/home/headless/share/Botan-2.0 -l:libbotan-2.0.so"
> export BOTAN_CFLAGS="-I/home/headless/share/Botan-2.0/build/include"
> ./configure --with-crypto-backend=botan --host x86_64-pc-linux-gnu
> 
> When I run export SOFTHSM_CONF=./softhsm.conf and then softhsm2-util --show-slots for example I get the following error:
> 
> ERROR: Could not load the SoftHSM configuration.
> ERROR: Please verify that the SoftHSM configuration is correct.
> 
> This is the content of the configuration file:
> 
> # SoftHSM configuration file
> #
> # Format:
> # <Slot ID>:<Path to the token database>
> #
> # The given paths are just an indication to SoftHSM on where it should 
> # store the information for each token.
> 
> 0:/var/lib/softhsm/slot0.db
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- Roland M. van Rijswijk-Deij
-- NLnet Labs

**Comment by halderen** [comment]
Indeed, in fact the SOFTHSM_CONF environment variable is used by SoftHSM version 1 only, for SoftHSM version 2, this environment variable is SOFTHSM2_CONF.  In case your problem persist, please provide an exerpt from the system log (syslog).  This is the place where more information is logged by SoftHSM.
