### ISSUE TITLE
CKA_VALUE of CKO_DATA must be (re)writable 

### ISSUE THREAD

**Issue by alexyack** [opendnssec/SoftHSMv2#460]
https://github.com/opendnssec/SoftHSMv2/blob/6ad5e1a7aaa4674366e24503e53576cde5939924/src/lib/P11Objects.cpp#L355-L359

PKCS#11 2.40 standard assumes no restrictions to this field. 

> 4.5 Data objects
> 4.5.1 Definitions
> 
> This section defines the object class CKO_DATA for type CK_OBJECT_CLASS as used in the CKA_CLASS attribute of objects.
> 4.5.2 Overview
> 
> Data objects (object class CKO_DATA) hold information defined by an application. Other than providing access to it, Cryptoki does not attach any special meaning to a data object. The following table lists the attributes supported by data objects, in addition to the common attributes defined for this object class:
> 
> Table 17, Data Object Attributes
> 
> Attribute | Data type | Meaning
> -- | -- | --
> CKA_APPLICATION | RFC2279 string | Description of the application that manages   the object (default empty)
> CKA_OBJECT_ID | Byte Array | DER-encoding of the object identifier   indicating the data object type (default empty)
> CKA_VALUE | Byte array | Value of the object (default empty)

It only says that other attributes of storage subclasses objects have some restrictions:
> 4.4 Storage Objects 
>...
>Only the CKA_LABEL attribute can be modified after the object is created. (The CKA_TOKEN, CKA_PRIVATE, and CKA_MODIFIABLE attributes can be changed in the process of copying an object, however.)

**Comment by rijswijk** [comment]
The fact that the PKCS #11 spec does not mention anything leaves it open to interpretation of the token implementer. The spec clearly specifies that token implementers may choose to restrict whether or not attributes can be changed. 

Do you have a specific use case for wanting to change the content of a data object, or an application that does not work? If not, we will leave the behaviour as is, as it is clearly documented in the code. In case you do have reasons you would like to see this changed, I do have to caution that we currently have not time to spend on development cycles, so if this is an urgent requirement, then a pull request would be appreciated.

**Comment by alexyack** [comment]
Yes, the spec leave you the possibility to implement more restrictions, but the decision 

> Therefore we assume it is not allowed to change the CKA_VALUE attribute of a Data Object

is look very strange.....

Please check this post on [StackOverflow](https://stackoverflow.com/q/55098713/3868464), where you can contact with it's author.

**Comment by rijswijk** [comment]
As this question on StackOverflow does not mention a specific use case we will not change the behaviour. Also, the OP seems to have accepted another response on the thread that the SoftHSM implementation does not allow changing of the attributes of a data object. We also note that this behaviour has been in SoftHSM for years, this is the first question about this behaviour.

Closing this issue, thank you for bringing it to our attention, the OP on StackOverflow can always reach out to us if they have a specific use case for changing attributes on data objects.

**Comment by alexyack** [comment]
I have just checked my code.
In some cases I update CKA_VALUE and tests with SoftHSM get CKR_ATTRIBUTE_READ_ONLY, but my solution is not designed to work with SoftHSM so you can ignore my personal case. 

Just for reference.
Other **hardware** tokens like Aladdin eToken and Aktiv ruToken allow to modify this attribute value and my code works fine.
