### ISSUE TITLE
CKA_EC_POINT read only

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#463]
For reasons I wont go into I'm trying to change the value of the CKA_EC_POINT attribute in a previously created public key (which used C_GenerateKeyPair)

When I try  this using C_SetAttributeValue I get the error response CKR_ATTRIBUTE_READ_ONLY.  

I cant see anything in the PKCS#11 standards that seems to suggest this attribute should be set as read only - although I can see good reasons why this is the case.

Also looking through the SoftHSMv2 source I cant see anything that tests for this.

**Comment by rijswijk** [comment]
While this is not explicitly specified in the PKCS #11 v2.40 standard for EC public/private key objects, generally, attributes cannot be changed unless they are explicitly marked is potentially mutable. In addition to this, token implementations can choose to make attributes read only, even if the standard says that they may be mutable. [Table 10](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959698) specifies common footnotes for attributes, and as you can, for example, see for RSA key objects, as specified in [Table 26](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959720), the attributes that define an RSA public- and private key are not marked as mutable (footnote 8 is not present). SoftHSM assumes the same policy applies to EC keys.

Thus, if you wish to create an EC public key object with a different point in the public key, you'll have to create a new object.

**Comment by johughes99** [comment]
I thought that was the case - so starting to produce code that uses C_CreateObject!
