### ISSUE TITLE
how to get csr for GOSTR3410 keys?

### ISSUE THREAD

**Issue by gecheim** [opendnssec/SoftHSMv2#466]
Hallo.
I'm in the program create a pair of private and public keys using the interface of PKCS#11 and the mechanism CKM_GOSTR3410_KEY_PAIR_GEN. After that, you need to request a certificate for them in the certifying center.
I tried to use openssl and libp11 for this, for which I used the following sequence of commands:
`openssl req -key "$(p11tool --list-tokens | grep -n5 SoftHSM | grep -o "pkcs11:.*$" | xargs p11tool --set-pin 11111111 --info --login | grep -m1 -o "pkcs11:.*$")" -engine gost -keyform engine -engine pkcs11 -verbose`
The result is an error, because openssl can not handle the key format GOSTR3410.
Prompt in what way it is possible to receive request of the certificate for such keys.

**Comment by rijswijk** [comment]
I'm afraid we cannot really comment on this, the PKCS #11 API has no provisions for generating CSRs. You could try one of the other cryptographic libraries (Botan, GNUTLS) to see if they provide this functionality. Or consider asking in the OpenSSL community whether they have plans to support this.
