### ISSUE TITLE
C_EncryptFinal - segmentation fault

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#469]
In testing out various error conditions in the C_Encrypt* set of function calls I noticed I get a segmentation fault when i pass a NULL ptr for the pulLastEncryptedPartLen parameter. Looking at the code in SoftHSM.cpp I notice there is no check for it being NULL

I also get some CKR_OK returns for some situations where I'm passing in either NULL pointers or zero length to the various function calls. But given the strategy in SoftHSMv2 seems to be towards leniency I'm not reporting those:-)

**Comment by rijswijk** [comment]
I have implemented a fix and a test case which my colleague will review and merge probably later this weeks. Thanks for the report!
