### ISSUE TITLE
C_Logout - sequential calls

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#472]
In issuing C_Logout and then a subsequent C_Logout (without an intervening C_Login) gives a CKR_OK return. I would have thought it should have returned CKR_USER_NOT_LOGGED_IN. The base PKCS#11 base spec is not explicit on this behavior - if you look at the possible return values it does list CKR_USER_NOT_LOGGED_IN as a possible value.

**Comment by rijswijk** [comment]
I don't believe there is a proscribed return value in the standard; arguably, from a security perspective, returning ```CKR_USER_NOT_LOGGED_IN``` reveals information (that a user was logged in). I don't see any harm in returning ```CKR_OK```, in effect it turns the call into an idempotent function. Unless you see a reason why it should return anything other than ```CKR_OK```, I will close this issue and treat it as documentation of known behaviour.

**Comment by johughes99** [comment]
I agree
