### ISSUE TITLE
SoftHSM in a Docker (with secret delegation)

### ISSUE THREAD

**Issue by vanrein** [opendnssec/SoftHSMv2#476]
Would it be an idea to describe how to best integrate SoftHSMv2 with Docker (and other virtualisation technologies)?

There is a `--secret` option that mounts a secret file into a container's file system using a RAM layer.  This helps to provide the PIN only to containers that may have it, without storing it on unencrypted disks.  Docker manages the encryption of the secret file from the host environment, and replicates it through a "swarm" of nodes.

One thing I've learnt from this is that my security application [TLS Pool](https://github.com/arpa2/tlspool) can benefit more than expected from storing the PIN in a file on its own, instead of in the configuration file.

I am however wondering if there are files internal to the SoftHSMv2 engine that could be protected with the same mechanism, to protect the content behind the PKCS #11 API.  I would expect a salt or other entropy source to be hashed along with the password in forming the encrypted data for the stored files.

Being able to protect the storage format and not just the PIN could prove helpful in stopping attacks that would gain access to the HSM's stored files.  It could also make operators feel more relaxed about access rights of the various files stored by the HSM.

**Comment by rijswijk** [comment]
Right now, the PIN is used as a source for a PBKDF from which a key is extracted that is used to encrypt sensitive data. Hence, if a sufficiently secure PIN is chosen, and this PIN is stored securely, then there should be no need to protect other files. The biggest issue is that there will always be brief periods of time during which the PIN is present in memory, which, as far as I can see, none of the standard virtualisation/container technologies can protect against.

Having said that, a guide on how to Dockerize SoftHSM v2 (for example with a p11-proxy stacked on top) would be a nice contribution, so a pull request is welcome.
