### ISSUE TITLE
Importing AES Key via PKCS#11

### ISSUE THREAD

**Issue by ortug** [opendnssec/SoftHSMv2#478]
Hi All,

I am tring to import an AES key to SoftHSM. I am using C_CreateObject function of PKCS#11 standart and I am getting CKR_ATTRIBUTE_READ_ONLY error from that function. You can see the attributes that i am using in the attachment.  I have successfully created the AES key on Utimaco Soft HSM with same attributes.   

![attributes](https://user-images.githubusercontent.com/26404172/57619718-534f7480-758f-11e9-9b8c-5b8a0aa3fe8d.png)

**Comment by rijswijk** [comment]
```CKA_VALUE_LEN``` must not be specified in calls to ```C_CreateObject``` (please refer to the PKCS #11 specification for details). Utimaco's implementation probably (incorrectly) ignores this.
