### ISSUE TITLE
Slots are Jumblinig

### ISSUE THREAD

**Issue by NaveenVamshi** [opendnssec/SoftHSMv2#486]
I am creating the slot in soft hsm using the command

softhsm2-util --init-token --slot 2 --label "mt2"

after creating more the slots are jumbled.

Code for login for the particular slot it is working in same manner, jumbling of slots is happening
-----------------------------------------------------------------------------------------------------------------------------
var mod = Module.load("/usr/local/lib/softhsm/libsofthsm2.so", "SoftHSM");

mod.initialize();

         var session = mod.getSlots(0).open();
         session.login("password");

         // Get a number of private key objects on token 
         console.log(session.find({class: graphene.ObjectClass.PRIVATE_KEY}).length); 

         try {
             // Getting info about PKCS11 Module 
             var module_info = pkcs11.C_GetInfo();

             // Getting list of slots 
             var slots = pkcs11.C_GetSlotList(true);
             var slot = slots[2];

          console.log("%s", JSON.stringify(slot));
             // Getting info about slot 
             var slot_info = pkcs11.C_GetSlotInfo(slot);

             // Getting info about token 
             var token_info = pkcs11.C_GetTokenInfo(slot);

             console.log("-----------------------token_info");
             console.log("%s", JSON.stringify(token_info));
------------------------------------------------------------------------------------------------------------------------------

In the above code slot 2 , should be called because of the code var slot = slots[2];, but it is calling the slot 1.

Actually slots are jumbling, how can I get the preferred slot, what changes to be made in code. The code used to display about which slot is called by using the code

console.log("%s", JSON.stringify(token_info));

Is there any other code which I can implement to get the slots correctly?

**Comment by rijswijk** [comment]
Slot identifiers are not fixed in PKCS #11, and SoftHSM is no different. In order to find a specific token, you should call ```C_GetSlotList```, and then (if need be) repeatedly call ```C_GetTokenInfo``` to find the slot with the token you want to use. You must _never_ rely on slot IDs remaining static in PKCS #11 code.
