### ISSUE TITLE
Runtime warnings: Can't read appid

### ISSUE THREAD

**Issue by jonasholtkamp** [opendnssec/SoftHSMv2#490]
I'm running SoftHSMv2 in a Kubernetes cluster. Each second I get the following log message:
```
Jun 26 14:53:05 softhsm-proxy-9d45686-srq58 pkcs11-proxy[19]: WARNING: Can't read appid
```

However encryption and signing works just fine, it's just that these log messages appear periodically. Locally in Docker Compose everything is fine. Any ideas?

**Comment by jariq** [comment]
To me it looks more like an entry generated by `pkcs11-proxy` application. IMO it's not related to SoftHSM.

**Comment by rijswijk** [comment]
Agreed, this is a ```pkcs11-proxy``` log message, I'd suggest you pick it up with them.
