### ISSUE TITLE
How does the SoftHSM protect the PrivateKey stored in it?

### ISSUE THREAD

**Issue by meishijia** [opendnssec/SoftHSMv2#492]
When use the SoftHSM as KeyStore, I invoke the method KeyStore.setKeyEntry(String alias, Key key, char[] password, Certificate[] chain), and I want to know how SoftHSM uses the password to protect the key stored in it. I found an implementation in sun.security.provider.KeyProtector, and it uses the PBE+hash. So I wonder what mechanism the softHSM uses.

**Comment by rijswijk** [comment]
SoftHSM uses RFC 4880 PBE + salt (see the [source](https://github.com/opendnssec/SoftHSMv2/tree/develop/src/lib/data_mgr), in ```RFC4880.cpp``` and ```SecureDataManager.cpp```).
