### ISSUE TITLE
C_CopyObject getting (CKR_ATTRIBUTE_READ_ONLY

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#498]

**Comment by johughes99** [comment]
I have been looking at this in more detail and trying to "debug" what is going on.
It is failing in the function P11Attribute::update.  
Basically it falls through all the Table 10 checks and exits at the end of the functionwith the default return value of CKR_ATTRIBUTE_READ_ONLY.

Why it is doing this is not clear right now

**Comment by rijswijk** [comment]
It would help to know which attribute it is trying to set when this error occurs. I suspect it is trying to set a generated attribute (i.e. an attribute that the PKCS #11 library derives or sets, but that is not user writable directly).

**Comment by johughes99** [comment]
I'm struggling to find out what it is right now. I know it has a length of 8 - and isn't a string.  Trying to put some debug at the beginning of P11Attribute::update

Do you have a generic function i can use to output a value of an attribute

**Comment by rijswijk** [comment]
No, not really, debug prints are probably the way to go.

**Comment by johughes99** [comment]
It is the CKA_CLASS attribute - ie value 0

**Comment by rijswijk** [comment]
would you mind verifying what our test suite does, because I'm pretty sure it should verify functioning of ```C_CopyObject```, and if not, that is something we need to add.

**Comment by johughes99** [comment]
so I have checked that the original object does have a CKA_CLASS set as CKO_DATA.  So next just check that value is processed correctly

**Comment by johughes99** [comment]
will do.  I will get back much later today

**Comment by johughes99** [comment]
The test suite does test C_CopyObject quite well.

However, I have solved the problem and not sure it is a "bug" or a "feature".  

As we all know when you copy an object you can not change the CKA_CLASS of the object in copying.  But I (perhaps foolishly) defined the CKA_CLASS of the new object to be CKO_DATA - as in the original object.  So although I wasn't changing the CKA_CLASS of the object softhsm doesn't like you specifying CKA_CLASS at all for the new object

**Comment by rijswijk** [comment]
AFAIK any attributes specified in a template override whatever is in the original object, so an error message is to be expected, as you are trying to overwrite a write-once attribute. If you agree, can you close the issue?

**Comment by johughes99** [comment]
I guess I agree:-)
