### ISSUE TITLE
Using Botan 2.9

### ISSUE THREAD

**Issue by orestep** [opendnssec/SoftHSMv2#499]
In the file Botan_ecb.cpp on line 111, there is throw Exception(...), this conflicts with Botan protected declaration and causes a compilation error. My guess is that line 111 should be throw Invalid_Argument(...) and when changed, correctly compiles and links the Botan library. The version of softhsm2 was taken from the master branch 20190827.

**Comment by rijswijk** [comment]
Could you please verify that the solution you proposed works and provide a pull request if so? This will automatically schedule a build in the continuous integration environment, which tests correct building of SoftHSM on multiple platforms. Note: there is currently an open issue to drop support for older versions of Botan (#493), perhaps you we can merge the two issues and move this report there?

**Comment by randombit** [comment]
I believe this particular issue was addressed by the change in the recently merged PR #482 or if you upgrade to Botan 2.11.0 a change was made there which allows versions of SoftHSM prior to #482 to work as before.

**Comment by rijswijk** [comment]
Thanks @randombit, closing this.
