### ISSUE TITLE
Question: CKR_GENERAL_ERROR on C_GetAttributeValue

### ISSUE THREAD

**Issue by microshine** [opendnssec/SoftHSMv2#505]
I've got `CKR_GENERAL_ERROR` on `C_GetAttributeValue`

I'm trying to print all private and public keys from token to console and I've got that error for some private keys for `CKA_ID` and `CKA_LABEL` getting.

In which cases can I get `CKR_GENERAL_ERROR` error on `C_GetAttributeValue` using?

**Comment by rijswijk** [comment]
This means you tried to access an attribute on a protected object and were not logged in as user, see ```SoftHSM.cpp``` [line 1767 and further.](https://github.com/opendnssec/SoftHSMv2/blob/de9012e09e645f64cb4ba6f156db1341517527de/src/lib/SoftHSM.cpp#L1767)

**Comment by microshine** [comment]
@rijswijk 
I'm using `C_Login` function and `C_FindObjects` to get all `CKO_PRIVATE_KEY` and `CKO_PUBLIC_PUBLIC`  keys. SoftHSM throws `CKR_GENERAL_ERROR` exception for some filtered objects (for me it's for some `CKO_PRIVATE_KEY`).

Is it possible that SoftHSM returns authorized and unauthorized in `C_FindObjects`?

**Comment by rijswijk** [comment]
Have you checked the SoftHSM log? in exceptional cases it will log why access is denied. Sounds also like you might be accessing attributes that are not supposed to be read (see PKCS #11 spec).

**Comment by microshine** [comment]
@rijswijk thank you for the answer. I'll try to get logs from SoftHSM.

I'm getting `CKA_ID` and `CKA_LABEL` attributes
