### ISSUE TITLE
configure script does not consider OpenSSL library path in test executables

### ISSUE THREAD

**Issue by 0xa5a5** [opendnssec/SoftHSMv2#507]
When providing a custom OpenSSL path by ``--with-openssl`` the configure script does not handle this path properly. That is, the path is considered when building the test executables ``conftest`` (function ``ac_fn_c_try_link``), however, not when running them (``ac_fn_c_try_run``).

On systems with native OpenSSL libraries, the configure script would in this case test the native shared library's capabilities, on systems without OpenSSL libraries the test would fail, and hence various OpenSSL specific options would be disabled, although the custom built OpenSSL library would provide the required functionality (e.g. P256, P384, P512, ED448, ED25519).

This behaviour possibly also applies to other dynamic libraries whose path can be specified by means of command line parameters.

**Comment by rijswijk** [comment]
Would you be willing to supply a pull request to fix this?

**Comment by halderen** [comment]
Administratively closing issue due to rationale in the linked pull request.  If usage of LD_LIBRARY_PATH or inclusion in /etc/ld.config isn't working please consider re-issuing the issue.
