### ISSUE TITLE
Logging in simultaneously in multiple threads

### ISSUE THREAD

**Issue by hug-dev** [opendnssec/SoftHSMv2#509]
Hi,

I am not sure if this question relates to the PKCS 11 standard or this implementation but hopefully someone can help 😃 

In my application, I initialise the library with `CKF_OS_LOCKING_OK` in order to access it from multiple threads.
Each thread is opening its own separate session to access the library and some of them need to authenticate to perform operations on private objects.

The problem I am having is that when the amount of threads is big, two threads will try to log in simultaneously:
- A opens a session
- A logs in
- B opens a session
- B logs in -> fails and `CKR_USER_ALREADY_LOGGED_IN` is returned

I did not find anything in the PKCS 11 specs about that particular case. I was thinking that if the library has been initialised with multithreading support there would be some mechanism to allow that?

For example some kind of atomic counter of the current sessions logged in so that `C_Login` will increment the counter and not fail if the counter is `> 1` and `C_Logout` would decrement the counter and really log out if the counter is `0` (something like that the order is probably wrong 😄).

If it is the library user responsability to do that then I will implement something like that in my code but I was just wondering!

**Comment by rijswijk** [comment]
In PKCS 11, if one session is logged in, all sessions are logged in, hence ```CKR_USER_ALREADY_LOGGED_IN``` is returned. You can safely ignore this warning. Common practice is to open a log-in session, and the only thing you do in that is log in, and log out when all your other sessions are done (to prevent a race condition on logging out). Hope this helps.

**Comment by hug-dev** [comment]
Thanks for the info!
I guess the common practice you described is similar but I am also conscious of keeping the authentication state the least amount of time possible, to limit the time a buggy/malicious session would be able to access the private objects.
