### ISSUE TITLE
HSM returned response code: 0x70 CKR_MECHANISM_INVALID

### ISSUE THREAD

**Issue by 342167339** [opendnssec/SoftHSMv2#511]
when I use **pkcs11 crypto interface** in barbican, the barbican will report **WARNING**: 
`WARNING barbican.plugin.crypto.p11_crypto [req-dee0ad0f-9ed8-4fa9-adb5-91945242ce74 - a8b9d5eb-f14d-4f52-82cb-2fb1e74eceb3 - - -] Reinitializing PKCS#11 library: HSM returned response code: 0x70 CKR_MECHANISM_INVALID: barbican.common.exception.P11CryptoPluginException: HSM returned response code: 0x70 CKR_MECHANISM_INVALID`

**CKR_MECHANISM_INVALID**: 
`An invalid mechanism was specified to the cryptographic operation.  This error code is an appropriate return value if an unknown mechanism was specified or if the mechanism specified cannot be used in the selected token with the selected function.`

My **barbican.conf** setting is(almost the default value):

![image](https://user-images.githubusercontent.com/20694600/69221629-b3644a80-0bb2-11ea-81ee-8075f7d37f13.png)

The **CKM_AES_CBC** is default encryption encryption_mechanism, **CKM_AES_KEY_GEN** is default hmac_keygen_mechanism, **CKM_SHA256_HMAC** is default hmac_keywrap_mechanism, I don't know which one doesn't be support by softhsm. **BUT** the default value is for **SafeNet HSM**, I don't know the right config for softhsm. I tried some CKM in pkcs11 spec, but it reported INVALID PARAMETER in barbican. **MAYBE what I need is just a correct config for softhsm**.

**My Environment:**
No auth barbican(stein and master), installed as 

> https://github.com/cloudkeep/barbican/wiki/Barbican-Quick-Start-Guide

It could work well to operating secret data through simple_crypto plugin.

python 2.7.5
softhsmv2
OpenSSL  **1.0.2g**( I tried 1.1.1d, it didn't work)
Slot is assigned and mkek/hmac is generated successfully using **barbican-manager hsm** command.

WHAT should I do to modify the p11_crypto_plugin section of barbican.conf to make softhsm work through pkcs11 interface?
Or any other method, thanks!

**Comment by rijswijk** [comment]
We are unfamiliar with Barbican or its mechanism requirements, there appears to be a project to support SoftHSM in combination with Barbican which you can find here: https://github.com/openstack/charm-barbican-softhsm

The ```README``` for that project states that OpenSSL < 1.0.2h will not work due to mechanism limitations.

You can also use GNUTLS' ```p11tool``` to list the mechanisms supported by your build of SoftHSM to check which of the mechanisms you are missing.

Unfortunately, troubleshooting applications that use PKCS #11 is out of scope for our project, it would simply cost our volunteers too much time, we hope these hints help you figure out a solution.

**Comment by 342167339** [comment]
@rijswijk Thanks rijswijk, I've checked the softhsmv2 supported mechanism by using p11tool, and the softhsmv2 seems to work well, so I will debug on the end of barbican.

**Comment by 342167339** [comment]
@rijswijk Hi, sorry for bothering you again. I find my softhsm doesn't support CKM_AES_KEY_WRAP which is supposed to be supported. In source code, I find that this function is controlled by macro HAVE_AES_KEY_WRAP which is 0 now. Is this p11 function supported by softhsm? If yes, how can I valid it.  Look forward to your reply, thanks a lot.

**Comment by rijswijk** [comment]
```CKM_AES_KEY_WRAP``` is only supported if OpenSSL support RFC 5649, which -- as far as I can see -- should be the case for OpenSSL 1.1.1; support is automatically detected at compile time by the m4-macro ```m4/acx_openssl_rfc5649.m4```.
