### ISSUE TITLE
softhsm2-util --init-token -- slot 0  returns a weird slot number

### ISSUE THREAD

**Issue by letoams** [opendnssec/SoftHSMv2#512]
I want to use slot 0, but I can't do that on softhsm higher than 2.1.0. As of 2.2.0 I get:

[root@thinkpad paul]# rm -rf /var/lib/softhsm/tokens/*
[root@thinkpad paul]# rpm -q softhsm
softhsm-2.2.0-4.fc31.x86_64
[root@thinkpad paul]# softhsm2-util --init-token  --slot 0 --label "OpenDNSSEC" --pin 1234 --so-pin 1234
The token has been initialized.
[root@thinkpad paul]# softhsm2-util --show-slots
Available slots:
Slot 546161034
    Slot info:
        Description:      SoftHSM slot ID 0x208dc18a                                      
        Manufacturer ID:  SoftHSM project                 
        Hardware version: 2.2
        Firmware version: 2.2
        Token present:    yes
    Token info:
        Manufacturer ID:  SoftHSM project                 
        Model:            SoftHSM v2      
        Hardware version: 2.2
        Firmware version: 2.2
        Serial number:    8b4346d9208dc18a
        Initialized:      yes
        User PIN init.:   yes
        Label:            OpenDNSSEC                      
Slot 1
    Slot info:
        Description:      SoftHSM slot ID 0x1                                             
        Manufacturer ID:  SoftHSM project                 
        Hardware version: 2.2
        Firmware version: 2.2
        Token present:    yes
    Token info:
        Manufacturer ID:  SoftHSM project                 
        Model:            SoftHSM v2      
        Hardware version: 2.2
        Firmware version: 2.2
        Serial number:                    
        Initialized:      no
        User PIN init.:   no
        Label:        

I cannot get it to use slot 0, or any other number specified. softhsm 2.1.0 works properly. ssofthsm 2.2.0 upto 2.5.0 all fail.

I tried to git bisect 2.1.0...2.2.0 but that code simultaneously wants automake 1.15 and something newer than 1.15, so after some jugging with automake 1.15 and 1.16 rpm, I gave up.

This work was started because fedora has softhsm 2.5.0 and I need to start testing opendnssec migration from 1.4.x to 2.x, but that also includes a softhsm 1.4 to 2.x upgrade. so I need to grab my softhsm 1.4 data and pull it into softhsm 2.x

**Comment by rijswijk** [comment]
SoftHSM v2 does not have predictable slot IDs, and has not had these since the first release. The behaviour did change, however, in version 2.2, see issue #199. You should not assume that you know a slot number, but instead always search for a token by label. In case you really want to use a slot ID, you can rely on the semantics introduced in #199, but I would recommend against this for new code.

To import 1.4 data, you should be able to use ```softhsm2-migrate``` with the ```--token``` option.

**Comment by rijswijk** [comment]
Closing this, if you have follow-up questions please re-open the issue.
