### ISSUE TITLE
Method C_DecryptInit returned CKR_OBJECT_HANDLE_INVALID

### ISSUE THREAD

**Issue by mcabriel** [opendnssec/SoftHSMv2#514]
Hi,

I'm using your PKCS11Interop library and doing the Encrypt using mechanism CKM.CKM_DES3_CBC.
Then stored that encrypted data. 
Afterwards, I decrypted that data on different instance and encountered this issue "Method C_DecryptInit returned CKR_OBJECT_HANDLE_INVALID".

I have read some explanations regarding this error in the pdf document that "B1 attempts to perform some operation.....".

Although in doing the test under PKCS11Interop _01_EncryptAndDecryptSinglePartTest, i tweaked it by doing the same encryption and decryption separately. It works properly using the mock dll. But when using the Softhsm2 dll, that's when I encountered this problem.

Any thoughts about this?

**Comment by rijswijk** [comment]
Object handles are not persistent across sessions, in order to perform an operation with the same object in a different session you need to first find the object and obtain a handle using appropriate calls to ```C_FindObjects```. The PKCS11 specification should explain this (and it seems you have already found some of the information).

**Comment by mcabriel** [comment]
Hi @rijswijk 

Thanks for the reply, I'm not sure if this is where the right question to ask. I understood that the object handles was probably destroyed by the session that did the encryption when the session closed. And when trying to decrypt it with the new session, that's when we received the error.

However, by trying to C_CreateDataObject, and hopefully do the C_CopyObject, it seems that the "C_CopyObject" cannot be executed on the platform for SoftHSM for windows, is that correct?

**Comment by rijswijk** [comment]
As far as I know, there is no limitation on the use of ```C_CopyObject``` on any platform, but I don't maintain the Windows build, so I can't say for sure.

**Comment by mcabriel** [comment]
I actually had some tests and checked the code and it seems that the PKCS11Interop library says that the copy object cannot be executed on the said platform (Softhsm  **during runtime**).

I actually "forced" and skipped the checking and yes, im getting this error 
Method C_CopyObject returned CKR_ARGUMENTS_BAD. Should I open this one on a new separate issue?

**Comment by rijswijk** [comment]
You can try to turn on logging in SoftHSM to see why it thinks the arguments provided are bad. Unless you have reason to believe there is a bug in SoftHSM, I would ask you not to open an issue and to find out what is happening first. While we try to help out users with questions, our support resources are scarce (read: mostly spare time of individuals). Also when you say "our PKCS11Interop library", could it be you are referring to another project? Maybe you can also ask the question there?
