### ISSUE TITLE
OTP

### ISSUE THREAD

**Issue by jahluwalia** [opendnssec/SoftHSMv2#515]
Hi,

Does SoftHSMv2 implement the OTP section of the PKCS11 spec? 

http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/cs01/pkcs11-curr-v2.40-cs01.html#_Toc399399116

Thanks,
Jas

**Comment by jariq** [comment]
Hello @jahluwalia, SoftHSMv2 currently does not implement OTP mechanisms and personally I've never seen PKCS#11 module that would implement this part of specification.

**Comment by jahluwalia** [comment]
If i wanted to add it, could you put in me in teh right places of SoftHSM2 code?

thanks,
jas

**Comment by jariq** [comment]
Sorry, I'm not familiar with the SoftHSMv2 codebase enough to do that.

**Comment by rijswijk** [comment]
We currently have no plans to support this part of the OTP spec, I'll close the issue for now and mark it as a potential future feature request.
