### ISSUE TITLE
std::set used in non-thread-safe way

### ISSUE THREAD

**Issue by oerdnj** [opendnssec/SoftHSMv2#518]
std::set is not thread-safe, but it's being used in unlocked manner in `SessionObjectStore::deleteObject()`:

https://github.com/opendnssec/SoftHSMv2/blob/develop/src/lib/object_store/SessionObjectStore.cpp#L125

This might (or might not) be main cause for the crash in `dnssec-signzone`: https://gitlab.isc.org/isc-projects/bind9/issues/1509

**Comment by rijswijk** [comment]
thanks Ondřej, looks like you're right. have you tried a build where the lock directive is moved to before `objects.find(..)` is invoked by any chance?

If I look at the stack trace from the BIND crash then I concur that this may indeed be the cause of that crash.

**Comment by oerdnj** [comment]
Hi Roland,

> have you tried a build where the lock directive is moved to before objects.find(..) is invoked by any chance?

I haven't, but the crash is so rare and it happened inside the CI that we won't be reproduce it right away. If it will start occurring more frequently we will probably update our images to use the patch.

We have only recently started collected, so it might have been happening before, but we have stack traces in the CI builds, so that's how I found it.

**Comment by rijswijk** [comment]
Right, OK. Well your analysis sounds quite plausible so I suggest we go ahead and patch the code. I had a quick look, and it seems there is no harm in moving the lock up, do you concur?

**Comment by oerdnj** [comment]
Yes, exactly, that would be my proposed fix.

**Comment by rijswijk** [comment]
PR submitted for review, check branch `fix_issue_518` if you already want to test.
