### ISSUE TITLE
EdDSA keygen not work according to final PKCS #11 3.0

### ISSUE THREAD

**Issue by Jakuje** [opendnssec/SoftHSMv2#523]
If I read the PKCS #11 3.0 specification correctly, the `EC_PARAMS` in the keygen template should list the DER encoding of curve name (PrintableString) for EdDSA keys. The template  in [1]  even adds an example how the ec params template should look like:

    CK_BYTE ecParams[] = {0x13, 0x0c, 0x65, 0x64, 0x77, 0x61, 0x72, 0x64, 0x73, 0x32, 0x35, 0x35, 0x31, 0x39};

But from my reading of the code in `src/lib/crypto/OSSLEDDSA.cpp`, the content is passed to few OpenSSL functions assuming it is really only OID and hoping we will get some NID from OpenSSL.

This probably needs to be updated to work with named curves according to the standard. Filling the issue now so it does not get lost, but I hope I will be able to work on this soon.

[1] https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/csprd01/pkcs11-curr-v3.0-csprd01.html#_Toc10560871

**Comment by rijswijk** [comment]
Thanks, the contributions are much appreciated!
