### ISSUE TITLE
compiling errors out on mac os

### ISSUE THREAD

**Issue by onesick** [opendnssec/SoftHSMv2#535]
With the changes in: https://github.com/opendnssec/SoftHSMv2/commit/f5dcf2d4646785b0b37a0e75eab146cf39360cc3
I am getting the following errors and warning:
./PublicKey.h:64:23: warning: 'constexpr' non-static member function will not be
      implicitly 'const' in C++14; add 'const' to avoid a change in behavior
      [-Wconstexpr-not-const]
        constexpr PublicKey& operator=(const PublicKey&) { return *this; }
                             ^
                                                         const
./PublicKey.h:64:60: error: binding value of type 'const PublicKey' to reference
      to type 'PublicKey' drops 'const' qualifier
        constexpr PublicKey& operator=(const PublicKey&) { return *this; }
                                                                  ^~~~~
./PublicKey.h:64:23: error: no return statement in constexpr function
        constexpr PublicKey& operator=(const PublicKey&) { return *this; }
                             ^
In file included from AESKey.cpp:37:
In file included from ./CryptoFactory.h:40:
In file included from ./AsymmetricAlgorithm.h:37:
In file included from ./AsymmetricKeyPair.h:39:
./PrivateKey.h:71:24: warning: 'constexpr' non-static member function will not
      be implicitly 'const' in C++14; add 'const' to avoid a change in behavior
      [-Wconstexpr-not-const]
        constexpr PrivateKey& operator=(const PrivateKey&) { return *this; }
                              ^
                                                           const
./PrivateKey.h:71:62: error: binding value of type 'const PrivateKey' to
      reference to type 'PrivateKey' drops 'const' qualifier
        constexpr PrivateKey& operator=(const PrivateKey&) { return *this; }
                                                                    ^~~~~
./PrivateKey.h:71:24: error: no return statement in constexpr function
        constexpr PrivateKey& operator=(const PrivateKey&) { return *this; }
                              ^
2 warnings and 4 errors generated.
make[5]: *** [AESKey.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by hymas** [comment]
I had this same problem on Mac OS, and "fixed" it (maybe) by making these changes:

PrivateKey.h:

constexpr PrivateKey& operator=(const PrivateKey&) { return *this; }

To:

constexpr const PrivateKey& operator=(const PrivateKey&)  const { return *this; }

PublicKey.h:

constexpr PublicKey& operator=(const PublicKey&) { return *this; }

To:

constexpr const PublicKey& operator=(const PublicKey&) const { return *this; }

"make check" runs through OK, but I haven't done any extensive testing.

**Comment by rijswijk** [comment]
Thanks for the solution @hymas, closing

**Comment by iay** [comment]
Is this being picked up for a fix? I don't see a commit or an MR in the repository.

I ask because I'm trying to get the MacPorts port to work and I could just use the commit as a patch in the interim before a 2.6.1. Happy to format the above as a PR as well if that's easier.

**Comment by rijswijk** [comment]
If you wouldn't mind, a PR would be very welcome, thanks for offering!

**Comment by iay** [comment]
No problem. I have it ready to go, but today brings us a new version of macOS Catalina and of Xcode. I will update one machine to the latest to make sure it is compatible before submitting the PR (I don't expect a problem, though).

**Comment by hymas** [comment]
> I will **update** one machine to the latest to make sure it is compatible before submitting the PR (I don't **expect** a problem, though). 

Nobody expects the Update Inquisition!

I tested this on Mac OS 10.15.4 with Xcode 11.4 on my MacBookPro and it runs OK.  I haven't done any extensive testing, though . . . just some basics.

**Comment by iay** [comment]
macOS 10.15.5 and Xcode 11.5 seem to be fine for compilation, as expected.

I'm seeing this from `make check`, though:

```
  "vtable for CppUnit::TestSuiteBuilderContextBase", referenced from:
      AESTests::addTestsToSuite(CppUnit::TestSuiteBuilderContextBase&) in AESTests.o
      DESTests::addTestsToSuite(CppUnit::TestSuiteBuilderContextBase&) in DESTests.o
      DHTests::addTestsToSuite(CppUnit::TestSuiteBuilderContextBase&) in DHTests.o
      DSATests::addTestsToSuite(CppUnit::TestSuiteBuilderContextBase&) in DSATests.o
      ECDHTests::addTestsToSuite(CppUnit::TestSuiteBuilderContextBase&) in ECDHTests.o
      ECDSATests::addTestsToSuite(CppUnit::TestSuiteBuilderContextBase&) in ECDSATests.o
      EDDSATests::addTestsToSuite(CppUnit::TestSuiteBuilderContextBase&) in EDDSATests.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
```

I have `cppunit` installed (from MacPorts) but perhaps I am missing another dependency that everyone working with C++ knows about. Any ideas @hymas ?

**Comment by iay** [comment]
OK, that seemed to be just that I had run `./configure ...` before I installed `cppunit`, and not thereafter. Results look plausible, so I will push the PR now.

**Comment by rijswijk** [comment]
Thanks for the PR, will merge after CI tests complete.
