### ISSUE TITLE
Constexpr assignment operators in PublicKey and PrivateKey

### ISSUE THREAD

**Issue by Aearsis** [opendnssec/SoftHSMv2#538]
I have few questions/issues about these copy assignments introduced recently. 

https://github.com/opendnssec/SoftHSMv2/blob/e4c954e96ae5b625ca800b78f9fee5e2cc453423/src/lib/crypto/PrivateKey.h#L71
https://github.com/opendnssec/SoftHSMv2/blob/e4c954e96ae5b625ca800b78f9fee5e2cc453423/src/lib/crypto/PublicKey.h#L64

1) It does not make much sense to define an assignment operator `const` function - you should not assign into a constant variable.
2) The implementation also seems weird. You would not expect an assignment operator to do nothing.
3) According to the standard, assignment operator can be `constexpr` only if all the types involved are `LiteralType`, which the keys are not - they have virtual destructor.

Is there some reason behind it? If not, I suggest to change this to plain:

```c++
PrivateKey& operator= (const PrivateKey&) = default;
```

Or, if the purpose was to silence warnings but disable assignment, then:

```c++
PrivateKey& operator= (const PrivateKey&) = delete;
```

Both should work in all compilers, these are common snippets.

**Comment by rijswijk** [comment]
The reason these were introduced is that gcc10 follows C++20 and does not allow implicit assignment operators to exist (warning). So the purpose is to silence the warnings, the code does not have a function. Semantically, I would expect the compiler to refuse with a const violation if anyone attempts to assign, so the code does not have an effect. Can you elaborate on why you think the ```= delete;``` approach is better in your view? (not enough of a detailed C++ expert to be able to judge this).

**Comment by Aearsis** [comment]
Then the code does quite the opposite :) Assignment is more or less a function call. If you provide an implementation which is `const`, I believe that compiler will just call it, allowing semantically incorrect code to compile. (A compile error would be triggered if you actually attempted to modify `this` inside the function, or e.g. return it as a non-const reference - which is why #535 exists.)

The original warning is due to absence of any copy assignment operator - if you explicitly say that it is deleted, it will dismiss the warning without allowing copy assignment.

At the very least, we have to remove the `constexpr`, because it triggers a compile error in e.g. GCC 6.3:

```
./../PublicKey.h:64:29: error: enclosing class of constexpr non-static member function 'const PublicKey& PublicKey::operator=(const PublicKey&) const' is not a literal type
  constexpr const PublicKey& operator=(const PublicKey&) const { return *this; }
                             ^~~~~~~~
./../PublicKey.h:40:7: note: 'PublicKey' is not literal because:
 class PublicKey : public Serialisable
       ^~~~~~~~~
./../PublicKey.h:40:7: note:   'PublicKey' has a non-trivial descructor
```

... which is because of the limitation described in 3).

**Comment by Aearsis** [comment]
OK, I've just tried it. We cannot delete it, because it is used:

https://github.com/opendnssec/SoftHSMv2/blob/e4c954e96ae5b625ca800b78f9fee5e2cc453423/src/lib/crypto/OSSLDHKeyPair.cpp#L40

And I'm quite sure that current behavior is broken, as this line uses the phony assignment.

**Comment by rijswijk** [comment]
Would the "default" approach work? (the other approach that you quoted)

**Comment by Aearsis** [comment]
It should. The `default` explicitli instantiates the implicit operator, e.g. "copy all fields".

But as this class have no fields, it does not need it. The warning is produced because of the presence of destructor, which is not needed in this case - virtual destructor is already provided by the `Serialisable` class. On the other hand, that class should have it, along with copy & move constructors (defaulted).

I will prepare a PR, if you want.

**Comment by rijswijk** [comment]
Much appreciated, thanks! And thank you for opening this issue and pointing this out.
