### ISSUE TITLE
SoftHSM 2.6.0 release

### ISSUE THREAD

**Issue by jariq** [opendnssec/SoftHSMv2#541]
Hello volunteers,

I'm little confused about SoftHSM release (again). Up until today I thought that only 2.6.0 RC1 has been released but I've got request to release binaries for 2.6.0 in https://github.com/disig/SoftHSM2-for-Windows/issues/12. Today I found out that..

GitHub tag/release exists:
https://github.com/opendnssec/SoftHSMv2/releases/tag/2.6.0

[resend?] e-mail in `opendnssec-announce` list exists:
https://lists.opendnssec.org/pipermail/opendnssec-announce/2020-March/000138.html

Signed files are published:
https://dist.opendnssec.org/source/softhsm-2.6.0.tar.gz  
https://dist.opendnssec.org/source/softhsm-2.6.0.tar.gz.sig

There's no mention at:
- https://www.opendnssec.org/
- https://twitter.com/opendnssec
- `softhsm-develop` mailing list

And now I've seen [comment](https://github.com/opendnssec/SoftHSMv2/pull/540#issuecomment-605022915) from @rijswijk indicating that 2.6.0 might not been released yet.

So please someone enlighten me. Is 2.6.0 ten days out and I missed it again or not? :)

**Comment by rijswijk** [comment]
Hi @jariq -- @halderen release a release candidate, but no final release for 2.6.0 yet, sorry for the confusion. He is holding off to see if any final feedback comes in before going for 2.6.0 final. The release will then also be announced through the usual communication channels (OpenDNSSEC site, Twitter and mailing list).

**Comment by rijswijk** [comment]
@halderen I suggest closing this when the release goes out.

**Comment by jariq** [comment]
So files at https://dist.opendnssec.org/source/softhsm-2.6.0.tar.gz are RC1?

**Comment by rijswijk** [comment]
Hmm. Yes, they should be, the tarball name is indeed confusing if that is the case :-/

**Comment by rijswijk** [comment]
and to answer that question before you ask it, there are still outstanding PRs to be merged.

**Comment by iay** [comment]
Given that the linked mail says nothing about the release being an RC, and the other things @jariq mentions, I think it would be preferable if the upcoming release was 2.7.0 or 2.6.1, just for clarity.

**Comment by rijswijk** [comment]
hmm. that seems fair. will be 2.6.1.

**Comment by halderen** [comment]
Be be clear, the source code should always be leading.  The 2.6.0 tag has been set and package made out of it has been made public.  Hence there is a release.  In this particular case the website hasn't been updated (the website isn't particular easy to access to edit), as an oversight on my part, but the release mail was send out.

I do want to patch release-based stuff, like platform specific compation in a 2.6.1.  The when I haven't decided upon.

**Comment by halderen** [comment]
2.6.1 will be released today.  Website, maintainer/announce mailing list, tags, source, will be updated.  I will leave twitter, instagram, facebook, youtube, tiktok, snapchat, linkedin, google+, and the other channels to others.
