### ISSUE TITLE
Incorrect RSA key modulus causes signature failure.

### ISSUE THREAD

**Issue by dwmw2** [opendnssec/SoftHSMv2#544]
In the OpenConnect self-test suite I have a set of three SoftHSM tokens, all of which contain the same three RSA, EC and DSA certs but with different permuations of `CKA_PRIVATE` and `CKA_SENSITIVE`, and indeed the presence or absence of a corresponding public key object (as well as the X.509 cert and the private key).

See http://git.infradead.org/users/dwmw2/openconnect.git/blob/HEAD:/tests/Makefile.am#l196

These keys are *identical*. But when I connect with the one from the first token, SoftHSM knows the key modulus is 304. With the other two tokens, it thinks the modulus is 305 and failures occur.

Not sure why this hasn't always happened; I tried going back to SoftHSM 2.2 and it still happens. 

Observed on Fedora 30 with SoftHSM 2.5 and also a current build from git. I see it with both the GnuTLS and OpenSSL builds of OpenConnect (GnuTLS build shown here).

I added this debugging output:
```
--- a/src/lib/crypto/OSSLRSA.cpp
+++ b/src/lib/crypto/OSSLRSA.cpp
@@ -211,7 +211,7 @@ bool OSSLRSA::sign(PrivateKey* privateKey, const ByteString& dataToSign,
 
                // Perform the signature operation
                signature.resize(osslKey->getN().size());
-
+               fprintf(stderr, "size is %zd\n", osslKey->getN().size());
                int sigLen = RSA_private_encrypt(osslKey->getN().size(), &em[0], &signature[0], rsa, RSA_NO_PADDING);
 
                RSA_blinding_off(rsa);
@@ -241,7 +241,7 @@ bool OSSLRSA::sign(PrivateKey* privateKey, const ByteString& dataToSign,
 
                // In case of raw RSA, the length of the input data must match the length of the modulus
                OSSLRSAPrivateKey* osslKey = (OSSLRSAPrivateKey*) privateKey;
-
+               fprintf(stderr, "data size %zd modulus %zd\n", dataToSign.size(), osslKey->getN().size());
                if (dataToSign.size() != osslKey->getN().size())
                {
                        ERROR_MSG("Size of data to sign does not match the modulus size");
```

Now, in a clean build of openconnect after observing that 'make check' fails...

 In the `openconnect/tests` directory:

```
$ openssl s_server -key certs/server-key.pem -cert certs/server-cert.pem -accept 8443 -Verify 1
```
And separately in the same directory:
```
$ SOFTHSM2_CONF=./softhsm2.conf ./openconnect -c 'pkcs11:token=openconnect-test;object=RSA' --key-password 1234 localhost:8443 -v --servercert pin-sha256:xp3scfzy3r
```

That one succeeds, with debug output ending like this...
```
C_Sign
  IN: hSession = S3
  IN: pData = (32) "\xB0\x82\xD7M\xB7\xA3\xACQn_\x0E\x84z\xCFj\x88\xBBC\xDD\xA0\\xDA')\x8E\tO\x8D\xC2\x80\x0Ek"
 OUT: pSignature = (304) NOTHING
C_Sign = CKR_OK
C_Sign
  IN: hSession = S3
  IN: pData = (32) "\xB0\x82\xD7M\xB7\xA3\xACQn_\x0E\x84z\xCFj\x88\xBBC\xDD\xA0\\xDA')\x8E\tO\x8D\xC2\x80\x0Ek"
size is 304
 OUT: pSignature = (304) "U\xC2\xC2\x89\x81\xE1\x02\xF8\x8B\xA3\x82\x90\xA1\xEA\x84\xBF\xF5\xA8\xD1\xB1g\xDA\x0F\x94\x1C\xB6\xF0\x0Fp\x8B"$F\x87\..."
C_Sign = CKR_OK
Connected to HTTPS on localhost with ciphersuite (TLS1.3)-(ECDHE-SECP256R1)-(RSA-PSS-RSAE-SHA256)-(AES-256-GCM)

```

However, using the `openconnect-test1` or `openconnect-test2` tokens will fail thus:
```
$ SOFTHSM2_CONF=./softhsm2.conf ./openconnect -c 'pkcs11:token=openconnect-test1;object=RSA' --key-password 1234 localhost:8443 -v --servercert pin-sha256:xp3scfzy3r
```
...
```
C_Sign
  IN: hSession = S3
  IN: pData = (32) " h\x9By\xBC\xD6\x93\xC2\x1A\x84\xFB\xAC<\x1C\x93\xDD\xEF\xC00dY\xC2g\xC2Y}\xD6\x95S\xCFr\xF6"
 OUT: pSignature = (304) NOTHING
C_Sign = CKR_OK
C_Sign
  IN: hSession = S3
  IN: pData = (32) " h\x9By\xBC\xD6\x93\xC2\x1A\x84\xFB\xAC<\x1C\x93\xDD\xEF\xC00dY\xC2g\xC2Y}\xD6\x95S\xCFr\xF6"
size is 305
OSSLRSA.cpp(221): An error occurred while performing the RSA-PSS signature
C_Sign = CKR_GENERAL_ERROR
SSL connection failure: PKCS #11 error.

```

**Comment by dwmw2** [comment]
```
C_Sign
  IN: hSession = S3
  IN: pData = (32) "\x11\xEE\xEE\x04\x13\xAAX\xB5G\x87e\xB0\x8B\xCB\x9D\xF5\x19\x98\xBB\x8Ez\xEE\x17=\xA0\xD5WE1\x85\x817"
size is 304
key is AB5498FCA9C615959DA6C194849491791E78DB2D485199650102C04052495DEB70BC26EF68391E0491E2DBCB6F9340451E228E715A588928795E1A32253E8B9D3B347F19F8D02F37B76232B753A5432CC55DECACF935FA142B3466F1D6A7A1D0839A56F41983BCBF1174302DA8285BA2AB7AC6CD9C5CF851E9A90C48DB71BBB13477F7EEDE5D78C0480A370D651E3B2B14038972F252ED5F00C50660EA8020D043EC66BCD226DBF0293E6AF96220BE582644BAD78C6F76A60520E498B7C4727A5DDF4F0D23EC2E9C71EC30F9145FC8750BAB67F67DFB4D76644AA5D5FAB408509D13C78FC279B0B43E2F89D333274D9F8BD3602407ABB2723D29A5C44AEC3C04D2493E261BEC7A103DCA455A808B4D2A96634F2D63280F3B4747CA7C2C154132D5E0C9BEA5552CB36B462A56B11BED29
 OUT: pSignature = (304) "1Uv\xF3b3\x05\xFC\xC6\xB9\x9A\xF2C\x11P\x0E\xE9a\xF5!|\xD4\xB7\xD9,\x92z\xFDM}i\xE3\x06\x11\x13UY<\x1D(\xCFF\xC2\xC9\x0..."
C_Sign = CKR_OK
Connected to HTTPS on localhost with ciphersuite (TLS1.3)-(ECDHE-SECP256R1)-(RSA-PSS-RSAE-SHA256)-(AES-256-GCM)

```

vs.

```
C_Sign
  IN: hSession = S3
  IN: pData = (32) "\x86m\x19\\x04?\xC5\xAAU\xC2\xD31\xBEf\x1F0v\xB1\xE1\xE2\xB3=\xA7\xEC\xA4\x93\x87'\t\xD5\xD78"
size is 305
key is 00AB5498FCA9C615959DA6C194849491791E78DB2D485199650102C04052495DEB70BC26EF68391E0491E2DBCB6F9340451E228E715A588928795E1A32253E8B9D3B347F19F8D02F37B76232B753A5432CC55DECACF935FA142B3466F1D6A7A1D0839A56F41983BCBF1174302DA8285BA2AB7AC6CD9C5CF851E9A90C48DB71BBB13477F7EEDE5D78C0480A370D651E3B2B14038972F252ED5F00C50660EA8020D043EC66BCD226DBF0293E6AF96220BE582644BAD78C6F76A60520E498B7C4727A5DDF4F0D23EC2E9C71EC30F9145FC8750BAB67F67DFB4D76644AA5D5FAB408509D13C78FC279B0B43E2F89D333274D9F8BD3602407ABB2723D29A5C44AEC3C04D2493E261BEC7A103DCA455A808B4D2A96634F2D63280F3B4747CA7C2C154132D5E0C9BEA5552CB36B462A56B11BED29
OSSLRSA.cpp(222): An error occurred while performing the RSA-PSS signature
```

**Comment by rijswijk** [comment]
What I see in the code snippet for OpenConnect that you refer to is that the keys are imported using different tools. ```softhsm2-util``` and ```p11tool``` appear to be used. And if I interpret the scripting in ```Makefile.am``` and the output you provide above correctly, the test works when ```softhsm2-util``` is used to import the key, but does not work if ```p11tool``` is used. What I suspect is that ```p11tool``` may be prepending an extra ```0x00``` byte at the front of the modulus to ensure that it is treated as an positive big integer (effectively making it unsigned). To confirm this, could you dump the first few bytes of the modulus in both cases?

**Comment by dwmw2** [comment]
Was just poking at the files for that, and yes, there does seem to be a leading zero in at least the first case I looked at:
```
$ hexdump -C softhsm/3e606151-441f-fd0b-2b41-bd372ec8723f/f095d2b1-1592-4f77-80a7-e5cc04fcc634.object | grep 'ab 54
00000150  00 00 01 31 00 ab 54 98  fc a9 c6 15 95 9d a6 c1  |...1..T.........|
```

**Comment by rijswijk** [comment]
Was that key imported using ```softhsm2-util``` or ```p11tool```? And what would also help: how long have you been using this test, and did it work correctly before? And if so, what changed when it stopped working? (OS upgrade, other changes, ...)

I'm trying to understand if there is changed behaviour in e.g. the tool chain that generates the key or imports the key or whether this has always been broken.

It is something we can fix by rectifying the modulus on key import (by stripping any leading ```0x00``` bytes).

**Comment by dwmw2** [comment]
Hm, however that's true the actual file even for the `openconnect-test` token that's working.
```
$ hexdump -C softhsm/78239b73-64e9-44df-76cf-8dc68ccc7dab/a14b1c07-fd7b-bec1-d93b-03727572ea70.object | grep 'ab 54'
00000110  82 01 31 00 ab 54 98 fc  a9 c6 15 95 9d a6 c1 94  |..1..T..........|
```

**Comment by dwmw2** [comment]
Test has been like this since September 2016 and I've never seen a failure. No idea *why* I suddenly see a failure on Fedora 30 now.

**Comment by rijswijk** [comment]
Yes, it is canonical PKCS #8 format to have the leading zero, the import tool would strip that.

**Comment by dwmw2** [comment]
Note that the import procedure is there for posterity, the actual files of the softhsm database are present in my git tree to prevent changes in those tools from changing the tests over time. The keys haven't been imported since 2016.

**Comment by rijswijk** [comment]
OK. That is odd, the validation code in SoftHSM that checks the correct length of attributes also has not changed any time in the recent past. You said you tested with SoftHSM 2.2 as well, right? With the same input I assume?

**Comment by dwmw2** [comment]
Yes, precisely the same input files. Sometimes SoftHSM does change the files even when I'm running the tests which perform logically read-only operations. I usually just 'git reset --hard HEAD' to get back to the originals imported in 2016.

The two problematic tokens are `openconnect-test1` and `openconnect-test2`, with the keys imported by (a 2016 version of) p11tool.

The `openconnect-test` token, imported by a 2016 version of softhsm-util, is fine. Despite, AFAICT, *also* actually having the leading zero and the size of `0x131` (305) in its object file as shown above:
```
$ hexdump -C softhsm/78239b73-64e9-44df-76cf-8dc68ccc7dab/a14b1c07-fd7b-bec1-d93b-03727572ea70.object | grep 'ab 54'
00000110  82 01 31 00 ab 54 98 fc  a9 c6 15 95 9d a6 c1 94  |..1..T..........|
```
Somehow, SoftHSM is stripping the leading zero from that one but not the others?

**Comment by dwmw2** [comment]
A hack in ObjectFile::refresh() confirms that the ByteString being loaded even from the *working* token is prefixed with a zero...
```
bytestring attr type 288 (len 305): 00AB5498FCA9C615959DA6C194849491791E78DB2D485199650102C04052495DEB70BC26EF68391E0491E2DBCB6F9340451E228E715A588928795E1A32253E8B9D3B347F19F8D02F37B76232B753A5432CC55DECACF935FA142B3466F1D6A7A1D0839A56F41983BCBF1174302DA8285BA2AB7AC6CD9C5CF851E9A90C48DB71BBB13477F7EEDE5D78C0480A370D651E3B2B14038972F252ED5F00C50660EA8020D043EC66BCD226DBF0293E6AF96220BE582644BAD78C6F76A60520E498B7C4727A5DDF4F0D23EC2E9C71EC30F9145FC8750BAB67F67DFB4D76644AA5D5FAB408509D13C78FC279B0B43E2F89D333274D9F8BD3602407ABB2723D29A5C44AEC3C04D2493E261BEC7A103DCA455A808B4D2A96634F2D63280F3B4747CA7C2C154132D5E0C9BEA5552CB36B462A56B11BED29
```
... but later has been stripped before use:
```
C_Sign
  IN: hSession = S1
  IN: pData = (304) "%L\x08\xA6\xB7\x10vL\xE6\xC2\xF4o?\tG\xAD\xC2\xD8\x96\xE6IfmE\xE0\xBD)\xFBfs\x17y}\x87\xB2\xC8C\xA3`G6\x1D/C\x17\\xAD \..."
data 304 key modulus 304
Key AB5498FCA9C615959DA6C194849491791E78DB2D485199650102C04052495DEB70BC26EF68391E0491E2DBCB6F9340451E228E715A588928795E1A32253E8B9D3B347F19F8D02F37B76232B753A5432CC55DECACF935FA142B3466F1D6A7A1D0839A56F41983BCBF1174302DA8285BA2AB7AC6CD9C5CF851E9A90C48DB71BBB13477F7EEDE5D78C0480A370D651E3B2B14038972F252ED5F00C50660EA8020D043EC66BCD226DBF0293E6AF96220BE582644BAD78C6F76A60520E498B7C4727A5DDF4F0D23EC2E9C71EC30F9145FC8750BAB67F67DFB4D76644AA5D5FAB408509D13C78FC279B0B43E2F89D333274D9F8BD3602407ABB2723D29A5C44AEC3C04D2493E261BEC7A103DCA455A808B4D2A96634F2D63280F3B4747CA7C2C154132D5E0C9BEA5552CB36B462A56B11BED29
```
```

**Comment by dwmw2** [comment]
```
--- a/src/lib/SoftHSM.cpp
+++ b/src/lib/SoftHSM.cpp
@@ -9976,7 +9976,7 @@ CK_RV SoftHSM::getRSAPrivateKey(RSAPrivateKey* privateKey, Token* token, OSObjec
                exponent2 = key->getByteStringValue(CKA_EXPONENT_2);
                coefficient = key->getByteStringValue(CKA_COEFFICIENT);
        }
-
+       fprintf(stderr, "Private key (isKeyPrivate %s) modulus %zd: %s\n", isKeyPrivate?"true":"false", modulus.size(), modulus.hex_str().c_str());
        privateKey->setN(modulus);
        privateKey->setE(publicExponent);
        privateKey->setD(privateExponent);
```
For `openconnect-test` I see:
```
Private key (isKeyPrivate true) modulus 304: AB5498FCA9C615959DA…
```
For `openconnect-test1` I see:
```
Private key (isKeyPrivate false) modulus 305: 00AB5498FCA9C615959DA…
```
For `openconnect-test2` I see:
```
Private key (isKeyPrivate true) modulus 305: 00AB5498FCA9C61595DA…
```

**Comment by rijswijk** [comment]
What does the hack in ```ObjectFile::refresh()``` show for the non-working token? Two zeroes perhaps?

**Comment by dwmw2** [comment]
```
Object 0:
	URL: pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=76cf8dc68ccc7dab;token=openconnect-test;id=%01;object=RSA;type=private
	Type: Private key (RSA-2432)
	Label: RSA
	Flags: CKA_PRIVATE; CKA_SENSITIVE; 
	ID: 01

Object 0:
	URL: pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=2b41bd372ec8723f;token=openconnect-test1;id=%01;object=RSA;type=private
	Type: Private key (RSA-2440)
	Label: RSA
	Flags: CKA_WRAP/UNWRAP; CKA_SENSITIVE; 
	ID: 01

Object 0:
	URL: pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=488d6dd1669acb88;token=openconnect-test2;id=%01;object=RSA;type=private
	Type: Private key (RSA-2440)
	Label: RSA
	Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_SENSITIVE; 
	ID: 01

```

**Comment by dwmw2** [comment]
> What does the hack in `ObjectFile::refresh()` show for the non-working token? Two zeroes perhaps?

Nope, all are precisely the same with one leading zero.

Is it the decrypt operation called by SoftHSM::getRSAPrivateKey() in the isKeyPrivate case, which is *sometimes* stripping the zero?

**Comment by rijswijk** [comment]
This has me absolutely baffled, I can't find any place in the code where leading ```0x00``` bytes are explicitly stripped in SoftHSM. _If_ it happens, it must happen in OpenSSL, perhaps some behaviour changed there. Have you tried re-importing the keys in your test environment? And does that give the same result? All conversion to/from stored attributes uses OpenSSL API-provided functions. BTW, it is the call to RSA_private_encrypt that is failing, not the size check that SoftHSM performs.

**Comment by dwmw2** [comment]
Ah, in the `openconnect-test` case I'm looking at the wrong thing. The modulus does exist with the leading zero, but if I instrument the `SecureDataManager::decrypt()` call I find that *that* instance of the bytestring isn't the important one.

openconnect-test:
```
Decrypt 336: 3451C6EB2E94CB2FEBCB51484EFB7397438C2044281C510E0A0129A27D81DDA310E790E7737338ED460122EC8893CE30A12A02940A53DF98DAA533973E920D0B4920DD9C8F2A8C576684A484410AFCB8073984DAAE358C2A0CD4B12D57D47D21A30BCA178F4484600AA104383918624AA099C5880BF508475D1528F88C6809F9FCB13CD504A34294B56EFD5F0B60581B0A3B0E5EA3E4BA220E6C8D305AE376992706D9AC432136498C8C356C9697369F199EB35C02C241A0C7637BFE29631F719A2A6B97B2E05561C5D845068EA8072DEF8CA07A559ED9C012029715B4DE09F24DBEC79E7642726463905CF537D08CCFBC0E5579262F32DE0DCB24E67D27D24DDA739512C47F3CC7551FBE79A3961141D1C50BA31A7ACF20D723AAD084A035D17BD3FCF57B110B5ADD41CB46074109F6E5355175E5337CA37641E4E6C77D8342F680F2E0A9EB2DA5637D89F618E76051
Decrypted to 304: AB5498FCA9C615959DA6C194849491791E78DB2D485199650102C04052495DEB70BC26EF68391E0491E2DBCB6F9340451E228E715A588928795E1A32253E8B9D3B347F19F8D02F37B76232B753A5432CC55DECACF935FA142B3466F1D6A7A1D0839A56F41983BCBF1174302DA8285BA2AB7AC6CD9C5CF851E9A90C48DB71BBB13477F7EEDE5D78C0480A370D651E3B2B14038972F252ED5F00C50660EA8020D043EC66BCD226DBF0293E6AF96220BE582644BAD78C6F76A60520E498B7C4727A5DDF4F0D23EC2E9C71EC30F9145FC8750BAB67F67DFB4D76644AA5D5FAB408509D13C78FC279B0B43E2F89D333274D9F8BD3602407ABB2723D29A5C44AEC3C04D2493E261BEC7A103DCA455A808B4D2A96634F2D63280F3B4747CA7C2C154132D5E0C9BEA5552CB36B462A56B11BED29
```

It *isn't* encrypted in `openconnect-test1`, while `openconnect-test2` says:

```
Decrypt 336: DCBC5C41A46DA80008C59014072A7117C7541DD12578AE37DA00F0198AAE6277380D1CDC23AC5E4D3D9E5EC4EF1F9DD5A53C6315BA6293164819F6C294C9D56C98DDE6F00BC860CE70C9A89632E54C403B4679E144CBF3296DA8841BBC99C709F07787EB024D6BE2015E9AFC13CB98CEA25ED80E7B481188620DA1C66F2B06E624835AE8A631072B3E89CCE03FD3E775E69E0D62D3AEBC99B1863EB24EC4B46308B358CC41DED6205F4819D44396646B070C98DBFC181E9B538F323743203697D231327BD7E328D50A90B8CE32DD2F48721E5B72ED7A02E01D8C9414A9696CC8DA13373FE6337CDF44700426A76D9307B398257840DFDE0A21305D6ECBAA31B35729330B3028CAF194FC1D16499F3F2C0D678106C6106BF172179EF7E815615BE5CB9604BC2EBC8CE6EC5E411AC6F8FD2BA3A910397947E83DB898D8633F70887710D519DDF1B1BD2B72A3AB5BF3FDF3
Decrypted to 305: 00AB5498FCA9C615959DA6C194849491791E78DB2D485199650102C04052495DEB70BC26EF68391E0491E2DBCB6F9340451E228E715A588928795E1A32253E8B9D3B347F19F8D02F37B76232B753A5432CC55DECACF935FA142B3466F1D6A7A1D0839A56F41983BCBF1174302DA8285BA2AB7AC6CD9C5CF851E9A90C48DB71BBB13477F7EEDE5D78C0480A370D651E3B2B14038972F252ED5F00C50660EA8020D043EC66BCD226DBF0293E6AF96220BE582644BAD78C6F76A60520E498B7C4727A5DDF4F0D23EC2E9C71EC30F9145FC8750BAB67F67DFB4D76644AA5D5FAB408509D13C78FC279B0B43E2F89D333274D9F8BD3602407ABB2723D29A5C44AEC3C04D2493E261BEC7A103DCA455A808B4D2A96634F2D63280F3B4747CA7C2C154132D5E0C9BEA5552CB36B462A56B11BED29
```

All the tokens actually *work* with TLSv1.1, which ends up using `CKM_RSA_PKCS`, while TLSv1.2 ends up using `CKM_RSA_X_509`  and that's what fails. I wonder if that's why it wasn't seen before... but while TLSv1.3 is relatively new, TLSv1.2 isn't!

**Comment by dwmw2** [comment]
>  BTW, it is the call to RSA_private_encrypt that is failing, not the size check that SoftHSM performs.

That's true in the GnuTLS build which uses `CKM_RSA_PKCS_PSS`. In the OpenSSL build it does hit an explicit size check using `CKM_RSA_X_509`:

```
C_Sign
  IN: hSession = S1
  IN: pData = (304) "3PO\x1B\xFF\x7Fj\xD1\x01\xFE\xDE\xEEH\x9E\xE9\x1F\x96\x91\x8FT\xF5C\xC9\xBD\xF5D\x1A\xD5c\xF2\xDEh\xB6%A-<\xA0\xC2_\xA3..."
data 304 key modulus 305
Key 00AB5498FCA9C615959DA6C194849491791E78DB2D485199650102C04052495DEB70BC26EF68391E0491E2DBCB6F9340451E228E715A588928795E1A32253E8B9D3B347F19F8D02F37B76232B753A5432CC55DECACF935FA142B3466F1D6A7A1D0839A56F41983BCBF1174302DA8285BA2AB7AC6CD9C5CF851E9A90C48DB71BBB13477F7EEDE5D78C0480A370D651E3B2B14038972F252ED5F00C50660EA8020D043EC66BCD226DBF0293E6AF96220BE582644BAD78C6F76A60520E498B7C4727A5DDF4F0D23EC2E9C71EC30F9145FC8750BAB67F67DFB4D76644AA5D5FAB408509D13C78FC279B0B43E2F89D333274D9F8BD3602407ABB2723D29A5C44AEC3C04D2493E261BEC7A103DCA455A808B4D2A96634F2D63280F3B4747CA7C2C154132D5E0C9BEA5552CB36B462A56B11BED29
OSSLRSA.cpp(248): Size of data to sign does not match the modulus size
C_Sign = CKR_GENERAL_ERROR
C_Sign returned 5
```

**Comment by dwmw2** [comment]
Hm, although it is scripted I haven't actually tried importing for a while. 
```
[dwoodhou@i7 tests]$ rm -rf ../../tests/softhsm/*
[dwoodhou@i7 tests]$ make softhsm-setup0
SOFTHSM2_CONF=softhsm2.conf softhsm2-util --show-slots
Available slots:
Slot 0
    Slot info:
        Description:      SoftHSM slot ID 0x0                                             
        Manufacturer ID:  SoftHSM project                 
        Hardware version: 2.5
        Firmware version: 2.5
        Token present:    yes
    Token info:
        Manufacturer ID:  SoftHSM project                 
        Model:            SoftHSM v2      
        Hardware version: 2.5
        Firmware version: 2.5
        Serial number:                    
        Initialized:      no
        User PIN init.:   no
        Label:                                            
SOFTHSM2_CONF=softhsm2.conf softhsm2-util --init-token --slot 0 --label openconnect-test \
	--so-pin 12345678 --pin 1234
The token has been initialized and is reassigned to slot 889193699
SOFTHSM2_CONF=softhsm2.conf softhsm2-util --slot 0 --pin 1234 --import ../../tests/certs/user-key-pkcs8.pem \
	--label RSA --id 01
ERROR: The given slot does not exist.
make: *** [Makefile:1381: softhsm-setup0] Error 1

```

**Comment by dwmw2** [comment]
I've fixed that and reimported:
http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/fb40b9433eb0

... and then reimported again with SoftHSM 2.2 because it was failing on older distributions.

So I'm OK for now, but there is definitely scope for stripping the leading zeroes from existing tokens which have been imported with them by historical tools. I'll let you decide if you want to do that (which you can test with the token data in my git tree from before that commit), or just close this now.

Thanks.

**Comment by rijswijk** [comment]
OK, so what if you generate a key in the token and use that, is that an option? Just to find out if it is the import that is causing the problems.

**Comment by dwmw2** [comment]
To be clear, reimporting *did* work; I just needed to do the reimport with an older version of SoftHSM because importing with the latest then didn't work on older distros. I just assumed that was expected lack of backward compatibility: https://gitlab.com/openconnect/openconnect/-/jobs/522189972

If generating a key in the token (instead of importing) was causing a problem today, I'm guessing that someone would have pointed that out already. If you're asking me to go back to 2016 and generate keys instead of importing (which I suppose I *could* do by installing an appropriate older distro), I'm not sure we care.

Obviously I'm happy to perform additional useful tests but I'm not sure what you're looking for there, and suspect I addressed it with my initial clarification?

**Comment by rijswijk** [comment]
Sorry, seems I skipped over your message too quickly; good to hear the re-import works. I seem to remember this being an issue with ```p11tool``` from some other bug report; if you're OK for now I say we close this issue, and I chalk it up as something to keep an eye on.
