### ISSUE TITLE
CMAKE support ZLib

### ISSUE THREAD

**Issue by rbroggi** [opendnssec/SoftHSMv2#549]
Good morning,

I've been trying to compile using cmake along with my own ZLib installation but I see no support for it on CMAKE or autoconfig tools. Specifically, my compilation process fails during the check in the line:

`check_library_exists(crypto "BN_new" "${CRYPTO_LIB_DIR}" HAVE_LIBCRYPTO)`
on file:
`modules/CompilerOptions.cmake`

I'm using version 2.5.0. 

I've also attached part of the cmake error logs:
[CMakeError.log](https://github.com/opendnssec/SoftHSMv2/files/4580080/CMakeError.log)

Does someone knows how to workaround this issue?

Thank you,

Rodrigo

**Comment by rijswijk** [comment]
ZLib is not a direct dependency of SoftHSM v2, the check that seems to be failing for you is related to OpenSSL. From the log you provide it looks like the OpenSSL that SoftHSM is building against hasn't been linked with your own ZLib build. I'm not a CMake expert, but it seems to me that you also need to build OpenSSL yourself and ensure it links against your own ZLib build.
