### ISSUE TITLE
Error while Establishing multiple times connection with same user

### ISSUE THREAD

**Issue by marywang372** [opendnssec/SoftHSMv2#552]
Hi Team,

I am integrating Axway API Platform with softHSM. I have created one slot with one token and multiple realms.
While restarting the API platform it tries to connect with softHSM for each realm. For the first realm it is initialized and established a connection with softHSM but for the second one it gives an error because it tries to establish a connection again. I get a PKCS11 Exception C-Login failed user already logged in.

Is there a way to bypass this issue or any solution ?

Regards
Mary

**Comment by rijswijk** [comment]
This is a limitation of the PKCS #11 specification; a user can only log in once to a single token, logging in in another session will result in ```CKR_USER_ALREADY_LOGGED_IN``` being returned. Note, though, that this is not an error message, but a warning, to notify you that you are sharing a logged in session. If your goal is to have multiple concurrent sessions, you can either log in once, or accept that this warning occurs and ignore it. Note, though, that once the user logs out, all sessions are automatically logged out.

**Comment by marywang372** [comment]
Hi Rijswijk,

Thanks for your comment.
But the problem is realm is failed to load because the login failed.
See the snapshot attached.

![softHSM Error](https://user-images.githubusercontent.com/29123413/81926074-b7ad7580-95e1-11ea-8d1c-937c6e94711c.png)

**Comment by rijswijk** [comment]
This is exactly the situation I described in the answer; the software you are using is reporting that the PKCS #11 API returned ```CKR_USER_ALREADY_LOGGED_IN```; this is either being interpreted incorrectly by the software ("Axway"), or you are using that software in a manner in which it was not intended to be used. I'm afraid we cannot really help you with this, SoftHSM behaves according to the PKCS #11 specification, and you would see exactly the same behaviour with most other PKCS #11 libraries.
