### ISSUE TITLE
Testing Edwards curves

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#559]
I'm just adding in some tests for Edwards curves in my testing tool.  Just want to raise a few points (which did get me confused for a while).

- When generating a keypair for Edwards curves you must specify the CKK_EC_EDWARDS key type in the public and private key templates. Unfortunately the latest version of the 3.0 PKCS#11 current mechanism spec specifies that you should use CKK_EC.  

- I generated a edwards25519 curve key pair successfully - but only using the OID specified in RFC8410.  However, the method of using a printable string (as shown in the PKCS#11 current mechanism example) causes a CKR_GENERAL_ERROR.  Not sure whether the printable string CHOICE is not supported at all in SoftHSMv2. If it is then the curveName "edwards25519" is not supported.

- CK_MECHANISM_INFO reports a min key size of 256 and 456 (256 = curve 25519 and 456 = curve 448). However, this does not match the values of 255 and 448 specified in section 2.3.10 of the 3.0 PKCS#11 current mechanisms. RFC 8072 says the private key sizes should be 32 and 57 bytes respectively - which matches what SoftHSMv2 reports.  So is the PKCS#11 spec is wrong?

**Comment by johughes99** [comment]
As an update - I also tried the printable strings `id-Ed25519` and `id-Ed448`.  This also gave CKR_GENERAL_ERROR. Hence, my assumption is that SoftHSM does not support the curveName  option in CKA_EC_PARAMS.

**Comment by johughes99** [comment]
That's what i was doing, for example:

`CK_BYTE X25519_NAME[] = {0x13, 0x09, 0x69, 0x64, 0x2D, 0x58, 0x32, 0x35, 0x35, 0x31, 0x39};`

**Comment by rijswijk** [comment]
That OID is not the one from the PKCS #11 spec, you should probably have a look at the EDDSA test cases in the SoftHSM source code (which has the OIDs), e.g.: [here](https://github.com/opendnssec/SoftHSMv2/pull/526/commits/baeac85d46b5af284f1c43754fa8deaed0aded28#diff-1a4621e1c86e66d248f7b9f955c0059c)

**Comment by johughes99** [comment]
0x13, 0x09, 0x69, 0x64, 0x2D, 0x58, 0x32, 0x35, 0x35, 0x31, 0x39 is the ASN.1 printable string of "id-X25519"  - as taken from RFC8410 - not an OID

The PKCS#11 spec in 2.3.5 example gives the ASN.1 printable string as curve25519 - which isnt one of the value curve names in RFC8410  (or I believe in 8032).  Let me check the test code....

**Comment by johughes99** [comment]
Looking at PKCS#11 specs again -they do seem to be defined - :-)

Let me check through all this again - and retest

**Comment by johughes99** [comment]
All fine.  Using the curve names edwards25519 and edwards448 works just fine.

What about support for the Montgomery curves?  On testing these with either the OIDs or the curve names curve25519 and curve448 I get the error CKR_MECHANISM_INVALID.  

Is the CKM_EC_MONTGOMERY_KEY_PAIR_GEN mechanism not supported yet - even though the tests seem to include support for them?

**Comment by rijswijk** [comment]
The mechanism is indeed not supported, and there are currently also no plans to support it. Can you indicate why you need it?

**Comment by johughes99** [comment]
No I don't need it. Its just an observation.
