### ISSUE TITLE
Allow file modes to be configured

### ISSUE THREAD

**Issue by nomis** [opendnssec/SoftHSMv2#560]
#40 removed read permission from group/other for SoftHSM tokens

This makes it difficult to backup these files because no groups have access  to the files, even if there are additional default ACLs on the directory allowing other groups to access them.

It needs to be possible to configure a umask of `0027` instead of always using `0077`.

**Comment by rijswijk** [comment]
We can put this in as a feature request, but note that SoftHSM is maintained entirely in volunteer time, so it may be some time before this is picked up. We would welcome a pull request.
