### ISSUE TITLE
ulSessionCount contains CK_INFORMATION_UNAVAILABLE

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#572]
Im querying the value of ulSessionCount in the CK_TOKEN_INFO structure returned from a call to C_GetTokenInfo.

It always contains CK_INFORMATION_UNAVAILABLE (ie -1). Is this by design?

**Comment by rijswijk** [comment]
Yup, that's by design, check out [line 517 of `Token.cpp`](https://github.com/opendnssec/SoftHSMv2/blob/827ab25e9d5c571502eaf7900a5cc1732223240f/src/lib/slot_mgr/Token.cpp#L517)

**Comment by johughes99** [comment]
That's a bit of pain. Every other device I have tested so far supports this.

C'est la vie.
