### ISSUE TITLE
Windows client library (dll) for connecting SoftHSMv2

### ISSUE THREAD

**Issue by pfelixz** [opendnssec/SoftHSMv2#581]
We are evaluating SoftHSMv2 technology to virtualize HSM for signing in pre-production environments. We are using in windows a PKCS11Interop (https://github.com/Pkcs11Interop/Pkcs11Interop) which is C# wrapper (API) for pkcs11 clients for HSM vendor (each vendor provides a pkcs11 client library dll). 
Is there any client library for windows x86/x64 for accessing remotely a SoftHSMv2 instance/server (in linux box). If not, there is any way to use SoftHSMv2 remotely as a remote server for several clients.

**Comment by rijswijk** [comment]
It is possible to realise this type of functionality with `p11-kit`, but whether or not that will work on Windows I don't know. More information here: [https://p11-glue.github.io/p11-glue/p11-kit/manual/remoting.html](https://p11-glue.github.io/p11-glue/p11-kit/manual/remoting.html)

**Comment by realmfoo** [comment]
@pfelixz You could try https://github.com/realmfoo/pkcs11-proxy/tree/pkcs11%232.40 (branch pkcs11#2.40). I've managed to compile `pkcs11-proxy.dll` with VS2019 and connect to `pkcs11-daemon` running on a linux server.

**Comment by pfelixz** [comment]
Hi @rijswijk after struggling to get [p11-kit](https://p11-glue.github.io/p11-glue/p11-kit.html) windows x64 binaries (managed to do it thru [msys2](https://www.msys2.org/) and [mingw-w64-p11-kit](https://packages.msys2.org/package/mingw-w64-x86_64-p11-kit)) and extract all its dependencies, 

I was able to put it running but not able to put it working by finding the right configuration of p11-kit-remote to communicate with this a docker [hsm-pkcs11proxy](https://hub.docker.com/r/gbolo/hsm-pkcs11proxy/). (remote | ssh root@127.0.0.1 -p 5657 remote /usr/local/lib/softhsm/libsofthsm2.so). If it is not must to ask, can you please share the necessary steps to install fresh docker station with SoftHSMv2 and p-kit packages and the necessary p11-kit client configuration files.

**Comment by pfelixz** [comment]
@realmfoo after struggling i was unable to complie [realmfoo/pkcs11-proxy](https://github.com/realmfoo/pkcs11-proxy/tree/pkcs11%232.40) in windows with vs2019. Neither thru [msys2](https://www.msys2.org/) or [cmake](https://cmake.org/). Allways the unix include headers. If it is not must to ask, can you please how could you managed to build it in windows.

**Comment by realmfoo** [comment]
> @realmfoo after struggling i was unable to complie [realmfoo/pkcs11-proxy](https://github.com/realmfoo/pkcs11-proxy/tree/pkcs11%232.40) in windows with vs2019. Neither thru [msys2](https://www.msys2.org/) or [cmake](https://cmake.org/). Allways the unix include headers. If it is not must to ask, can you please how could you managed to build it in windows.

Have you switched to branch `pkcs11#2.40` before build it? I used toolset `msvc_x64_x64`, generator `Ninja`. Feel free to submit an issue in [realmfoo/pkcs11-proxy](https://github.com/realmfoo/pkcs11-proxy) with error messages or screenshots.
