### ISSUE TITLE
C_Encrypt etc not terminating operation

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#585]
I have been doing a few tests on tokens in respect of handling errors from C_Encrypt etc

as per the spec, which says for C_Encrypt

> The encryption operation MUST have been initialized with C_EncryptInit.  A call to C_Encrypt always terminates the active encryption operation unless it returns CKR_BUFFER_TOO_SMALL or is a successful call (i.e., one which returns CKR_OK) to determine the length of the buffer needed to hold the ciphertext.

Therefore any error other than CKR_BUFFER_TOO_SMALL should terminate the current operation. 

I'm finding for SoftHSMv2 this is not always true - as per my log from below.

`--- Test 8 - Call C_Encrypt with a NULL ptr to the cleartext data =>CKR_ARGUMENTS_BAD
ERROR: call to C_Encrypt did not terminate the operation

--- Test 11 - Call C_Encrypt with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
ERROR: call to C_Encrypt did not terminate the operation

--- Test 14 - Call C_EncryptUpdate with a NULL ptr to the cleartext data =>CKR_ARGUMENTS_BAD
ERROR: call to C_EncryptUpdate did not terminate the operation

--- Test 17 - Call C_EncryptUpdate with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
ERROR: call to C_EncryptUpdate did not terminate the operation

--- Test 57 - Call C_Decrypt with a NULL ptr to the cleartext data =>CKR_ARGUMENTS_BAD
ERROR: call to C_Decrypt did not terminate the operation

--- Test 60 - Call C_Decrypt with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
ERROR: call to C_Decrypt did not terminate the operation

--- Test 63 - Call C_DecryptUpdate with a NULL ptr to the cleartext data =>CKR_ARGUMENTS_BAD
ERROR: call to C_DecryptUpdate did not terminate the operation

--- Test 66 - Call C_DecryptUpdate with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
ERROR: call to C_DecryptUpdate did not terminate the operation`

**Comment by rijswijk** [comment]
Thanks for reporting this, #592 will fix this once merged. If you want to test, clone a fresh repository and switch to branch `fix_issue_585`.

**Comment by johughes99** [comment]
Perfect.  Fixes the problem  See below for the results - passes all tests:

******************************************************************************
Starting Encryption General TEST GROUP
******************************************************************************
--- Test 1 - Call C_Encrypt without a previous call to C_EncryptInit =>CKR_OPERATION_NOT_INITIALIZED
--- Test 2 - Call C_EncryptUpdate without a previous call to C_EncryptInit =>CKR_OPERATION_NOT_INITIALIZED
--- Test 3 - Call C_EncryptFinal without a previous call to C_EncryptInit =>CKR_OPERATION_NOT_INITIALIZED
--- Test 4 - Call C_EncryptInit with a 0 for the session handle =>CKR_SESSION_HANDLE_INVALID
--- Test 5 - Call C_EncryptInit with a NULL ptr for the mechanism =>CKR_ARGUMENTS_BAD||(CKR_MECHANISM_INVALID
--- Test 6 - Call C_EncryptInit with a 0 for the object handle =>CKR_OBJECT_HANDLE_INVALID||CKR_KEY_HANDLE_INVALID
--- Test 7 - Call C_Encrypt with a 0 for the session handle =>CKR_SESSION_HANDLE_INVALID
--- Test 8 - Call C_Encrypt with a NULL ptr to the cleartext data =>CKR_ARGUMENTS_BAD
--- Test 9 - Call C_Encrypt with a 0 length for the cleartext data =>CKR_OK
--- Test 10 - Call C_Encrypt with a NULL ptr for encrypted part =>CKR_OK
--- Test 11 - Call C_Encrypt with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
--- Test 12 - Call C_Encrypt with a 0 length for the encrypted buffer =>CKR_BUFFER_TOO_SMALL
--- Test 13 - Call C_EncryptUpdate with a 0 for the session handle =>CKR_SESSION_HANDLE_INVALID
--- Test 14 - Call C_EncryptUpdate with a NULL ptr to the cleartext data =>CKR_ARGUMENTS_BAD
--- Test 15 - Call C_EncryptUpdate with a 0 length for the cleartext data =>CKR_OK
--- Test 16 - Call C_EncryptUpdate with a NULL ptr for encrypted part =>CKR_OK
--- Test 17 - Call C_EncryptUpdate with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
--- Test 18 - Call C_EncryptUpdate with a 0 length for the encrypted buffer =>CKR_BUFFER_TOO_SMALL
--- Test 19 - Call C_EncryptFinal with a 0 for the session handle =>CKR_SESSION_HANDLE_INVALID
--- Test 20 - Call C_EncryptFinal with a NULL ptr for encrypted part =>CKR_OK
--- Test 21 - Call C_EncryptFinal with a 0 length for the encrypted buffer =>CKR_OK
--- Test 22 - Call C_EncryptFinal with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
--- Test 50 - Call C_Decrypt without a previous call to C_DecryptInit =>CKR_OPERATION_NOT_INITIALIZED
--- Test 51 - Call C_DecryptUpdate without a previous call to C_DecryptInit =>CKR_OPERATION_NOT_INITIALIZED
--- Test 52 - Call C_DecryptFinal without a previous call to C_DecryptInit =>CKR_OPERATION_NOT_INITIALIZED
--- Test 53 - Call C_DecryptInit with a 0 for the session handle =>CKR_SESSION_HANDLE_INVALID
--- Test 54 - Call C_DecryptInit with a NULL ptr for the mechanism =>CKR_ARGUMENTS_BAD||(CKR_MECHANISM_INVALID
--- Test 55 - Call C_DecryptInit with a 0 for the object handle =>CKR_OBJECT_HANDLE_INVALID||CKR_KEY_HANDLE_INVALID
--- Test 56 - Call C_Decrypt with a 0 for the session handle =>CKR_SESSION_HANDLE_INVALID
--- Test 57 - Call C_Decrypt with a NULL ptr to the cleartext data =>CKR_ARGUMENTS_BAD
--- Test 58 - Call C_Decrypt with a 0 length for the cleartext data =>CKR_OK
--- Test 59 - Call C_Decrypt with a NULL ptr for encrypted part =>CKR_OK
--- Test 60 - Call C_Decrypt with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
--- Test 61 - Call C_Decrypt with a 0 length for the encrypted buffer =>CKR_BUFFER_TOO_SMALL
--- Test 62 - Call C_DecryptUpdate with a 0 for the session handle =>CKR_SESSION_HANDLE_INVALID
--- Test 63 - Call C_DecryptUpdate with a NULL ptr to the cleartext data =>CKR_ARGUMENTS_BAD
--- Test 64 - Call C_DecryptUpdate with a 0 length for the cleartext data =>CKR_OK
--- Test 65 - Call C_DecryptUpdate with a NULL ptr for encrypted part => CKR_OK
--- Test 66 - Call C_DecryptUpdate with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
--- Test 67 - Call C_DecryptUpdatet with a 0 length for the encrypted buffer =>CKR_BUFFER_TOO_SMALL
--- Test 68 - Call C_DecryptFinal with a 0 for the session handle =>CKR_SESSION_HANDLE_INVALID
--- Test 69 - Call C_DecryptFinal with a NULL ptr for encrypted part =>CKR_OK
--- Test 70 - Call C_DecryptFinal with a 0 length for the encrypted buffer =>CKR_OK
--- Test 71 - Call C_DecryptFinal with a null ptr for the length for the encrypted buffer =>CKR_ARGUMENTS_BAD
--- Test 90 - Call C_GenerateKey with an invalid session handle =>CKR_SESSION_HANDLE_INVALID
--- Test 91 - Call C_GenerateKey with a NULL pointer to the mechanisms list =>CKR_ARGUMENTS_BAD||(CKR_MECHANISM_INVALID
--- Test 92 - Call C_GenerateKey with a NULL ptr to the attribute template =>CKR_ARGUMENTS_BAD
--- Test 93 - Call C_GenerateKey with a zero length attribute template =>CKR_TEMPLATE_INCOMPLETE||CKR_TEMPLATE_INCONSISTENT
--- Test 94 - Call C_GenerateKey with a NULL ptr to the object handle =>CKR_ARGUMENTS_BAD
--- Test 95 - Call C_GenerateKey with an asymmetric key gen mechanism =>CKR_MECHANISM_INVALID
--- Test 96 - Call C_GenerateKey without a keytype =>CKR_OK||CKR_TEMPLATE_INCONSISTENT
--- Test 97 - Call C_GenerateKey with an invalid keytype =>CKR_TEMPLATE_INCONSISTENT||CKR_KEY_TYPE_INCONSISTENT
--- Test 98 - Call C_GenerateKey successfully and then make sure CKA_LOCAL set to CK_TRUE =>CKR_OK
------------------------------------------------------------------------------
Results: 53 passed:  0 failed:  0 not run: 
------------------------------------------------------------------------------
