### ISSUE TITLE
cannot make softhsmv2 2.6.1

### ISSUE THREAD

**Issue by juyuancai** [opendnssec/SoftHSMv2#586]
I use tag 2.6.1  and when I make code ,i got errors below:

SoftHSM.cpp: In member function 'void SoftHSM::prepareSupportedMecahnisms(std::map<std::basic_string<char>, long unsigned int>&)':
SoftHSM.cpp:784:7: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
  for (auto it = t.begin(); it != t.end(); ++it)
       ^
SoftHSM.cpp:784:12: error: 'it' does not name a type
  for (auto it = t.begin(); it != t.end(); ++it)
            ^
SoftHSM.cpp:784:28: error: expected ';' before 'it'
  for (auto it = t.begin(); it != t.end(); ++it)
                            ^
SoftHSM.cpp:784:28: error: 'it' was not declared in this scope
SoftHSM.cpp: In member function 'CK_RV SoftHSM::C_GetMechanismList(CK_SLOT_ID, CK_MECHANISM_TYPE_PTR, CK_ULONG_PTR)':
SoftHSM.cpp:856:2: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
  auto it = supportedMechanisms.cbegin();
  ^
SoftHSM.cpp:856:7: error: 'it' does not name a type
  auto it = supportedMechanisms.cbegin();
       ^
SoftHSM.cpp:857:9: error: 'it' was not declared in this scope
  for (; it != supportedMechanisms.cend(); it++, i++)
         ^
SoftHSM.cpp:857:35: error: 'class std::list<long unsigned int>' has no member named 'cend'
  for (; it != supportedMechanisms.cend(); it++, i++)
                                   ^
SoftHSM.cpp: In member function 'bool SoftHSM::isMechanismPermitted(OSObject*, CK_MECHANISM_PTR)':
SoftHSM.cpp:12427:2: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
  auto it = std::find(mechs.begin(), mechs.end(), pMechanism->mechanism);
  ^
SoftHSM.cpp:12427:7: error: 'it' does not name a type
  auto it = std::find(mechs.begin(), mechs.end(), pMechanism->mechanism);
       ^
SoftHSM.cpp:12428:6: error: 'it' was not declared in this scope
  if (it == mechs.end())

what's can I do now

**Comment by Aearsis** [comment]
Use `-std=c++11` (at least). See the discussion on #539 for more details.
