### ISSUE TITLE
Log not being sent to syslog on Mac

### ISSUE THREAD

**Issue by missilerider** [opendnssec/SoftHSMv2#588]
I've completed Mac (Big Sur) installation and falling into issues. Found on README that logs should be sent to syslog, but I cannot find any reference to softhsm. I don't know if this is a Mac specific issue or maybe I cannot find the correct configuration or log source.

I've checked with "syslog" and "log show" without luck and ERROR, INFO and DEBUG log.level.

Thanks in advance!

Alf

**Comment by rijswijk** [comment]
I don't have a Big Sur installation to check this on, but did you install the Homebrew formula for SoftHSM? If not, you might want to check that out, as it is a macOS-specific build.

**Comment by keldonin** [comment]
`log show --process [name-of-your-process]` works for me, but It's on Catalina.

```
$ log stream --process p11ls
Filtering the log data using "process BEGINSWITH[cd] "p11ls""
Timestamp                       Thread     Type        Activity             PID    TTL
2020-12-23 13:39:21.696821+0100 0x2e0553   Default     0x0                  75223  0    p11ls: (libsofthsm2.so) Configuration.cpp(96): Missing slots.mechanisms in configuration. Using default value: ALL
```

**Comment by rijswijk** [comment]
@missilerider did the suggested solution work? Closing the issue for now, but feel free to reopen if the approach suggested by @keldonin does not work for you.

**Comment by missilerider** [comment]
Hi all,

Happy new year and sorry for my late reply; I've been a little bit out and am not very used to Github issue following (my fault).

I'm afraid I don't get any log about softhsm, but it seems to be working ok. My log level is DEBUG in softhsm2.conf, and OS version is BigSur 11.1 and I followed the macOS specific brew installation carefully.

If you need further information or have to perform tests, please let me know (and be patient, please!).

BR and congrats for your great work!
