### ISSUE TITLE
EDDSA signature failing - OSSLEDDSA.cpp(90): EDDSA sign init failed (0x060A109E) - looking for a message digest?

### ISSUE THREAD

**Issue by keldonin** [opendnssec/SoftHSMv2#589]
When trying to perform signature using a valid ED25519 private key generated on the token, calls to `C_Sign()` fail with a `CKR_GENERAL_ERROR`.

```
18: C_SignInit
>> 2020-12-23 10:30:25.007
[in] hSession = 0x1
pMechanism->type=CKM_EDDSA
[in] hKey = 0x2
<< 2020-12-23 10:30:25.008
Returned:  0 CKR_OK

19: C_Sign
>> 2020-12-23 10:30:25.008
[in] hSession = 0x1
[in] pData[ulDataLen] 0000000801a7d6e0 / 68
    00000000  30 42 02 01 00 30 0F 31 0D 30 0B 06 03 55 04 03  0B...0.1.0...U..
    00000010  0C 04 74 65 73 74 30 2A 30 05 06 03 2B 65 70 03  ..test0*0...+ep.
    00000020  21 00 00 50 0E 42 50 CB 2E 59 C6 75 A8 15 DB EF  !..P.BP..Y.u....
    00000030  9A 33 1F A4 B5 49 D9 0D 8D 81 F9 61 2A E7 09 AB  .3...I.....a*...
    00000040  23 7E A0 00                                      #~..
<< 2020-12-23 10:30:25.008
Returned:  5 CKR_GENERAL_ERROR
```
When setting library verbosity level to DEBUG, it yields the following:
```
OSSLEDDSA.cpp(90): EDDSA sign init failed (0x060A109E)
 ```

The OpenSSL code refers to OpenSSL EVP library, function `EVP_F_DO_SIGVER_INIT`, i.e. within `do_sigver_init()` from `crypto/evp/m_sigver.c` and is related to not finding a default digest.

`C_SigInit()` is invoked with no `CK_EDDSA_PARAMS` structure, assuming that SoftHSM implements the `PureEdDSA` variant of the algorithm.

Possibly a bug?

**Comment by rijswijk** [comment]
The call to `C_SignInit` does not require parameters (see also the testcases in `src/lib/test/SignVerifyTests.cpp`). Running `make check` should exercise this function, and on my test system (Ubuntu 20.04 LTS) the tests pass without problems. What environment are you running your test on?

**Comment by keldonin** [comment]
Here is the piece of source code for `C_SignInit()`, as you can see, no parameter is provided:

```lang=c
    CK_MECHANISM mechanism = { CKM_EDDSA, NULL_PTR, 0 };
    ...
    size_t p11siglen = EVP_PKEY_size( EVP_PKEY_CTX_get0_pkey( EVP_MD_CTX_pkey_ctx ( ctx ) ) );
    ...
    rv = static_st.p11Context->FunctionList.C_SignInit(static_st.p11Context->Session,
                                                       &mechanism,
                                                       static_st.hPrivateKey);
```

It is actually `C_Sign()` that fails, not `C_SignInit()`.

Configuration:
- SoftHSM commit 20a53bd083a6134ce2230f80edda5dc8be0366bd, but the issue was found under v2.6.1
- OpenSSL version: `OpenSSL 1.1.1h-freebsd  22 Sep 2020`
- OS: `FreeBSD 12.2-RELEASE`

**Comment by keldonin** [comment]
@rijswijk, I confirm that the test suite `make check` passes through without any problem, and that `C_Sign()` works as expected on FreeBSD. Currently looking at the condition that is systematically triggering the problem described above.

**Comment by keldonin** [comment]
OK, I found the culprit, and it is not directly related to SoftHSM library, but to the way how OpenSSL handles flags on `EVP_PKEY_METHOD` objects. Instrumenting `p11test` was quite useful in discovering the issue, thanks a lot for pointing out to `make check`.

Closing the issue (not an issue).
