### ISSUE TITLE
Support for mbed TLS?

### ISSUE THREAD

**Issue by tx-softhsm** [opendnssec/SoftHSMv2#609]
Hi.
SoftHSM supports OpenSSL and Botan.
Are there any plans to support also mbed TLS?

**Comment by rijswijk** [comment]
There are currently no concrete plans to support additional backend libraries. I'm not familiar with the API of mbed TLS, but if it is similar to, e.g., the OpenSSL EVP API, it should not be that difficult to write support for such a backend. If, on the other hand, the underlying API model is quite different, it may be tricky to add support. Architecturally, the crypto backends are implemented underneath a generic abstraction layer, which happened to work fine for OpenSSL and Botan.

**Comment by tx-softhsm** [comment]
OK, thank you for your quick answer.
Being curiously... am I the first one who asked? :-)

**Comment by rijswijk** [comment]
You are indeed the first that asked about this particular library. In the past we considered adding support for Crypto++, but did not pursue this due to development resource constraints. Is it OK if I close the issue?

**Comment by tx-softhsm** [comment]
Yes, please close.
And thanks for your answers.
