### ISSUE TITLE
 how to get the origin ECC private key from C_WarpKey

### ISSUE THREAD

**Issue by c20liu** [opendnssec/SoftHSMv2#622]
I want to export an ECC private key from softhsmv2 based on OpenSSL 1.1.1.  I use C_WarpKey and  passed "CKM_AES_KEY_WRAP" as mechanism, didn't passed the IV,   It can be executed successfully. 

According to my understanding, C_WrapKey is an encryption of PKCS#8 encoding,  so I want to use C_Decrypt to get the origin ECC private key information, I don't know how to pass parameters，I try  CKM_AES_ECB and CKM_AES_CBC , then use "openssl ec -in internal_priv_sk -pubout -out internal_priv_sk.pem"  to verify whether the private key is valied,  they all report：

```
read EC key
unable to load Key
140644277147456:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:crypto/asn1/asn1_lib.c:101:
140644277147456:error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header:crypto/asn1/tasn_dec.c:1137:
140644277147456:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:309:Type=PKCS8_PRIV_KEY_INFO
140644277147456:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:crypto/pem/pem_pkey.c:88:
```

so how can i get the origin ECC private key?  Thanks

**Comment by dengert** [comment]
Should you be using C_UnWrap, rather then  C_Decrypt? 

"openssl ec -in internal_priv_sk -pubout -out internal_priv_sk.pem" 
Is internal_priv_sk in PEM or DER format? i.e. try adding  `-inform DER`

Maybe https://tools.ietf.org/html/rfc5208 and https://tools.ietf.org/html/rfc5958 might help. 

Do you have the ASN1 in hex to see if it can be parsed?

**Comment by c20liu** [comment]
> Should you be using C_UnWrap, rather then C_Decrypt?
> 
> "openssl ec -in internal_priv_sk -pubout -out internal_priv_sk.pem"
> Is internal_priv_sk in PEM or DER format? i.e. try adding `-inform DER`
> 
> Maybe https://tools.ietf.org/html/rfc5208 and https://tools.ietf.org/html/rfc5958 might help.
> 
> Do you have the ASN1 in hex to see if it can be parsed?

Hi, dengert.
Thanks for your help.
Because of the lack of professional cryptography knowledge, it took some time to learn these standards and specifications.
Based on my study and understanding, CKM_AES_KEY_WRAP is an encryption method different from AES_ECB or AES_CBC (it is based the AES secret algorithm). I don’t know if I understand it, right? Therefore, the private key derived from the HSM using CKM_AES_KEY_WRAP cannot be decrypted simply with Decrypt (AES_ECB/AES_CBC)
