### ISSUE TITLE
Cannot find objects after C_CloseSession / C_OpenSession and log back in

### ISSUE THREAD

**Issue by pinheadmz** [opendnssec/SoftHSMv2#636]
I am writing an application that loads softhsm library to sign messages. In my test, I can generate key pairs in softhsm, and even insert externally-generated key pairs into softhsm. After this is done I can `C_FindObjects` and get all these keys back, and sign with them.

However, to simulate a new session I call `C_Logout`, `C_CloseSession ` and `C_Finalize` and then `C_Initialize`, `C_OpenSession` and `C_Login` with the same user PIN -- this time, `C_FindObjects` returns nothing (there is only one slot in use and I am logged in to that slot).

I have tried configuring both `db` and `file` backends in `softhsm2.conf` and I can see that some data is being written to disk -- although in `file` mode, the data written to `/var/lib/softhsm/tokens` looks way to small (~4k) to actually have all three keypairs included...

Am I missing an option (or perhaps a PKCS#11 attribute?) to persist keys when the application restarts?

**Comment by pinheadmz** [comment]
Ah got it:
`{ type: pkcs11js.CKA_TOKEN, value: true }`

never mind and thanks for SoftHSM!

**Comment by santosh-shaastry** [comment]
@pinheadmz thank you. Did you use the key pairs for sign & verify use case? Or did you happen to use the keys generated for the "verify" mechanism and that happened for the encryption/decryption use case?

**Comment by pinheadmz** [comment]
@santosh-shaastry All I use the keys for is signing in this test, I actually verify the signature with an external library, to double check that I signed correctly.
