### ISSUE TITLE
ssh-add -s issue "agent refused operation"

### ISSUE THREAD

**Issue by spfendtner** [opendnssec/SoftHSMv2#637]
I can use ssh -I /usr/lib/softhsm/libsofthsm2.so user@host without problems.
But ssh-add -s to add the pkcs11 lib to the agent to cache the PIN does not. 

It says:
`Enter passphrase for PKCS#11: `
`Could not add card "/usr/lib/softhsm/libsofthsm2.so": agent refused operation`

I have no problems doing this with real hardware like yubikeys.
Any indication where I could dig further?

**Comment by rijswijk** [comment]
Looks like the SSH agent is the culprit, perhaps it detects that SoftHSM is not a removable token (like a Yubikey) and treats it differently? I'd suggest digging into the documentation of the SSH agent. SoftHSM does not have any specific functionality that would block this.

**Comment by spfendtner** [comment]
I found this trick which works for me to. It pipes the PIN trough stdin. 
[https://github.com/openssh/openssh-portable/blob/master/regress/agent-pkcs11.sh](https://github.com/openssh/openssh-portable/blob/master/regress/agent-pkcs11.sh)
