### ISSUE TITLE
Can't find OpenSSL headers- during ./configure 

### ISSUE THREAD

**Issue by sousoul** [opendnssec/SoftHSMv2#662]
I want to install SoftHSM v2.5 from source code on MacOS, But I meet this configure error: 
checking for openssl/ssl.h... no
configure: error: Can't find OpenSSL headers

I am confused and how can I solve this problem?

**Comment by rijswijk** [comment]
Installing developer tools on macOS no longer installs OpenSSL by default (Apple uses their own crypto library). In order to build SoftHSM, you'll need to install a third-party OpenSSL package, probably the best option is to install the one from Homebrew.
