### ISSUE TITLE
Null dereference in C_UnwrapKey

### ISSUE THREAD

**Issue by Eliot-Roxbergh** [opendnssec/SoftHSMv2#673]
https://github.com/opendnssec/SoftHSMv2/blob/28c67fe771131fa31720258bd485089c108ec9bf/src/lib/SoftHSM.cpp#L7124-L7127

Due to an incorrect if statement, null dereference is possible on line 7126.

Compare with similar statements in the same file,

https://github.com/opendnssec/SoftHSMv2/blob/28c67fe771131fa31720258bd485089c108ec9bf/src/lib/SoftHSM.cpp#L7784-L7786

I am not able to do a PR, any help is welcome.

**Comment by rijswijk** [comment]
Good spot, this was indeed an error in an `if` statement, I merged a fix to the `develop` branch.
